#!/bin/bash

# script alias to the waf engine script

# source the environment only if DEVTOOLS_COMPUTER_ID is not already defined
printf "checking environment... "
if [ -z "$DEVTOOLS_COMPUTER_ID" ]; then
    env='unstable'
    [ `hg branch | egrep -c 'v[0-9]+'` -eq 1 ] && env='stable-updates'
    [ "${WAF_SUFFIX}" = "mpi" ] && env=${env}_${WAF_SUFFIX}
    fenv=$HOME/dev/codeaster/devtools/etc/env_${env}.sh
    if [ -e ${fenv} ]; then
        . ${fenv}
        echo "loading ${fenv}"
    else
        echo "no found"
    fi
else
    echo "already set"
fi

${0}.engine ${*}
