      SUBROUTINE ARLCAR(NOMARL,BASE)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 13/10/2009   AUTEUR CAO B.CAO 
C ======================================================================
C COPYRIGHT (C) 1991 - 2007  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE MEUNIER S.MEUNIER
C
      IMPLICIT NONE
      CHARACTER*1 BASE
      CHARACTER*8 NOMARL
C
C ----------------------------------------------------------------------
C
C ROUTINE ARLEQUIN
C
C ENRICHISSEMENT DE LA SD PRINCIPALE ARLEQUIN
C
C ----------------------------------------------------------------------
C
C
C I/O  NOMARL : NOM DE LA SD PRINCIPALE ARLEQUIN
C IN   BASE   : TYPE DE BASE ('V' OU 'G')
C
C SD EN SORTIE :
C ==============
C
C .TRAVR : VECTEUR DE TRAVAIL DE TYPE R
C .TRAVI : VECTEUR DE TRAVAIL DE TYPE I
C .TRAVL : VECTEUR DE TRAVAIL DE TYPE L
C .POIDS : NOM DE L'OBJET .POIDS_MAILLE
C
C
C ----------------------------------------------------------------------
C
      INTEGER      IBID,NUMHAR,ARLGEI
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
C --- PARAMETRE POUR LONGUEUR DU VECTEUR DE TRAVAIL
C
      NUMHAR = ARLGEI(NOMARL,'NH    ')
C
C --- CREATION VECTEURS JEVEUX
C
      CALL WKVECT(NOMARL(1:8)//'.TRAVR',BASE//' V R'  ,12+276*NUMHAR ,
     &  IBID)
      CALL WKVECT(NOMARL(1:8)//'.TRAVI',BASE//' V I'  ,56+1536*NUMHAR,
     & IBID)
      CALL WKVECT(NOMARL(1:8)//'.TRAVL',BASE//' V L'  ,24*NUMHAR     ,
     & IBID)
      CALL WKVECT(NOMARL(1:8)//'.POIDS',BASE//' V K24',1         ,IBID)
C
      CALL JEDEMA()
      END
