      INTEGER FUNCTION INDK24(LK24,K24Z,RANG,NBK24)
      IMPLICIT NONE
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 26/01/2000   AUTEUR VABHHTS J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C INSPI INDIK8
C     ARGUMENTS:
C     ----------
      INTEGER NBK24,RANG
      CHARACTER*(*) K24Z, LK24(*)
      CHARACTER*24 K24,LK24Z
C ----------------------------------------------------------------------
C     ENTREES:
C     LK24 : LISTE DE K24 OU ON DOIT CHERCHER LE MOT K24
C     K24 : MOT A CHERCHER
C     NBK24: NOMBRE DE MOTS DE LK24
C     RANG : ON CHERCHE LE RANG-IEME MOT K24 DANS LA LISTE.
C
C     SORTIES:
C     INDK24 : POSITION DU MOT CHERCHE DANS LA LISTE.
C           SI LE MOT EST ABSENT: INDK24=0
C
C ----------------------------------------------------------------------
C
C     VARIABLES LOCALES:
C     ------------------
      INTEGER I,J
C DEB-------------------------------------------------------------------
C
      K24 = K24Z
      J = 0
      DO 100 I = 1,NBK24
         LK24Z = LK24(I)
         IF (LK24Z.EQ.K24) THEN
            J = J + 1
            IF (J.EQ.RANG) GO TO 110
         END IF
  100 CONTINUE
      INDK24 = 0
      GO TO 120
  110 CONTINUE
      INDK24 = I
  120 CONTINUE
      END
