      SUBROUTINE LOCALI(M,DIM,DIME,H,E0,MA,IMA,MINMAX,PAN,COORD,
     &                  CONNEX,LCCONN,NORMAL,TYPEMA,PREC,M0,IR)
C           CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 04/04/2002   AUTEUR VABHHTS J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2002  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C ----------------------------------------------------------------------
C    TESTE APPROXIMATIVEMENT SI LE POINT M APPARTIENT A LA MAILLE MA
C ----------------------------------------------------------------------
C VARIABLES D'ENTREE
C REAL*8       M(DIM)     : COORDONNEES DU POINT
C INTEGER      DIM        : DIMENSION DE L'ESPACE
C INTEGER      DIME(*)    : SD BOITE.DIME ASSOCIEE A MA (CF BOITE)
C REAL*8       H          : LONGUEUR CARACTERISTIQUE DE LA MAILLE IMA
C REAL*8       E0         : PRECISION SUR LE TEST
C INTEGER      MA         : INDEX DE LA MAILLE DANS H
C INTEGER      IMA        : INDEX DE LA MAILLE DANS LA SD MAILLAGE
C REAL*8       MINMAX(*)  : SD BOITE.MINMAX ASSOCIEE A MA (CF BOITE)
C REAL*8       PAN(*)     : SD BOITE.PAN ASSOCIEE A MA (CF BOITE)
C REAL*8       COORD(*)   : SI IMA = 0 : COORD. DES NOEUDS DE LA MAILLE
C                           SINON      : COORD. DES NOEUDS DU MAILLAGE
C INTEGER      CONNEX(*)  : SD CONNEXITE DU MAILLAGE  (UTILE SI IMA>0)
C INTEGER      LCCONN(*)  : LONGUEUR CUMULEE DE CONNEX (UTILE SI IMA>0)
C REAL*8       NORMAL(*)  : NORMALES LISSEES AUX NOEUDS (UTILE SI IMA>0)
C                           (CF LISNOR)
C CHARACTER*8  TYPEMA     : TYPE DE LA MAILLE
C LOGICAL      PREC       : PRECISION ELEVEE SUR M0
C
C VARIABLES DE SORTIE
C REAL*8       M0(*)      : COORD. DE M SUR LA MAILLE DE REFERENCE
C                           SI IR = .TRUE.
C LOGICAL      IR         : .TRUE. SI LES TESTS D'APPARTENANCE SONT
C                                     POSITIFS
C ----------------------------------------------------------------------
C          UTILISER DEDANS POUR ACHEVER LE TEST D'APPARTENANCE
C ----------------------------------------------------------------------

      IMPLICIT NONE

C --- VARIABLES
      CHARACTER*8 TYPEMA
      INTEGER     DIM,DIME(*),MA,IMA,CONNEX(*),LCCONN(*),P0,P1,I,J
      REAL*8      M(*),H,E0,MINMAX(2,DIM,*),PAN(DIM+2,*)
      REAL*8      COORD(*),NORMAL(*),M0(*),R,E,CNOEUD(81)
      LOGICAL     PREC,IR

      IR = .FALSE.
      E = H*E0

C --- 1. TEST MINMAX

      DO 10 I = 1, DIM
        R = M(I)
        IF ((R.LT.(MINMAX(1,I,MA)-E))
     &  .OR.(R.GT.(MINMAX(2,I,MA)+E))) GOTO 40
 10   CONTINUE

C --- 2. TEST PAN

      P0 = DIME(1+2*MA)
      P1 = DIME(3+2*MA)-1

      DO 20 I = P0, P1
        R = 0.D0
        DO 30 J = 1, DIM
          R = R + PAN(J,I)*M(J)
 30     CONTINUE
        IF ((R+PAN(J,I)).GT.E) GOTO 40
 20   CONTINUE

C --- 3. TEST COORDONNEES SUR LA MAILLE DE REFERENCE

      IF (IMA.NE.0) THEN
        CALL TMACOQ(TYPEMA,DIM,I)
        CALL CONOEU(IMA,CONNEX,LCCONN,COORD,NORMAL,DIM,I,CNOEUD,J)
        CALL REFERE(M,CNOEUD,DIM,TYPEMA,H,PREC,M0,IR,.FALSE.,R)
      ELSE
        CALL REFERE(M,COORD,DIM,TYPEMA,H,PREC,M0,IR,.FALSE.,R)
      ENDIF

 40   CONTINUE

      END
