      SUBROUTINE MECOAC(OPTIOZ,MODELE,LIGREL,MATE,PRESS,CHAMEL)
      IMPLICIT REAL*8 (A-H,O-Z)
      CHARACTER*(*) OPTIOZ,MODELE,LIGREL,MATE,PRESS,CHAMEL
C----------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 26/04/2011   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2011  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.

C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.

C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================

C     - FONCTION REALISEE:  CALCUL DES PRESSIONS EN DECIBELS
C                                  DES INTENSITES ACOUS. ACTIVE,REACTIVE

C     - ARGUMENTS:
C        DONNEES:      OPTIOZ       --> OPTION DE CALCUL
C                      MODELE       --> MODELE
C                      PRESS        --> CHAMNO(PRESS)
C                      MATE         --> CARTE DE MATERIAU CODE
C      RESULTATS:      CHAMEL       <-- CHAMELEM( ) DBEL_R PRES_C ...
C                                                   INTE_R
C----------------------------------------------------------------------

      CHARACTER*8 LPAIN(10),LPAOUT(1)
      CHARACTER*16 OPTION
      CHARACTER*24 LCHIN(10),LCHOUT(1),CHGEOM
      LOGICAL EXIGEO

C DEB-------------------------------------------------------------------

      OPTION = OPTIOZ
      CALL MEGEOM(MODELE,'        ',EXIGEO,CHGEOM)


      LCHOUT(1) = CHAMEL

      IF (OPTION.EQ.'PRAC_ELNO') THEN
        LPAOUT(1) = 'PPRAC_R'
        LPAIN(1) = 'PPRESSC'
        LCHIN(1) = PRESS
        CALL CALCUL('S',OPTION,LIGREL,1,LCHIN,LPAIN,1,LCHOUT,LPAOUT,'G',
     &                 'OUI')

      ELSE IF (OPTION.EQ.'INTE_ELNO') THEN
        LPAOUT(1) = 'PINTER'
        LPAIN(1) = 'PPRESSC'
        LCHIN(1) = PRESS
        LPAIN(2) = 'PGEOMER'
        LCHIN(2) = CHGEOM
        LPAIN(3) = 'PMATERC'
        LCHIN(3) = MATE
        CALL CALCUL('S',OPTION,LIGREL,3,LCHIN,LPAIN,1,LCHOUT,LPAOUT,'G',
     &                 'OUI')
      END IF

      END
