      SUBROUTINE MEPESA(LISCHA,CHPESA)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 13/06/2012   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
      IMPLICIT NONE
      INCLUDE 'jeveux.h'
      CHARACTER*19 LISCHA
      CHARACTER*19 CHPESA
C
C ----------------------------------------------------------------------
C
C RETOURNE LE CHAMP DE PESANTEUR DU CHARGEMENT
C
C ----------------------------------------------------------------------
C
C IN  LISCHA : SD LISTE DES CHARGES
C OUT CHPESA : CHAMP DE PESANTEUR
C
C
C
C
      CHARACTER*24 LISTIC,NOMOBJ
      INTEGER      JLIST,NBIDEN
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
C --- IDENTIFICATION DES CHARGEMENTS PESANTEUR
C
      LISTIC = '&&MEPESA.LISTIC'
      CALL LISIDT(LISCHA,'NEUM_MECA','PESANTEUR',LISTIC,NBIDEN)
      CHPESA = ' '
C
C --- UN SEUL CHARGEMENT PESANTEUR !
C
      IF (NBIDEN.GT.1) CALL ASSERT(.FALSE.)
      CALL JEVEUO(LISTIC,'L',JLIST)
C
C --- REPERAGE
C
      NOMOBJ = ZK24(JLIST-1+1)
      IF (NOMOBJ.NE.' ') THEN
        CHPESA = NOMOBJ(1:19)
      ENDIF
C
      CALL JEDETR(LISTIC)
      CALL JEDEMA()
C
      END
