      INTEGER FUNCTION MODAT2(IOPT,ITE,NOMPAR)
      IMPLICIT NONE

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 04/09/2012   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE PELLET J.PELLET
      INCLUDE 'jeveux.h'
      INTEGER IOPT,ITE
      CHARACTER*8 NOMPAR
C ----------------------------------------------------------------------
C BUT : TROUVER LE NUMERO DU MODE LOCAL ASSOCIE A UN PARAMETRE
C       D'UNE OPTION POUR UN TYPE_ELEM DONNE.

C ARGUMENTS :
C  IOPT    IN    I    : NUMERO DE L'OPTION DE CALCUL
C  ITE     IN    I    : NUMERO  DU TYPE_ELEM
C  NOMPAR  IN    K8   : NOM DU PARAMETRE POUR L'OPTION
C  MODAT2  OUT   I    : NUMERO DU MODE_LOCAL TROUVE DANS LE
C                       CATALOGUE DU TYPE_ELEM
C                       = 0 SI LE TYPE_ELEM NE CONNAIT PAS
C                       L'OPTION OU NE CONNAIT PAS LE PARAMETRE.
C ----------------------------------------------------------------------

C     VARIABLES LOCALES:
C     ------------------
      INTEGER IOPTE,IANBLC,JOPTTE,LGCO
      INTEGER NUCALC,NBPAR,K,JOPTMO,JOPTNO
C ----------------------------------------------------------------------

      MODAT2 = 0

      CALL JEVEUO('&CATA.TE.OPTTE','L',JOPTTE)
      CALL JEVEUO('&CATA.TE.NBLIGCOL','L',IANBLC)
      LGCO = ZI(IANBLC-1+1)
      IOPTE = ZI(JOPTTE-1+ (ITE-1)*LGCO+IOPT)


      IF (IOPTE.EQ.0) GO TO 20
      CALL JEVEUO(JEXNUM('&CATA.TE.OPTMOD',IOPTE),'L',JOPTMO)
      CALL JEVEUO(JEXNUM('&CATA.TE.OPTNOM',IOPTE),'L',JOPTNO)


      NUCALC = ZI(JOPTMO-1+1)
      IF (NUCALC.LE.0) GO TO 20

      NBPAR = ZI(JOPTMO-1+2) + ZI(JOPTMO-1+3)
      DO 10,K = 1,NBPAR
        IF (NOMPAR.NE.ZK8(JOPTNO-1+K)) GO TO 10
        MODAT2 = ZI(JOPTMO-1+3+K)
   10 CONTINUE


   20 CONTINUE
      END
