      CHARACTER*8 FUNCTION NOPARA(OPT,TE,STATUT,IPAR)
      IMPLICIT REAL*8 (A-H,O-Z)

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 30/01/2002   AUTEUR VABHHTS J.TESELET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C RESPONSABLE                            VABHHTS J.PELLET
C     ARGUMENTS:
C     ----------
      INTEGER OPT,TE,IPAR
      CHARACTER*3 STATUT
C ----------------------------------------------------------------------
C     ENTREES:
C     OPT    : OPTION
C     TE     : TYPE_ELEMENT
C     STATUT : IN/OUT
C     IPAR   : NUMERO DU CHAMP PARAMETRE DANS L'OPTION

C     SORTIES:
C     NOPARA : NOM DU PARAMETRE DANS L'OPTION

C ----------------------------------------------------------------------
      COMMON /CAII02/IAOPTT,LGCO,IAOPMO,ILOPMO,IAOPNO,ILOPNO,IAOPDS,
     +       IAOPPA,NPARIO,NPARIN,IAMLOC,ILMLOC,IADSGD


C     VARIABLES LOCALES:
C     ------------------
      INTEGER NBIN,OPTMOD,OPTNOM
C---------------- COMMUNS NORMALISES  JEVEUX  --------------------------
      COMMON /IVARJE/ZI(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
      INTEGER ZI

C DEB-------------------------------------------------------------------


C     JJ = IOPTTE(OPT,TE)
      JJ = ZI(IAOPTT-1+ (TE-1)*LGCO+OPT)
      OPTMOD = IAOPMO + ZI(ILOPMO-1+JJ) - 1
      OPTNOM = IAOPNO + ZI(ILOPNO-1+JJ) - 1
      IF (STATUT.EQ.'IN ') THEN
        NOPARA = ZK8(OPTNOM-1+IPAR)
      ELSE
        IF (STATUT.NE.'OUT') THEN
          CALL UTMESS('F','NOPARA','1')
        END IF
        NBIN = ZI(OPTMOD-1+2)
        NOPARA = ZK8(OPTNOM-1+NBIN+IPAR)
      END IF
   10 CONTINUE
      END
