      INTEGER FUNCTION NUCALC(OPT,TE,MEMOIR)
      IMPLICIT NONE

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CALCULEL  DATE 04/09/2007   AUTEUR DURAND C.DURAND 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE                            VABHHTS J.PELLET
C     ARGUMENTS:
C     ----------
      INTEGER OPT,TE,MEMOIR
C ----------------------------------------------------------------------
C     ENTREES:
C        OPT : OPTION
C         TE : TYPE_ELEMENT
C     MEMOIR : 1 : ON MET EN MEMOIRE LES OBJETS CATALOGUE NECESSAIRES
C              0 : ON NE FAIT PAS DE JEVEUX CAR LES OBJETS SONT DEJA LA
C                  (POUR ETRE PLUS RAPIDE DANS CALCUL).

C     SORTIES:
C     NUCALC : NUMERO DU CALCUL ELEMENTAIRE A LANCER

C ----------------------------------------------------------------------
      INTEGER IAOPTT,LGCO,IAOPMO,ILOPMO,IAOPNO,ILOPNO,IAOPDS
      INTEGER IAOPPA,NPARIO,NPARIN,IAMLOC,ILMLOC,IADSGD
      COMMON /CAII02/IAOPTT,LGCO,IAOPMO,ILOPMO,IAOPNO,ILOPNO,IAOPDS,
     +       IAOPPA,NPARIO,NPARIN,IAMLOC,ILMLOC,IADSGD

C     VARIABLES LOCALES:
C     ------------------
      INTEGER OPTMOD,JJ,IANBLC
C---------------- COMMUNS NORMALISES  JEVEUX  --------------------------
      COMMON /IVARJE/ZI(1)
      INTEGER ZI
      CHARACTER*32 JEXATR

C DEB-------------------------------------------------------------------
      CALL ASSERT(MEMOIR.EQ.0 .OR. MEMOIR.EQ.1)
      IF (MEMOIR.EQ.1) THEN
        CALL JEVEUO('&CATA.TE.OPTTE','L',IAOPTT)
        CALL JEVEUO('&CATA.TE.OPTMOD','L',IAOPMO)
        CALL JEVEUO(JEXATR('&CATA.TE.OPTMOD','LONCUM'),'L',ILOPMO)
        CALL JEVEUO('&CATA.TE.NBLIGCOL','L',IANBLC)
        LGCO = ZI(IANBLC-1+1)
      ENDIF

C     JJ = IOPTTE(OPT,TE)
      JJ = ZI(IAOPTT-1+ (TE-1)*LGCO+OPT)
      IF (JJ.EQ.0) THEN
C        -- LE TYPE_ELEMENT TE NE SAURA JAMAIS CALCULER L'OPTION OPT:
        NUCALC = 0
      ELSE
        OPTMOD = IAOPMO + ZI(ILOPMO-1+JJ) - 1
        NUCALC = ZI(OPTMOD-1+1)
      END IF
   10 CONTINUE
      END
