# coding=utf-8

import os
import shutil
from pprint import pformat

def build(self):
    get_srcs = self.path.get_src().ant_glob
    env = self.all_envs[self.variant]
    if self.cmd.startswith('install'):
        try:
            shutil.rmtree(env.PYTHONDIR)
        except OSError:
            pass

    self(
        features = 'py',
            name = 'bibpyt',
          source = get_srcs('**/*.py'),
    install_from = '.',
    install_path = os.path.join(env.LIBDIR, 'aster'),
    )

    self(
        features = 'subst py',
            name = 'aster_pkginfo',
          source = 'aster_pkginfo.pytmpl',
          target = 'aster_pkginfo.py',
    install_path = os.path.join(env.LIBDIR, 'aster'),
             use = ['bibpyt'],
    VERSION_INFO = pformat(env['ASTER_VERSION']),
    )
