# encoding: utf-8

import os.path as osp

from waflib import TaskGen, Utils

def build(self):
    get_srcs = self.path.get_src().ant_glob
    env = self.all_envs[self.variant]
    
    self(
        features = 'py',
            name = 'bibpyt',
          source = get_srcs('**/*.py'),
    install_from = '.',
    install_path = env.PYTHONDIR,
    )

    self(
       features = 'revid py',
           name = 'revision_id',
         target = 'revision_id.py',
   install_path = osp.join(env.PYTHONDIR, 'Accas'),
    )

@TaskGen.feature('revid')
def build_revid(self):
    """Create 'revision_id.py' containing the parent revision."""
    target = self.bld.bldnode.make_node(self.target)
    txt = "#\nrevid = %s\n" % self.env.ASTER_VERSION
    with open(target.abspath(), 'w') as fid:
        fid.write(txt)
    target.sig = Utils.h_file(target.abspath())
    self.process_py(target)

