!
! COPYRIGHT (C) 1991 - 2015  EDF R&D  WWW.CODE-ASTER.ORG
!
! THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
! IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
! THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
! (AT YOUR OPTION) ANY LATER VERSION.
!
! THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
! WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
! MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
! GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
! YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
! ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
! 1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
!
! -------------------------------------------------------------------------
! sd_int data structure : Parameters <-> integer definitions
! -------------------------------------------------------------------------
!
#define _INT_NBPAR 24

#define DEPL  1
#define VITE  2
#define ACCE  3
#define TIME  4
#define STEP  5
#define INDEX 6
#define FORCE_EX 7
#define MASS_DIA 8
#define MASS_FUL 9
#define IND_ARCH 10
#define RIGI_DIA 11
#define AMOR_DIA 12
#define RIGI_FUL 13
#define AMOR_FUL 14
#define MASS_FAC 15
#define MAT_UPDT 16
#define PARAMS 17
#define WORK1 18
#define WORK2 19
#define WORK3 20
#define WORK4 21
#define WORK5 22
#define WORK6 23
#define WORK7 24