      SUBROUTINE APETSC(ACTION,SOLVEZ,MATASZ,VECASZ,SOLUZ,VCINEZ)
      IMPLICIT NONE
C AJOUT FERMETUR
C--------------------------------------------------------------
C BUT : ROUTINE D'INTERFACE ENTRE LE CODE_ASTER ET LA BIBLIOTHEQUE
C       PETSC DE RESOLUTION DE SYSTEMES LINEAIRES.

C IN : ACTION :
C     /'PRERES'  : POUR DEMANDER LA FACTORISATION
C     /'RESOUD'  : POUR DEMANDER LA DESCENTE/REMONTEE
C     /'DETR_MAT': POUR DEMANDER LA DESTRUCTION DE L'INSTANCE MUMPS
C                  ASSOCIEE A UNE MATRICE
C     /'FIN'     : DESTRUCTION DE TOUTES LES INSTANCES MUMPS
C                  + MPI_FINALIZE  (A FAIRE DANS LA COMMANDE FIN ??)

C IN : SOLVEZ   (K19) : NOM DE LA SD SOLVEUR
C             (SI ACTION=PRERES/RESOUD)
C IN : MATASZ(K19) : NOM DE LA MATR_ASSE
C             (SI ACTION=PRERES/RESOUD/DETR_MATR)
C IN : VECASZ (K19) : NOM DU SECOND MEMBRE
C            (SI ACTION=RESOUD)
C IN : SOLUZ  (K19) : NOM DE LA SOLUTION
C            (SI ACTION=RESOUD)
C IN : VCINEZ (K19) : NOM DU CHAM_NO DE CHARGEMENT CINEMATIQUE
C            (SI ACTION=RESOUD)
C--------------------------------------------------------------
      CHARACTER*(*) ACTION,SOLVEZ,MATASZ,VECASZ,SOLUZ,VCINEZ

      CALL U2MESS('F','FERMETUR_10')

      END
