
      SUBROUTINE EFEQUL(FID,MAA,EQ,CORR,N,TYPENT,TYPGEO,CRET)
      IMPLICIT NONE
      CHARACTER *(*) MAA, EQ
      INTEGER FID, CRET, CORR(*), N,TYPENT, TYPGEO
      INTEGER EDFEQUL
      CALL U2MESS('F','FERMETUR_2')
      END
