      SUBROUTINE NUMDDL(NU,BASE,NBMAT,TLIMAT,METHOD)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ASSEMBLA  DATE 03/11/2008   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C
      CHARACTER*2     BASE
      CHARACTER*(*)   NU,TLIMAT(*) ,METHOD
      INTEGER                   NBMAT
C ----------------------------------------------------------------------
C --- DESCRIPTION DES PARAMETRES
C OUT K*14 NU     : LE CHAMP .NUME DE S.D. NUME_DDL_EQUA DE L'OBJET NU
C                   DE S.D. NUME_DDL EST CREE ET REMPLI.
C IN  K*14 NU     : NOM D'UN NUMERO_DDL(SI UN OBJET DE NOM NU ET
C                   DE S.D. NUME_DDL EXISTE ON L'ECRASE)
C IN  K2   BASE    : BASE(1:1) : BASE POUR CREER LE NUME_DDL
C                    (SAUF LE PROF_CHNO)
C                  : BASE(2:2) : BASE POUR CREER LE PROF_CHNO
C IN  I    NBMAT  : NOMBRE DE MATELE PASSES DANS TLIMAT
C IN  K19  TLIMAT : LISTE DES MATELE DEFINISSANT LA NUMEROTATION
C IN  K*4  METHOD : METHODE DE RENUMEROTATION DES NOEUDS:
C                   'SANS' --> ON NE RENUMEROTE PAS
C                   'RCMK' --> 'REVERSE CUTHIL MAC-KEE'
C                   SINON LA NUMEROTATION EST BASEE SUR CETTE GRANDEUR
C----------------------------------------------------------------------

      CHARACTER*14 NUPGM
      INTEGER IBID
      CHARACTER*19 K19BID
      CHARACTER*24 TLIMA2(NBMAT)
C
C------RECUPERATION DU NIVEAU D'IMPRESSION
      CALL INFNIV(IFM,NIV)

      NUPGM = NU
      K19BID = ' '
C
      DO 10 I=1,NBMAT
        TLIMA2(I)=TLIMAT(I)
 10   CONTINUE
C---- CREATION D'UNE LISTE DE LIGRELS A PARTIR DE LA LISTE DE MATR_ELEM
C
      CALL NUMOCH(TLIMA2,NBMAT,'V',NUPGM//'.&LMODCHAR')
      CALL NUEFFE(NUPGM//'.&LMODCHAR',BASE,NUPGM,METHOD,' ',
     &  K19BID,IBID)
      CALL JEDETC(' ',NUPGM//'.&LMODCHAR',1)
C
      END
