      SUBROUTINE OP0013()
      IMPLICIT REAL*8 (A-H,O-Z)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ASSEMBLA  DATE 30/06/2010   AUTEUR DELMAS J.DELMAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C
C
      CHARACTER*8 NU,VECAS,MAILLA,K8,VPROF
      CHARACTER*16 TYPV,OPER
      INTEGER TYPE
C
C     FONCTIONS JEVEUX
C
      CHARACTER*32 JEXNUM,JEXNOM,JEXATR
C
C     COMMUNS   JEVEUX
C
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C
      CHARACTER*19 CH19
      CALL JEMARQ()

      CALL INFMAJ
      CALL INFNIV(IFM,NIV)
      CALL GETRES(VECAS,TYPV,OPER)
C
      CALL GETVID(' ','VECT_ELEM',0,1,0,K8,NBVEC)
      NBVEC = -NBVEC
C
C
      CALL JECREO(VECAS//'.LI2VECEL','V V K8 ')
      CALL JEECRA(VECAS//'.LI2VECEL','LONMAX',NBVEC,' ')
      CALL JEVEUO(VECAS//'.LI2VECEL','E',ILIVEC)
      CALL GETVID(' ','VECT_ELEM',0,1,NBVEC,ZK8(ILIVEC),NBVEC)
      CALL GETTCO(ZK8(ILIVEC),TYPV)
      IF (TYPV(16:16).EQ.'R') TYPE=1
      IF (TYPV(16:16).EQ.'C') TYPE=2

C
      CALL JECREO(VECAS//'.LICOEF','V V R ')
      CALL JEECRA(VECAS//'.LICOEF','LONMAX',NBVEC,' ')
      CALL JEVEUO(VECAS//'.LICOEF','E',ILICOE)
      DO 5 I = 1,NBVEC
         ZR(ILICOE-1+I) = 1.0D0
    5 CONTINUE
C
      CALL GETVID(' ','NUME_DDL',0,1,1,NU,IBID)
      VPROF = '        '
      CALL ASSVEC('G',VECAS,NBVEC,ZK8(ILIVEC),ZR(ILICOE),NU,VPROF,
     +            'ZERO',TYPE)
      CH19 = VECAS
      CALL JEDETR(CH19//'.LILI')
      CALL JEDETR(CH19//'.ADNE')
      CALL JEDETR(CH19//'.ADLI')
C
      CALL JEDEMA()
      END
