      SUBROUTINE PRNIV1(T,NBCP,NBCO,NBSP,SNORIG,SNEXTR,SNFLEX)
      IMPLICIT  NONE
      INTEGER NBCP,NBCO,NBSP
      REAL*8 T(*),SNORIG(*),SNEXTR(*),SNFLEX(*)
C     ------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF POSTRELE  DATE 08/03/2004   AUTEUR REZETTE C.REZETTE 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C     ------------------------------------------------------------------
      INTEGER L,M,ISP,I10,I30,ICP

      IF (NBCO.GT.1) THEN
        CALL UTMESS('F','PRNIV1','ON NE TRAITE PAS LES MULTICOUCHES')
      END IF

      L = 6*NBSP
      M = L*NBCO

      ISP = 1
      I10 = 6* (ISP-1)
      DO 10 ICP = 1,NBCP
        I30 = M* (ICP-1)
C        --- COMPOSANTE MOMENT_0 ---
C                    = T(I30+I10+1)
C        --- COMPOSANTE MOYE_INT ---
        SNORIG(ICP) = T(I30+I10+5)
   10 CONTINUE

      ISP = NBSP
      I10 = 6* (ISP-1)
      DO 20 ICP = 1,NBCP
        I30 = M* (ICP-1)
C        --- COMPOSANTE MOMENT_1 ---
        SNFLEX(ICP) = 0.5D0*T(I30+I10+2)
C        --- COMPOSANTE MOYE_EXT ---
        SNEXTR(ICP) = T(I30+I10+6)
   20 CONTINUE


      END
