      SUBROUTINE IRCAEL(JCESDI,JCESLI,JCESVI,JCESCI,NUMMAI,
     &                  NBRCOU,NBRSEC,NBRFIB,NBRGRF,NUGRFI)
      IMPLICIT NONE
      INTEGER NMAXFI
      PARAMETER (NMAXFI=10)
      INTEGER JCESDI,JCESLI,NUMMAI,NBRCOU,JCESVI
      INTEGER NBRSEC,NBRFIB,NBRGRF,NUGRFI(NMAXFI),JCESCI
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF PREPOST  DATE 16/10/2012   AUTEUR SELLENET N.SELLENET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE SELLENET N.SELLENET
C ----------------------------------------------------------------------
C  IMPR_RESU - CARACTERISTIQUE DE L'ELEMENT
C  -    -      --                   --
C ----------------------------------------------------------------------
C
C  CETTE ROUTINE EST UTILE POUR TROUVER LE NOMBRE DE COUCHES, ...
C    PRESENTES SUR UNE MAILLE
C
C IN  :
C   JCESDI  I    ADRESSE JEVEUX DU CESD
C   JCESLI  I    ADRESSE JEVEUX DU CESL
C   JCESVI  I    ADRESSE JEVEUX DU CESV
C   JCESCI  I    ADRESSE JEVEUX DU CESC
C   NUMMAI  I    NUMERO DE MAILLE
C
C OUT :
C   NBRCOU  I    NOMBRE DE COUCHES
C   NBRSEC  I    NOMBRE DE SECTEURS
C   NBRFIB  I    NOMBRE DE FIBRES
C   NBRGRF  I    NOMBRE DE GROUPES DE FIBRES
C   NUGRFI  I    NUMERO DU GROUPE DE FIBRES
C
      INCLUDE 'jeveux.h'
C
      INTEGER NBRCMP,NUMGRF,ICMP,IAD,IGFIB
C
      DO 20, IGFIB = 1,NMAXFI
        NUGRFI(IGFIB)=0
 20   CONTINUE
C
      NBRCMP = ZI(JCESDI-1+5+4* (NUMMAI-1)+3)
      NUMGRF = 1
      DO 10, ICMP = 1, NBRCMP
        CALL CESEXI('C',JCESDI,JCESLI,NUMMAI,1,1,ICMP,IAD)
C
        IF ( IAD.GT.0 ) THEN
          IF ( ZK8(JCESCI+ICMP-1).EQ.'COQ_NCOU' ) THEN
            NBRCOU=ZI(JCESVI-1+IAD)
          ELSEIF ( ZK8(JCESCI+ICMP-1).EQ.'TUY_NCOU' ) THEN
            NBRCOU=ZI(JCESVI-1+IAD)
          ELSEIF ( ZK8(JCESCI+ICMP-1).EQ.'TUY_NSEC' ) THEN
            NBRSEC=ZI(JCESVI-1+IAD)
          ELSEIF ( ZK8(JCESCI+ICMP-1).EQ.'NBFIBR' ) THEN
            NBRFIB=ZI(JCESVI-1+IAD)
          ELSEIF ( ZK8(JCESCI+ICMP-1).EQ.'NBGRFI' ) THEN
            NBRGRF=ZI(JCESVI-1+IAD)
          ELSEIF ( ZK8(JCESCI+ICMP-1)(1:3).EQ.'NUG' ) THEN
            NUGRFI(NUMGRF)=ZI(JCESVI-1+IAD)
            NUMGRF=NUMGRF+1
          ENDIF
        ENDIF
 10   CONTINUE
      IF ( NBRFIB.NE.0 ) CALL ASSERT(NBRGRF.NE.0)
C
      END
