      SUBROUTINE W039C2(NUZONE,JVALE,JDESC,NOMGD,IFM,IFR)
      IMPLICIT   NONE
      INTEGER NUZONE,JVALE,JDESC,IFM,IFR
      CHARACTER*8 NOMGD
C ----------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF PREPOST  DATE 07/02/2012   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE PELLET J.PELLET
C ----------------------------------------------------------------------
C     BUT: IMPRIMER LA"LEGENDE" POUR W039C1
C ----------------------------------------------------------------------
C
C --------- DEBUT DECLARATIONS NORMALISEES  JEVEUX ---------------------
C
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32,JEXNOM
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
      CHARACTER*32 JEXNUM
C
C --------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ---------------------
C
      INTEGER I,NEC,NCMPMX,KCMP,IBID,JCMP,NZONMX,DEC1,ICO,DEBGD
      CHARACTER*8 KBID,TSCA,NOCMP
      LOGICAL EXISDG
C ----------------------------------------------------------------------
C
      CALL JEMARQ()

      CALL DISMOI('F','NB_EC',NOMGD,'GRANDEUR',NEC,KBID,IBID)
      CALL DISMOI('F','TYPE_SCA',NOMGD,'GRANDEUR',IBID,TSCA,IBID)
      CALL JELIRA(JEXNOM('&CATA.GD.NOMCMP',NOMGD),'LONMAX',NCMPMX,KBID)
      CALL JEVEUO(JEXNOM('&CATA.GD.NOMCMP',NOMGD),'L',JCMP)
      CALL ASSERT(NUZONE.GT.0)
      NZONMX=ZI(JDESC-1+2)

      WRITE (IFM,1005)'VALEUR =',DBLE(NUZONE)
      WRITE (IFR,1005)'VALEUR =',DBLE(NUZONE)
      DEBGD=3+2*NZONMX+(NUZONE-1)*NEC+1
      ICO=0
      DO 10,KCMP=1,NCMPMX
        IF (EXISDG(ZI(JDESC-1+DEBGD),KCMP)) THEN
          ICO=ICO+1
          NOCMP=ZK8(JCMP-1+KCMP)
          DEC1=NCMPMX*(NUZONE-1)+ICO
          IF (TSCA.EQ.'K8') THEN
            WRITE (IFM,1004)NOCMP,'=',ZK8(JVALE-1+DEC1)
            WRITE (IFR,1004)NOCMP,'=',ZK8(JVALE-1+DEC1)
          ELSEIF (TSCA.EQ.'K16') THEN
            WRITE (IFM,1004)NOCMP,'=',ZK16(JVALE-1+DEC1)
            WRITE (IFR,1004)NOCMP,'=',ZK16(JVALE-1+DEC1)
          ELSEIF (TSCA.EQ.'K24') THEN
            WRITE (IFM,1004)NOCMP,'=',ZK24(JVALE-1+DEC1)
            WRITE (IFR,1004)NOCMP,'=',ZK24(JVALE-1+DEC1)
          ELSEIF (TSCA.EQ.'I') THEN
            WRITE (IFM,1003)NOCMP,'=',ZI(JVALE-1+DEC1)
            WRITE (IFR,1003)NOCMP,'=',ZI(JVALE-1+DEC1)
          ELSEIF (TSCA.EQ.'R') THEN
            WRITE (IFM,1001)NOCMP,'=',ZR(JVALE-1+DEC1)
            WRITE (IFR,1001)NOCMP,'=',ZR(JVALE-1+DEC1)
          ELSEIF (TSCA.EQ.'C') THEN
            WRITE (IFM,1002)NOCMP,'=',DBLE(ZC(JVALE-1+DEC1)),
     &                                DIMAG(ZC(JVALE-1+DEC1))
            WRITE (IFR,1002)NOCMP,'=',DBLE(ZC(JVALE-1+DEC1)),
     &                                DIMAG(ZC(JVALE-1+DEC1))
          ELSE
            CALL ASSERT(.FALSE.)
          ENDIF
        ENDIF
   10 CONTINUE

1001  FORMAT (4X,A8,1X,A1,1X,1PD11.3)
1002  FORMAT (4X,A8,1X,A1,1X,2(1PD11.3))
1003  FORMAT (4X,A8,1X,A1,1X,I8)
1004  FORMAT (4X,A8,1X,A1,1X,A)
1005  FORMAT (A,1X,1F11.0)
      CALL JEDEMA()
      END
