      SUBROUTINE WCLASS(
     + ICLASS,IVAL,CVAL,TYPE,MOT,FIN,FINA,IRTETI)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF CATAELEM  DATE 12/05/97   AUTEUR JMBHH01 J.M.PROIX 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
      IMPLICIT REAL*8 (A-H,O-Z)
C
C     INCLUDE($CIMPERR)
C
      COMMON /CIMP/ IMP,IULMES,IULIST,IULVIG
C
C     EXCLUDE($CIMPERR)
C
C
C     ICLASS,IVAL,CVAL ---> CE QUI A ETET LU
C
C     TYPE : SI 1 ON ATTEND UN ENTIER
C            SI 3 ON ATTEND UN MOT QUELCONQUE
C            SI 4 ON ATTEND MOT
C
C     SI OK FIN <-- FINA SINON RETURN 1
C
C
      INTEGER FIN,FINA,TYPE
      CHARACTER*(*) CVAL,MOT
      INTEGER ERREUR,OK
C
      ASSIGN 100 TO ERREUR
      ASSIGN 200 TO OK
      IRTETI = 0
C
       IF (TYPE.EQ.1) THEN
C
        IF (ICLASS.EQ.1) THEN
         GOTO OK
        ELSE
         WRITE(IULMES,*) ' WCLASS  ENTIER ATTENDU   '
         GOTO ERREUR
        ENDIF
C
       ELSE IF (TYPE.EQ.3) THEN
C
        IF (ICLASS.EQ.3) THEN
         GOTO OK
        ELSE
         WRITE(IULMES,*) ' WCLASS MOT QUELCONQUE ATTENDU '
         GOTO ERREUR
        ENDIF
C
       ELSE IF (TYPE.EQ.4) THEN
        IF (ICLASS.EQ.3) THEN
         IF (CVAL(1:IVAL).EQ.MOT) THEN
          GOTO OK
         ELSE
          WRITE(IULMES,*) ' WCLASS MOT INCORRECT '
          WRITE(IULMES,*) ' MOT ATTENDU   ',MOT
          WRITE(IULMES,*) ' MOT RENCONTRE ',CVAL(1:IVAL)
          GOTO ERREUR
         ENDIF
        ELSE
         WRITE(IULMES,*) ' WCLASS ON LIT AUTRE CHOSE Q UN MOT '
         WRITE(IULMES,*) ' MOT ATTENDU   ',MOT
         GOTO ERREUR
        ENDIF
       ELSE
        WRITE(IULMES,1000) TYPE
 1000   FORMAT(' WCLASS TYPE ',I5,' INCONNU  RETOUR SUPERVISEUR ')
        CALL UTMESS('F','WCLASS','PB. LECTURE CATALOGUES.')
        GOTO ERREUR
       ENDIF
C
  100 CONTINUE
      CALL UTMESS('F','WCLASS','PB. LECTURE CATALOGUES.')
      IRTETI = 1
      GOTO 9999
  200 CONTINUE
      FIN = FINA
      IRTETI = 0
 9999 CONTINUE
      END
