# coding=utf-8

"""
Internationalization of Code_Aster messages
-------------------------------------------

Content of src/i18n
~~~~~~~~~~~~~~~~~~~

* ``$LANG/aster_messages.po``: current state of translated messages for each language

* These files are created by ``msginit`` from the ``.pot`` file::

    msginit -i build/release/i18n/aster_messages.pot --locale=$LANG --no-translator

  or by adding a new language on crowdin and download a fresh package.


Configure step
~~~~~~~~~~~~~~

* search the tool to extract the messages from the source files (xgettext),
  to merge ``.po`` and new ``.pot`` files (msgmerge), and to compile
  a ``.po`` file into a ``.mo`` file (msgfmt).

* if ``--install-i18n`` option is set, the configuration fails if the tool
  required at installation is missing.


Build steps
~~~~~~~~~~~

* ``waf build`` compiles the ``.po`` files from ``src/i18n/``.

* ``waf install`` installs the ``.mo`` files into ``share/locale/aster/...``.

* workflow with the crowdin project (https://crowdin.net/project/code-aster)

  - download already translated strings from crowdin (ex. ``/tmp/code-aster.zip``)

  - extract the ``aster_messages*`` files::

      cd i18n ; unzip -u /tmp/code-aster.zip '*/aster_messages*' -x 'fr*'

  - extract all the strings from the source files and update the ``.po`` files::

      waf i18n

  - update the 'src' tree by running::

      cp -r build/release/i18n_updated/* i18n/

  - pushed to crowdin the ``aster_messages.po`` files

"""

import os
import os.path as osp
from waflib import Configure, TaskGen, Task, Errors, Logs

def options(self):
    group = self.get_option_group('Code_Aster options')
    group.add_option('--install-i18n', dest='install_i18n',
                    action='store_true', default=None,
                    help='install the i18n files')

def configure(self):
    self.check_gettext_tools_inst()
    self.check_gettext_tools_dvp()

def build(self):
    self(
        features = 'i18n_compile',
    install_path = self.env.ASTERLOCALEDIR,
    )

def update_i18n(self):
    get_srcs = self.path.get_src().parent.ant_glob
    pysrc = get_srcs('bibpyt/**/*.py')
    pot = self.path.get_bld().make_node('aster_messages.pot')
    self(
        features = 'i18n_pot',
            name = 'i18n_pot',
            deps = pysrc,
          target = pot,
    )
    self(
        features = 'i18n_update',
            name = 'i18n_update',
             pot = pot,
           podir = 'i18n_updated',
             use = ['i18n_pot'],
    )

###############################################################################
@Configure.conf
def check_gettext_tools_inst(self):
    """Detect the programs to compile the `.po` files to binary format"""
    self.start_msg('Check for i18n programs')
    try:
        self.find_program('msgfmt', var='MSGFMT')
    except Errors.ConfigurationError:
        self.end_msg('not found', 'YELLOW')
        if self.options.install_i18n is True:
            raise
    else:
        self.env.enable_i18n = 1
        self.end_msg(self.env.MSGFMT)

@Configure.conf
def check_gettext_tools_dvp(self):
    """Detect the programs to update the `.po` files"""
    self.start_msg('Check for i18n programs (devel)')
    try:
        self.find_program('xgettext', var='XGETTEXT')
        self.find_program('msgmerge', var='MSGMERGE')
    except Errors.ConfigurationError:
        self.end_msg('not found', 'YELLOW')
    else:
        self.env.update_i18n = 1
        tools = ', '.join([self.env[i] for i in ('XGETTEXT', 'MSGMERGE')])
        self.end_msg(tools)

class CaptureTask(Task.Task):
    """Capture stderr/stdout and logs them only in case of failure"""

    def exec_command(self, cmd, **kw):
        try:
            self.generator.bld.cmd_and_log(cmd, quiet=0, **kw)
        except Errors.WafError, err:
            if hasattr(err, 'stdout'):
                Logs.warn('stdout: %s' % err.stdout)
                Logs.warn('stderr: %s' % err.stderr)
            raise

class xgettext(CaptureTask):
    """Build the .pot file from a list of source files"""
    run_str = '${XGETTEXT} -o ${TGT[0].abspath()} --package-name=Code_Aster --package-version=default ${I18NFILES}'
    color   = 'BLUE'

class merge_po(CaptureTask):
    """Merge a .po file and a new .pot file"""
    run_str = '${MSGMERGE} -q -o ${TGT[0].abspath()} ${SRC[0].abspath()} ${SRC[1].abspath()}'
    color   = 'BLUE'

class compile_po(CaptureTask):
    """Compile .po files into .mo files"""
    run_str = '${MSGFMT} -o ${TGT[0].abspath()} ${SRC[0].abspath()}'
    color   = 'BLUE'


@TaskGen.feature('i18n_compile')
def run_i18n(self):
    """compile .po files into .mo and install them.

	:param install_path: installation directory
	:type install_path: string
    """
    if not self.env.enable_i18n:
        return
    inst = getattr(self, 'install_path')
    for subd in self.path.listdir():
        node = self.path.find_resource(osp.join(subd, 'aster_messages.po'))
        if node:
            task = self.create_task('compile_po', node.get_src(), node.change_ext('.mo'))
            if inst:
                lang = task.outputs[0].srcpath().split(os.sep)[-2]
                path = osp.join(inst, lang, 'LC_MESSAGES')
                self.bld.install_files(path, task.outputs[0])

@TaskGen.feature('i18n_pot')
def make_pot(self):
    """Create task to build the pot file
    
    :param deps: list of the python files to run xgettext on
    :type deps: nodes
    :param target: name of the ``.pot`` file
    :type target: string
    """
    target = self.target
    deps = getattr(self, 'deps', [])
    self.env.I18NFILES = []
    for node in deps:
        self.env.append_value('I18NFILES', node.abspath())
    target.parent.mkdir()
    self.create_task('xgettext', deps, target)

@TaskGen.feature('i18n_update')
@TaskGen.after('i18n_pot')
def update_po(self):
    """Create task to update the po files
    
    :param pot: updated .pot file
    :type pot: string
    """
    pot = self.pot
    podir = self.path.parent.get_bld().make_node(self.podir)
    for subd in self.path.listdir():
        node = self.path.find_resource(osp.join(subd, 'aster_messages.po'))
        if node:
            tail = node.get_src().abspath().split(os.sep)[-2:]
            output = podir.make_node(tail)
            output.parent.mkdir()
            task = self.create_task('merge_po', [node.get_src(), pot], output)
