      SUBROUTINE ADINMA ( NOMAST, NRADAP, CODRET )
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF UTILITAI  DATE 10/10/2001   AUTEUR GNICOLAS G.NICOLAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C     ------------------------------------------------------------------
C      ADAPTATION - INFORMATION SUR LE MAILLAGE
C      --           --                 --
C     ENTREES:
C        NOMAST : NOM ASTER DU MAILLAGE
C    SORTIES:
C        NRADAP : NUMERO D'ADAPTATION (0 POUR UN MAILLAGE DE DEPART)
C        CODRET : 0, SI LE NUMERO A ETE TROUVE
C                 1, PAS DE NUMERO CODE
C     ------------------------------------------------------------------
C
      IMPLICIT NONE
C
C 0.1. ==> ARGUMENTS
C
      INTEGER NRADAP, CODRET
C
      CHARACTER*(*) NOMAST
C
C 0.2. ==> COMMUNS
C
C --- DEBUT DECLARATIONS NORMALISEES JEVEUX ----------------------------
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C --- FIN DECLARATIONS NORMALISEES JEVEUX ------------------------------
C
C 0.3. ==> VARIABLES LOCALES
C
CGN      CHARACTER*6 NOMPRO
CGN      PARAMETER ( NOMPRO = 'ADINMA' )
C
      INTEGER LXLGUT
C
      INTEGER IAUX
C
      CHARACTER*8  MAIL08
      CHARACTER*24 ADAPMA
C
C====
C 1. RECUPERATION DES INFORMATIONS
C====
C
C               12345678
      MAIL08 = '        '
      IAUX = LXLGUT(NOMAST)
      MAIL08(1:IAUX)  = NOMAST(1:IAUX)
      ADAPMA = MAIL08//'.ADAPTATION'
C
      CALL JEEXIN ( ADAPMA, IAUX )
C
      IF ( IAUX.EQ.0 ) THEN
C
CGN        CALL UTMESS ( 'A', NOMPRO,
CGN     >  'MAILLAGE '//MAIL08//' : AUCUNE INFORMATION D ADAPTATION')
        CODRET = 1
C
      ELSE
C
        CALL JEVEUO ( ADAPMA, 'L', IAUX )
        NRADAP = ZI(IAUX)
        CODRET = 0
C
      ENDIF
C
      END
