      SUBROUTINE JECCTA(COLLE1)
      IMPLICIT NONE
      INCLUDE 'jeveux.h'

      CHARACTER*32 JEXNUM,JEXATR
      CHARACTER*(*) COLLE1
C     ------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF UTILITAI  DATE 09/11/2012   AUTEUR DELMAS J.DELMAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE PELLET J.PELLET
C ======================================================================
C     RETASSAGE D'UNE COLLECTION CONTIGUE ALLOUEE TROP GRANDE
C     ------------------------------------------------------------------
C IN  COLLE1  : K24 : NOM DE LA COLLECTION CONTIGUE A RETASSER
C     ------------------------------------------------------------------
C
      CHARACTER*8 BASE,TYPE,KBID,ACCES,STOCK,MODELO
      CHARACTER*24 COLLE2
      INTEGER K,NBOBJ,LONT1,LONT2,JLONCU,IBID
      INTEGER N1,JCOLL1,JCOLL2
C-----------------------------------------------------------------------
      CALL JEMARQ()


C     -- CALCUL DE :
C        BASE, TYPE, NBOBJ,
C        ACCES, STOCK, MODELO, LONT1 ET LONT2 :
C     -------------------------------------------------------
      CALL JELIRA(COLLE1,'CLAS',IBID,BASE)
      CALL JELIRA(COLLE1,'TYPE',IBID,TYPE)
      CALL JELIRA(COLLE1,'NMAXOC',NBOBJ,KBID)
      CALL JELIRA(COLLE1,'ACCES',IBID,ACCES)
      CALL JELIRA(COLLE1,'MODELONG',IBID,MODELO)
      CALL JELIRA(COLLE1,'STOCKAGE',IBID,STOCK)
      CALL JELIRA(COLLE1,'LONT',LONT1,KBID)
      CALL ASSERT(TYPE.NE.'K')
      CALL ASSERT(STOCK.EQ.'CONTIG')
      CALL ASSERT(MODELO.EQ.'VARIABLE')
      CALL ASSERT(ACCES.EQ.'NU')

      CALL JEVEUO(JEXATR(COLLE1,'LONCUM'),'L',JLONCU)
      LONT2=ZI(JLONCU-1+NBOBJ+1)


C     -- ALLOCATION ET REMPLISAGE DE COLLE2 :
C     ------------------------------------------------
      COLLE2='&&JECCTA.COLLEC2'
      CALL JECREC(COLLE2,'V V '//TYPE,ACCES,STOCK,MODELO,NBOBJ)
      CALL JEECRA(COLLE2,'LONT',LONT2,KBID)
      CALL JEVEUO(COLLE1,'L',JCOLL1)
      CALL JEVEUO(COLLE2,'E',JCOLL2)
      IF (TYPE.EQ.'I') THEN
        DO 10,K=1,LONT2
          ZI(JCOLL2-1+K)=ZI(JCOLL1-1+K)
   10   CONTINUE
      ELSEIF (TYPE.EQ.'R') THEN
        DO 20,K=1,LONT2
          ZR(JCOLL2-1+K)=ZR(JCOLL1-1+K)
   20   CONTINUE
      ELSEIF (TYPE.EQ.'C') THEN
        DO 30,K=1,LONT2
          ZC(JCOLL2-1+K)=ZC(JCOLL1-1+K)
   30   CONTINUE
      ELSE
        CALL ASSERT(.FALSE.)
      ENDIF

      DO 40,K=1,NBOBJ
        N1=ZI(JLONCU-1+K+1)-ZI(JLONCU-1+K)
        CALL JECROC(JEXNUM(COLLE2,K))
        CALL JEECRA(JEXNUM(COLLE2,K),'LONMAX',N1,KBID)
   40 CONTINUE


C     RECOPIE DE COLLE2 DANS COLLE1 :
C     ------------------------------
      CALL JEDETR(COLLE1)
      CALL JEDUPO(COLLE2,BASE,COLLE1,.FALSE.)


C     -- MENAGE :
      CALL JEDETR(COLLE2)
      CALL JEDEMA()
      END
