      SUBROUTINE MODOPT ( LESOPT, NBOPT )
      IMPLICIT   NONE
      INTEGER             NBOPT
      CHARACTER*24        LESOPT
C ----------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF UTILITAI  DATE 11/03/2003   AUTEUR DURAND C.DURAND 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C
C    CETTE ROUTINE AJOUTE DES OPTIONS DE CALCUL DANS CALC_ELEM SI
C    CELLES-CI ONT ETE OMISES :
C
C    SI EPSI_ELNO_TUYO ALORS EPSI_ELGA_DEPL
C    SI EPEQ_ELNO_TUYO ALORS EQUI_ELGA_EPSI
C    SI SIEQ_ELNO_TUYO ALORS AQUI_ELGA_SIGM
C    SI ERRE_ELEM_NOZ1 ALORS SIEF_ELGA_DEPL PUIS SIGM_NOZ1_ELGA
C    SI SIGM_NOZ1_ELGA ALORS SIEF_ELGA_DEPL
C    SI ERRE_ELEM_NOZ2 ALORS SIEF_ELGA_DEPL PUIS SIGM_NOZ2_ELGA
C    SI SIGM_NOZ2_ELGA ALORS SIEF_ELGA_DEPL
C
C ----------------------------------------------------------------------
C     ----- DEBUT DECLARATIONS NORMALISEES  JEVEUX ---------------------
      INTEGER           ZI
      COMMON / IVARJE / ZI(1)
      REAL*8            ZR
      COMMON / RVARJE / ZR(1)
      COMPLEX*16        ZC
      COMMON / CVARJE / ZC(1)
      LOGICAL           ZL
      COMMON / LVARJE / ZL(1)
      CHARACTER*8       ZK8
      CHARACTER*16              ZK16
      CHARACTER*24                       ZK24
      CHARACTER*32                                ZK32
      CHARACTER*80                                         ZK80
      COMMON / KVARJE / ZK8(1), ZK16(1), ZK24(1), ZK32(1), ZK80(1)
C     ----- FIN  DECLARATIONS  NORMALISEES  JEVEUX ---------------------
      INTEGER       N1, JOPT, IEPSI, IERZ1, IERZ2, INOZ1, INOZ2, JOPT2,
     +              I, J, NBOPT2, INDK16,IEPEQ,ISIEQ
      CHARACTER*8   K8B
      CHARACTER*24  LESOP2
C DEB ------------------------------------------------------------------
C
      CALL JEMARQ()
C
      CALL GETVTX ( ' ', 'OPTION', 1,1,0, K8B, N1 )
      NBOPT = -N1
      CALL WKVECT ( LESOPT, 'V V K16', NBOPT, JOPT )
      CALL GETVTX (' ', 'OPTION'  , 1, 1, NBOPT, ZK16(JOPT), N1)
C
      IEPSI = INDK16( ZK16(JOPT), 'EPSI_ELNO_TUYO', 1, NBOPT )
C
      IEPEQ = INDK16( ZK16(JOPT), 'EPEQ_ELNO_TUYO', 1, NBOPT )
C
      ISIEQ = INDK16( ZK16(JOPT), 'SIEQ_ELNO_TUYO', 1, NBOPT )
C
      IERZ1 = INDK16( ZK16(JOPT), 'ERRE_ELEM_NOZ1', 1, NBOPT )
C
      IERZ2 = INDK16( ZK16(JOPT), 'ERRE_ELEM_NOZ2', 1, NBOPT )
C
      INOZ1 = INDK16( ZK16(JOPT), 'SIGM_NOZ1_ELGA', 1, NBOPT )
C
      INOZ2 = INDK16( ZK16(JOPT), 'SIGM_NOZ2_ELGA', 1, NBOPT )
C
      IF ( IEPSI+IERZ1+IERZ2+INOZ1+INOZ2 .EQ. 0 ) GOTO 9999
C
      LESOP2 = '&&OP0058.NEW_OPTION' 
      CALL JEDUPO ( LESOPT , 'V', LESOP2 , .FALSE. )
      CALL JEDETR ( LESOPT )
      CALL WKVECT ( LESOPT , 'V V K16' , NBOPT+3 , JOPT )
      CALL JEVEUO ( LESOP2 , 'L', JOPT2 )
C
      NBOPT2 = 1
C
      IF (IEPSI.NE.0) THEN
        ZK16(JOPT+NBOPT2-1) = 'EPSI_ELGA_DEPL'
        NBOPT2 = NBOPT2 + 1
        ZK16(JOPT+NBOPT2-1) = 'EPSI_ELNO_TUYO'
        NBOPT2 = NBOPT2 + 1
      ENDIF
C
      IF (IEPEQ.NE.0 ) THEN
         ZK16(JOPT+NBOPT2-1) = 'EQUI_ELGA_EPSI'
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = 'EPEQ_ELNO_TUYO'
         NBOPT2 = NBOPT2 + 1
      ENDIF
C
      IF (ISIEQ.NE.0 ) THEN     
         ZK16(JOPT+NBOPT2-1) = 'EQUI_ELGA_SIGM' 
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = 'SIEQ_ELNO_TUYO'
         NBOPT2 = NBOPT2 + 1
      ENDIF
         NBOPT2 = NBOPT2 - 1

C
      IF( ( IERZ1 .NE. 0 ).OR.
     +          ( IERZ2 .NE. 0 ).OR.
     +          ( INOZ1 .NE. 0 ).OR.
     +          ( INOZ2 .NE. 0 )) THEN               
        NBOPT2 = NBOPT2 + 1
        ZK16(JOPT+NBOPT2-1) = 'SIEF_ELGA_DEPL' 
      ENDIF 
C
      IF ( IERZ1 .NE. 0 ) THEN
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = 'SIGM_NOZ1_ELGA'
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = 'ERRE_ELEM_NOZ1'
      ENDIF
C
      IF ( IERZ2 .NE. 0 ) THEN
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = 'SIGM_NOZ2_ELGA'
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = 'ERRE_ELEM_NOZ2'
      ENDIF
C
      DO 10 I = 1 , NBOPT
         DO 12 J = 1 , NBOPT2
            IF ( ZK16(JOPT2+I-1) .EQ. ZK16(JOPT+J-1) ) GOTO 10
 12      CONTINUE
         NBOPT2 = NBOPT2 + 1
         ZK16(JOPT+NBOPT2-1) = ZK16(JOPT2+I-1)
 10   CONTINUE
C
      NBOPT = NBOPT2
      CALL JEDETR ( LESOP2 )
C
 9999 CONTINUE
      CALL JEDEMA()
      END
