      SUBROUTINE NMDIVR(SDDISC,ITERAT,DIVRES)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF UTILITAI  DATE 13/12/2011   AUTEUR GENIAUT S.GENIAUT 
C ======================================================================
C COPYRIGHT (C) 1991 - 2011  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE GENIAUT S.GENIAUT
C
      IMPLICIT NONE
      INTEGER      ITERAT
      CHARACTER*19 SDDISC
      LOGICAL      DIVRES
C
C ----------------------------------------------------------------------
C
C ROUTINE MECA_NON_LINE (UTILITAIRE)
C
C EVALUATION DE LA DIVERGENCE DU RESIDU :
C    ON DIT QU'IL Y A DIVERGENCE DU RESIDU SSI :
C       MIN[ R(I), R(I-1) ] > R(I-2), A PARTIR DE I=3 (COMME ABAQUS)
C
C    OU R(I)   EST LE RESIDU A L'ITERATION COURANTE
C       R(I-1) EST LE RESIDU A L'ITERATION MOINS 1
C       R(I-2) EST LE RESIDU A L'ITERATION MOINS 2
C
C ----------------------------------------------------------------------
C
C
C IN      SDDISC : SD DISCRETISATION
C IN      ITERAT : NUMERO ITERATION NEWTON
C IN/OUT  DIVRES : .TRUE. SI LE RESIDU DIVERGE
C
C
      REAL*8       R,RM1,RM2,R8BID
      INTEGER      IBID,NECHEC,IECHEC
      CHARACTER*8  K8BID
      CHARACTER*16 NOMEVD
      LOGICAL      LEVEN
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()

C     RECHECHE DE LE PRESENCE DE L'EVENEMENT DIVE_RESI PARMI LES
C     EVENEMENTS DEFINIS
      LEVEN  = .FALSE.
      CALL UTDIDT('L'   ,SDDISC,'LIST',IBID  ,'NECHEC',
     &            R8BID ,NECHEC,K8BID )
      DO 100 IECHEC = 1,NECHEC
        CALL UTDIDT('L'   ,SDDISC,'ECHE',IECHEC,'NOM_EVEN',
     &              R8BID ,IBID  ,NOMEVD)

        IF (NOMEVD.EQ.'DIVE_RESI') LEVEN  = .TRUE.
 100  CONTINUE

C     DIVRES N'EST EVALUE QUE SI L'EVENEMENT DIVE_RESI EST PRESENT 
      IF (.NOT.LEVEN) GOTO 999
C
C     DIVRES N'EST EVALUE QU'A PARTIR DE L'ITERATION 3
      IF (ITERAT.LT.3) GOTO 999

C     RESIDU GLOBAL (RESI_GLOB_MAXI) A L'ITERATION COURANTE
      CALL NMLERE(SDDISC,'L','VMAXI',ITERAT,R)

C     RESIDU GLOBAL (RESI_GLOB_MAXI) A L'ITERATION "MOINS 1"
      CALL NMLERE(SDDISC,'L','VMAXI',ITERAT-1,RM1)

C     RESIDU GLOBAL (RESI_GLOB_MAXI) A L'ITERATION "MOINS 2"
      CALL NMLERE(SDDISC,'L','VMAXI',ITERAT-2,RM2)

C     SI LE RESIDU N'EST PAS DIMINUE SUR UNE DES 2 ITERATIONS : DIV
      IF ( MIN(R,RM1).GT.RM2 ) DIVRES = .TRUE.
C
 999  CONTINUE

      CALL JEDEMA()
      END
