      SUBROUTINE OBCR26(NOMOBJ,NBPARB,NBPARI,NBPARR,NBPARK,
     &                  NBPARO)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF UTILITAI  DATE 09/04/2013   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2013  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE ABBAS M.ABBAS
C
      IMPLICIT      NONE
      INCLUDE       'jeveux.h'
      CHARACTER*24  NOMOBJ
      INTEGER       NBPARB,NBPARI,NBPARR,NBPARK,NBPARO
C
C ----------------------------------------------------------------------
C
C ROUTINE UTILITAIRE (GESTION STRUCTS)
C
C CREATION - SD IMPRESSION
C
C ----------------------------------------------------------------------
C
C
C IN  NOMOBJ : NOM DE L'OBJET
C OUT NBPARB : NOMBRE DE VALEURS DE TYPE BOOLEEN
C OUT NBPARI : NOMBRE DE VALEURS DE TYPE ENTIER
C OUT NBPARR : NOMBRE DE VALEURS DE TYPE REEL
C OUT NBPARK : NOMBRE DE VALEURS DE TYPE CHAINE
C OUT NBPARO : NOMBRE DE VALEURS DE TYPE OBJET
C
C ----------------------------------------------------------------------
C
      INTEGER      NPARAB,NPARAI,NPARAR,NPARAK,NPARAO
      PARAMETER    (NPARAB=4,NPARAI=2,NPARAR=0,NPARAK=0,NPARAO=1)
      CHARACTER*24 PARAB(NPARAB)
      CHARACTER*24 PARAI(NPARAI)
      CHARACTER*24 PARAR(NPARAR)
      CHARACTER*24 PARAK(NPARAK)
      CHARACTER*24 PARAO(NPARAO)
      CHARACTER*24 TYPEO(NPARAO)
C
C ----------------------------------------------------------------------
C
C
C --- BOOLEEN
C
      DATA PARAB /'INFO_RESIDU'  ,'INFO_TEMPS'   ,'TABL_CONV_CSV',
     &            'PRINT'        /
C
C --- ENTIER
C
      DATA PARAI /'UNIT_CONV_CSV','REAC_AFFICHAGE'/
C
C --- REEL
C
C      DATA PARAR //
C
C --- CHAINE
C
C      DATA PARAK //
C
C --- OBJETS
C
      DATA PARAO /'TABLEAU_CONV'/
C
C --- TYPE OBJETS
C
      DATA TYPEO /'TABLEAU'/
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
C --- INITIALISATIONS
C
      NBPARB = NPARAB
      NBPARI = NPARAI
      NBPARR = NPARAR
      NBPARK = NPARAK
      NBPARO = NPARAO
C
C --- CREATION SD
C
      CALL OBCRCR(NOMOBJ,NBPARB,NBPARI,NBPARR,NBPARK,
     &            NBPARO,PARAB ,PARAI ,PARAR ,PARAK ,
     &            PARAO ,TYPEO )
C
      CALL JEDEMA()
      END
