      SUBROUTINE RSUTRO(NOMSD,IORDG,IORDR,IERR)
      IMPLICIT NONE
      INCLUDE 'jeveux.h'
      INTEGER IORDG,IORDR,IERR
      CHARACTER*(*) NOMSD
C ----------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF UTILITAI  DATE 04/09/2012   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE PELLET J.PELLET
C      CORRESPONDANCE NUMERO D'ORDRE UTILISATEUR (IORDR) AVEC LE
C      NUMERO DE RANGEMENT (IORDG).
C ----------------------------------------------------------------------
C IN  : NOMSD  : NOM DE LA STRUCTURE "RESULTAT"
C IN  : IORDG  : NUMERO DE RANGEMENT.
C OUT : IORDR  : NUMERO D'ORDRE UTILISATEUR.
C OUT : IERR   : CODE RETOUR
C                = 0  , LA RELATION EXISTE .
C                = 10 , LE .ORDR N'EST PAS REMPLI (SD RESULTAT VIDE)
C                = 20 , LE NUMERO DE RANGEMENT EST SUPERIEUR AU MAX
C                       AUTORISE
C ----------------------------------------------------------------------
      CHARACTER*19 NOMD2
      CHARACTER*1 K1BID
C ----------------------------------------------------------------------

C-----------------------------------------------------------------------
      INTEGER JORDR ,NBORDR
C-----------------------------------------------------------------------
      CALL JEMARQ()
      IERR = 0
      NOMD2 = NOMSD

C     --- RECUPERATION DU .ORDR ---
      CALL JELIRA(NOMD2//'.ORDR','LONUTI',NBORDR,K1BID)
      IF (NBORDR.EQ.0) THEN
        IERR = 10
      ELSE IF (IORDG.GT.NBORDR) THEN
        IERR = 20
      ELSE
        CALL JEVEUO(NOMD2//'.ORDR','L',JORDR)
        IORDR = ZI(JORDR+IORDG-1)
      END IF

      CALL JEDEMA()
      END
