      SUBROUTINE FETTOR(OPTION,INFOFE,RANG,NBI,IRG1,IRG,IRP,IRZ,IFM)
C ----------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGELINE  DATE 13/06/2012   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE BOITEAU O.BOITEAU
C TOLE CRP_4
C-----------------------------------------------------------------------
C    - FONCTION REALISEE:  TEST ORTHOGONALITE DU GCPPC DE ALGO FETI
C                          POUR SOULAGER ALFETI.F
C     ------------------------------------------------------------------
C     IN  OPTION : IN   : OPTION DE LA ROUTINE
C     IN  INFOFE : CH19 : CHAINE DE CHARACTERES POUR MONITORING FETI
C     IN  RANG   : IN   : RANG DU PROCESSEUR
C     IN  NBI    : IN   : TAILLE DE L'INTERFACE
C     IN  IRG1   : IN   : ADRESSE DE PRI-1 AVANT MAJ
C     IN  IRG    : IN   : IDEM APRES MAJ
C     IN  IRP    : IN   : ADRESSE DE DI-1
C     IN  IRZ    : IN   : ADRESSE DE FI*DI-1
C     IN  IFM    : IN   : UNITE LOGIQUE D'AFFICHAGE
C----------------------------------------------------------------------
C CORPS DU PROGRAMME
      IMPLICIT NONE

C DECLARATION PARAMETRES D'APPELS
      INCLUDE 'jeveux.h'
      INTEGER      OPTION,RANG,NBI,IRG1,IRG,IRP,IRZ,IFM
      CHARACTER*24 INFOFE

C DECLARATION VARIABLES LOCALES
      REAL*8       DDOT,RAUX
      INTEGER*4    NBI4

C CORPS DU PROGRAMME
      CALL JEMARQ()

      IF ((INFOFE(8:8).EQ.'T').AND.(RANG.EQ.0)) THEN
        NBI4=NBI
        IF (OPTION.EQ.1) THEN
C TEST 1 ORTHOGONALITE DU GCPPC
          RAUX=DDOT(NBI4,ZR(IRG),1,ZR(IRG1),1)
          WRITE(IFM,*)'RANG ',RANG,' TEST <PRI,PRI-1>',RAUX
          RAUX=DDOT(NBI4,ZR(IRG),1,ZR(IRP),1)
          WRITE(IFM,*)'RANG ',RANG,' TEST <PRI,DI-1>',RAUX
        ELSE IF (OPTION.EQ.2) THEN
C TEST 2 ORTHOGONALITE DU GCPPC
          RAUX=DDOT(NBI4,ZR(IRP),1,ZR(IRZ),1)
          WRITE(IFM,*)'RANG ',RANG,' TEST <DI,FI*DI-1>',RAUX
        ELSE
          CALL ASSERT(.FALSE.)
        ENDIF
      ENDIF

      CALL JEDEMA()
      END
