# coding=utf-8

import os.path as osp
from pprint import pformat


def configure(self):
    # configure done by bibpyt
    pass

def build(self):
    get_srcs = self.path.get_src().ant_glob
    env = self.all_envs[self.variant]

    self(
        features = 'py',
            name = 'code_aster_py',
          source = get_srcs('**/*.py'),
    install_from = '.',
    install_path = osp.join(env.ASTERLIBDIR, "code_aster"),
    )

    self(
        features = 'subst py',
            name = 'aster_version',
          source = 'aster_version.pytmpl',
          target = 'aster_version.py',
    install_path = osp.join(env.ASTERLIBDIR, "code_aster", "Cata"),
             use = ['bibpyt'],
    VERSION_INFO = pformat(env['ASTER_VERSION']),
    )
