      SUBROUTINE ARLAS0(NUM1  ,NUM2  ,CNX   ,CNXC  ,
     &                  INO1  ,NBVLI    ,INO2  ,INO2C ,
     &                  PTMT)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF MODELISA  DATE 13/10/2009   AUTEUR CAO B.CAO 
C ======================================================================
C COPYRIGHT (C) 1991 - 2002  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C
C
C ======================================================================
C RESPONSABLE MEUNIER S.MEUNIER
C
      IMPLICIT NONE
      INTEGER NUM1,NUM2,CNX(*),CNXC(*)
      INTEGER INO1(*),NBVLI,INO2(*),INO2C(*)
      INTEGER PTMT(*)
C
C ----------------------------------------------------------------------
C
C ROUTINE ARLEQUIN
C
C GESTION DES RELATIONS LINEAIRES
C POINTEURS DANS LA MATRICE MORSE D'UN COUPLE DE MAILLE (NUM1,NUM2)
C
C ----------------------------------------------------------------------
C
C
C IN  NUM1    : NUMERO DE MAILLE LIGNE (INDEX CNXC)
C IN  NUM2    : NUMERO DE MAILLE COLONNE (INDEX CNXC)
C IN  CNX     : COLLECTION CONNECTIVITE DU MAILLAGE
C IN  CNXC    : LONGUEUR CUMULEE ASSOCIEE A CNX
C IN  INO1    : LISTE NOEUDS LIGNES (CF ARLFC*)
C IN  NBVLI   : LONGUEUR DU VECTEUR INO1
C IN  INO2    : COLLECTION NOEUDS COLONNES
C IN  INO2C   : LONGUEUR CUMULEE ASSOCIEE A INO2
C OUT PTMT(*) : POINTEURS DANS LA MATRICE MORSE,
C                  DEFINIE PAR INO1 ET INO2, POUR LES
C                  NOEUDS DES MAILLES NUM1 ET NUM2
C                 ( POINTEUR (NUM1.NO1,NUM2.NO1),
C                   POINTEUR (NUM1.NO1,NUM2.NO2), ...,
C                   POINTEUR (NUM1.NO2,NUM2.NO1), ... )
C
C ----------------------------------------------------------------------
C
      INTEGER NBVLR1,NBVLR2,PMAT,NBEV1,LGNM,LGNM0,NBEV2,VLTER,VLTER0,
     &        FCPIG,FCPIG0,MOY,NTRG,IAUX,JAUX,KAUX
C
C ----------------------------------------------------------------------
C
      KAUX = 0

      PMAT   = CNXC(NUM1)
      NBVLR1 = CNXC(NUM1+1) - PMAT
      LGNM0  = CNXC(NUM2)
      NBVLR2 = CNXC(NUM2+1) - LGNM0


      DO 10 IAUX = 1, NBVLR1

        VLTER = 1
        FCPIG = NBVLI + 1
        NBEV1 = CNX(PMAT)
        PMAT = PMAT + 1

C ----- RECHERCHE PAR DICHOTOMIE

 20     CONTINUE
        MOY = (VLTER + FCPIG)/2
        NTRG = INO1(MOY)

        IF (NBEV1.NE.NTRG) THEN
          IF (NBEV1.LT.NTRG) THEN
            FCPIG = MOY
          ELSE
            VLTER = MOY
          ENDIF

          GOTO 20
        ENDIF

        VLTER0 = INO2C(MOY)
        FCPIG0 = INO2C(MOY+1)
        LGNM = LGNM0

        DO 10 JAUX = 1, NBVLR2

          VLTER = VLTER0
          FCPIG = FCPIG0
          NBEV2 = CNX(LGNM)
          LGNM = LGNM + 1

C ------- RECHERCHE PAR DICHOTOMIE

 30       CONTINUE
          MOY = (VLTER + FCPIG)/2
          NTRG = INO2(MOY)

          IF (NBEV2.NE.NTRG) THEN
            IF (NBEV2.LT.NTRG) THEN
              FCPIG = MOY
            ELSE
              VLTER = MOY
            ENDIF
            GOTO 30
          ENDIF
C ------- STOCKAGE
          KAUX = KAUX + 1
          PTMT(KAUX) = MOY

 10   CONTINUE

      END
