      SUBROUTINE ECLEVO(TEXTE,NBMA,CODVOI,IAREPE,IADDVO,IADVOI)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF MODELISA  DATE 06/05/2008   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2008  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
C  ECRITURE DES VOISINAGES RESTREINTS POUR TOUTES LES
C  MAILLES AFFECTEES AVEC LE CODE CODVOI
C
      IMPLICIT NONE
      CHARACTER*(*) TEXTE


      CHARACTER*16 CODVOI
      INTEGER NVOIMA,NSCOMA,IAREPE,IADDVO,IADVOI,NBVOIS
      PARAMETER(NVOIMA=100,NSCOMA=4)
      INTEGER LIVOIS(1:NVOIMA),TYVOIS(1:NVOIMA),NBNOVO(1:NVOIMA)
      INTEGER NBSOCO(1:NVOIMA),LISOCO(1:NVOIMA,1:NSCOMA,1:2)

      INTEGER IV,IS,IMA,NBMA


C
      WRITE (6,*)
      WRITE (6,*)' DUMP_LESVOI ',TEXTE,' POUR CODE ',CODVOI
      WRITE (6,*)
      DO 30 IMA=1,NBMA
        CALL VOIUTI(IMA,CODVOI,NVOIMA,NSCOMA,IAREPE,IADDVO,IADVOI,
     &              NBVOIS,LIVOIS,TYVOIS,NBNOVO,NBSOCO,LISOCO)
        IF (NBVOIS.GT.0) THEN
          WRITE (6,*)' MAILLE ',IMA,' NOMBRE DE VOISINS ',NBVOIS
          DO 20 IV=1,NBVOIS
            WRITE (6,*)' VOISIN ',IV,' MAILLE ',LIVOIS(IV),' TYPE ',
     &        TYVOIS(IV),' NBNO',NBNOVO(IV),' NB SOM COMMMUNS ',
     &        NBSOCO(IV)
            DO 10 IS=1,NBSOCO(IV)
              WRITE (6,*)' SOMMET ',IS,' NUM DANS MA ',LISOCO(IV,IS,1),
     &          ' NUM DANS MV ',LISOCO(IV,IS,2)
   10       CONTINUE
   20     CONTINUE
        ENDIF
   30 CONTINUE
      WRITE (6,*)
      WRITE (6,*)' FIN DUMP_LESVOI '
      WRITE (6,*)
      END
