      SUBROUTINE MOYTEM ( FAMI, NPG, NSPG, POUM, TEMP, IRET)
      IMPLICIT   NONE
      INTEGER             NPG, NSPG,IRET
      REAL*8              TEMP
      CHARACTER*(*)       FAMI, POUM
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF MODELISA  DATE 16/10/2007   AUTEUR SALMONA L.SALMONA 
C ======================================================================
C COPYRIGHT (C) 1991 - 2007  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
      INTEGER  KPG, KSP
      REAL*8   TG, TGTOT
C
      TGTOT = 0.D0
      DO 10 KPG = 1 , NPG
         DO 20 KSP = 1 , NSPG
            CALL RCVARC(' ','TEMP',POUM,FAMI,KPG,KSP,TG,IRET)
            IF ( IRET .EQ. 1 ) THEN
               TEMP = TG
               GOTO 9999
            ENDIF
            TGTOT = TGTOT + TG
  20     CONTINUE
  10  CONTINUE
      TEMP = TGTOT/(NPG*NSPG)
 9999 CONTINUE
      END
