      SUBROUTINE OP0059(IER)
      IMPLICIT REAL*8 (A-H,O-Z)
      INTEGER IER
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF MODELISA  DATE 08/06/2004   AUTEUR JMBHH01 J.M.PROIX 
C RESPONSABLE JMBHH01 J.M.PROIX
C ======================================================================
C COPYRIGHT (C) 1991 - 2004  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C     COMMANDE:  DEFI_COMPOR
C ----- DEBUT --- COMMUNS NORMALISES  JEVEUX  --------------------------
C      INTEGER COMPORCPRI
      CHARACTER*8 COMPOR, MATERI, TYPPAR(5)
      CHARACTER*16 OPER, TYPE, NOMPAR(5), ECOULE, ECROIS, ECROCI, ELASTI
      CHARACTER*16 FASYGL, KBID, NOMS(6),COMDES
      REAL*8 NOMB(6), RBID,MS(6),PGL(3,3)
      COMPLEX*16 CBID
      INTEGER IOCC, NBOCC, NBMAT, NBECOU, NBECRO, NBCINE, NBELAS, NBFASY
      INTEGER TABDES(3)
      INTEGER ZI, IN, IM
      COMMON / IVARJE / ZI(1)
      REAL*8 ZR
      COMMON / RVARJE / ZR(1)
      COMPLEX*16 ZC
      COMMON / CVARJE / ZC(1)
      LOGICAL ZL
      COMMON / LVARJE / ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON / KVARJE / ZK8(1), ZK16(1), ZK24(1), ZK32(1), ZK80(1)
      
C------------FIN  COMMUNS NORMALISES  JEVEUX  --------------------------
      
      CALL GETRES(COMPOR,TYPE,OPER)
      COMDES='&&OP0059.TABLETX'
      CALL TBCRSD(COMDES,'V')
      NOMPAR(1)='FAMI_SYST_GLIS'
      NOMPAR(2)='MAT_SYST'
      NOMPAR(3)='ECOULEMENT'
      NOMPAR(4)='ECRO_ISOT'
      NOMPAR(5)='ECRO_CINE'
      TYPPAR(1)='K16'
      TYPPAR(2)='K16'
      TYPPAR(3)='K16'
      TYPPAR(4)='K16'
      TYPPAR(5)='K16'
      NBELAS=0
      NVI=6
      CALL TBAJPA(COMDES, 5,NOMPAR,TYPPAR)
      CALL GETFAC('MONOCRISTAL',NBOCC)
      CALL WKVECT(COMPOR//'.CPRK', 'G V K16',5*NBOCC+1,IM)
      DO 9 IOCC=1,NBOCC
        CALL GETVID('MONOCRISTAL','MATER',IOCC,1,1,MATERI,NBMAT)
        CALL GETVTX('MONOCRISTAL','ECOULEMENT',IOCC,1,1,ECOULE,NBECOU)
        CALL GETVTX('MONOCRISTAL','ECRO_ISOT',IOCC,1,1,ECROIS,NBECRO)
        CALL GETVTX('MONOCRISTAL','ECRO_CINE',IOCC,1,1,ECROCI,NBCINE)
        CALL GETVTX('MONOCRISTAL','ELAS',IOCC,1,1,ELASTI,NBELA1)
        IF (NBELA1.GT.0) THEN   
           IF (NBELAS.EQ.0) THEN        
              NBELAS=1
           ELSE
              CALL UTMESS('F','DEFI_COMPOR','UN SEUL ELAS SVP')
           ENDIF
        ENDIF
        CALL GETVTX('MONOCRISTAL','FAMI_SYST_GLIS',IOCC,1,1,
     &               FASYGL,NBFASY)
        NOMS(1)=FASYGL
        NOMS(2)=MATERI
        NOMS(3)=ECOULE
        NOMS(4)=ECROIS
        NOMS(5)=ECROCI
        CALL TBAJLI(COMDES,5, NOMPAR,0,0.D0,CBID,NOMS,0)
        DO 11 J=1,5
           ZK16(IM-1+(IOCC-1)*5+J)=NOMS(J)
11      CONTINUE           
        CALL LCMMSG(FASYGL,NBSYS,0,PGL,MS)
        NVI=NVI+3*NBSYS
9     CONTINUE
       ZK16(IM+5*NBOCC)=ELASTI
C      CALL TBIMPR(COMDES,' ','EXCEL','MESSAGE',0,' ',0,' ',' ',' ')
      TABDES(1)=NBOCC
      TABDES(2)=5
      TABDES(3)=NVI
      CALL WKVECT(COMPOR//'.CPRI', 'G V I',3,IN)
      DO 999 I=1,3
         ZI(IN+I-1)=TABDES(I)
999   CONTINUE   
      CALL JEDETC('V',COMDES,1)
      END
