      SUBROUTINE SURFC2(CHAR,NOMA,IFM)
C      
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF MODELISA  DATE 30/04/2007   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2007  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE ABBAS M.ABBAS
C 
      IMPLICIT NONE
      CHARACTER*8 CHAR
      CHARACTER*8 NOMA
      INTEGER     IFM      
C      
C ----------------------------------------------------------------------
C
C ROUTINE CONTACT (METHODE CONTINUE - AFFICHAGE DONNEES)
C
C AFFICHAGE LES INFOS CONTENUES DANS LA SD CONTACT POUR LA FORMULATION
C CONTINUE
C      
C ----------------------------------------------------------------------
C
C
C IN  CHAR   : NOM UTILISATEUR DU CONCEPT DE CHARGE
C IN  NOMA   : NOM DU MAILLAGE
C IN  IFM    : UNITE D'IMPRESSION
C
C -------------- DEBUT DECLARATIONS NORMALISEES JEVEUX -----------------
C
      CHARACTER*32  JEXNUM
      INTEGER ZI
      COMMON /IVARJE/ ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C
C ---------------- FIN DECLARATIONS NORMALISEES JEVEUX -----------------
C
      INTEGER      CFMMVD,ZMETH,ZTOLE,ZTGDE,ZPOUD
      INTEGER      ZECPD,ZCMCF
      INTEGER      NZOCO,NNOCO,NMACO
      INTEGER      IZONE,FORM
      REAL*8       JSUP    
      CHARACTER*24 NOEUMA,MAILMA
C
      INTEGER      INO,IMA,JDEC,JNOMNO,JNOMMA
      INTEGER      NUMRAC,NRACC,NUMFON,NFOND       
C
      CHARACTER*24 ECPDON,CARACF  
      INTEGER      JECPD ,JCMCF  
C
      CHARACTER*24 FORMCO,METHCO
      INTEGER      JFORM ,JMETH  
C           
      CHARACTER*24 NDIMCO,CONTNO
      INTEGER      JDIM  ,JNOCO 
C
      CHARACTER*24 TANPOU,DIRCO ,JEUSUP,NORLIS,TANDEF,TOLECO 
      INTEGER      JPOUDI,JDIR  ,JJSUP ,JNORLI,JTGDEF,JTOLE 
C
      CHARACTER*24 BARSNO,PBARS ,BARSMA,PBARM ,RACCNO,PRACC  
      INTEGER      JBARS ,JPBARS,JBARM ,JPBARM,JRACC ,JPRACC      
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ
C
C --- ACCES SD DU MAILLAGE
C
      NOEUMA = NOMA(1:8)//'.NOMNOE'
      MAILMA = NOMA(1:8)//'.NOMMAI'      
C   
C --- COMMUNS TOUTES FORMULATIONS 
C 
      FORMCO = CHAR(1:8)//'.CONTACT.FORMCO'
      METHCO = CHAR(1:8)//'.CONTACT.METHCO' 
      CALL JEVEUO(FORMCO,'L',JFORM)      
      CALL JEVEUO(METHCO,'L',JMETH) 
      ZMETH  = CFMMVD('ZMETH')  
      NZOCO  = ZI(JMETH)
C
      IZONE  = 1
      FORM   = ZI(JFORM-1+IZONE)
      IF (FORM.NE.2) THEN
        GOTO 999
      ENDIF   
C   
C --- COMMUNS AVEC FORM. MAILLEES (DISCRET ET CONTINUE MAIS PAS XFEM)
C  
      NDIMCO = CHAR(1:8)//'.CONTACT.NDIMCO'
      CONTNO = CHAR(1:8)//'.CONTACT.NOEUCO' 
      CALL JEVEUO(NDIMCO,'L',JDIM)
      CALL JEVEUO(CONTNO,'L',JNOCO) 
      NNOCO  = ZI(JDIM+4)   
      NMACO  = ZI(JDIM+3) 
C   
C --- COMMUNS AVEC FORM. DISCRETE
C  
      TANPOU = CHAR(1:8)//'.CONTACT.TANPOU'
      DIRCO  = CHAR(1:8)//'.CONTACT.DIRCO'
      JEUSUP = CHAR(1:8)//'.CONTACT.JSUPCO'
      NORLIS = CHAR(1:8)//'.CONTACT.NORLIS'
      TANDEF = CHAR(1:8)//'.CONTACT.TANDEF'
      TOLECO = CHAR(1:8)//'.CONTACT.TOLECO'       
C
      CALL JEVEUO(TANPOU,'L',JPOUDI)
      CALL JEVEUO(DIRCO ,'L',JDIR)
      CALL JEVEUO(JEUSUP,'L',JJSUP)
      CALL JEVEUO(NORLIS,'L',JNORLI)
      CALL JEVEUO(TANDEF,'L',JTGDEF)
      CALL JEVEUO(TOLECO,'L',JTOLE)
C 
      ZPOUD = CFMMVD('ZPOUD')
      ZTGDE = CFMMVD('ZTGDE') 
      ZTOLE = CFMMVD('ZTOLE')  
C   
C --- COMMUNS AVEC FORM. XFEM
C 
      ECPDON = CHAR(1:8)//'.CONTACT.ECPDON'
      CARACF = CHAR(1:8)//'.CONTACT.CARACF'
C
      CALL JEVEUO(ECPDON,'L',JECPD)
      CALL JEVEUO(CARACF,'L',JCMCF)      
C     
      ZCMCF = CFMMVD('ZCMCF')      
      ZECPD = CFMMVD('ZECPD') 
C   
C --- SPECIFIQUES FORMULATION CONTINUE
C      
      BARSNO = CHAR(1:8)//'.CONTACT.BANOCO'
      PBARS  = CHAR(1:8)//'.CONTACT.PBANOCO'  
      BARSMA = CHAR(1:8)//'.CONTACT.BAMACO'
      PBARM  = CHAR(1:8)//'.CONTACT.PBAMACO'
      RACCNO = CHAR(1:8)//'.CONTACT.RANOCO'
      PRACC  = CHAR(1:8)//'.CONTACT.PRANOCO'    
C
      CALL JEVEUO(BARSNO,'L',JBARS )
      CALL JEVEUO(PBARS ,'L',JPBARS)
      CALL JEVEUO(BARSMA,'L',JBARM )
      CALL JEVEUO(PBARM ,'L',JPBARM)
      CALL JEVEUO(RACCNO,'L',JRACC )
      CALL JEVEUO(PRACC ,'L',JPRACC)  
C
C --- CREATION VECTEURS TEMPORAIRES
C      
      CALL WKVECT('&&SURFC2.TRAVNO','V V K8',NZOCO*NNOCO,JNOMNO)
      CALL WKVECT('&&SURFC2.TRAVMA','V V K8',NZOCO*NMACO,JNOMMA)
C
C --- IMPRESSIONS POUR L'UTILISATEUR
C 
      WRITE (IFM,*)      
      WRITE (IFM,*) '<CONTACT> INFOS SPECIFIQUES SUR LA FORMULATION'//
     &              ' CONTINUE'
      WRITE (IFM,*)           
C 
C --- IMPRESSIONS POUR LES JEUX SUPPS
C 
      WRITE (IFM,*) '<CONTACT> ... JEU SUPP.' 
      DO 20 IZONE = 1,NZOCO
        JSUP   = ZR(JJSUP+IZONE-1)      
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE          
        WRITE (IFM,1030) JSUP      
 20   CONTINUE      
C          
 1030 FORMAT (' <CONTACT> ...... TYPE REEL              : ',E12.5)    
C
C --- INFOS COMMUNES AVEC FORMULATION CONTINUE
C
      WRITE (IFM,*) '<CONTACT> ... VECT_ORIE_POU'     
      DO 250 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE        
        IF (ZI(JMETH+ZMETH*(IZONE-1)+2).EQ.2) THEN  
          WRITE (IFM,1071) ZR(JPOUDI+ZPOUD*(IZONE-1)),
     &                     ZR(JPOUDI+ZPOUD*(IZONE-1)+1),
     &                     ZR(JPOUDI+ZPOUD*(IZONE-1)+2)
        ELSE
          WRITE (IFM,1072) 
        ENDIF
 250  CONTINUE 
C
      WRITE (IFM,*) '<CONTACT> ... DIRE_APPA'     
      DO 251 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE        
        WRITE (IFM,1071) ZR(JDIR+3*(IZONE-1)),
     &                   ZR(JDIR+3*(IZONE-1)+1),
     &                   ZR(JDIR+3*(IZONE-1)+2)
 251  CONTINUE 
C  
      WRITE (IFM,*) '<CONTACT> ... LISSAGE'     
      DO 252 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE        
        IF (ZI(JNORLI+(IZONE-1)+1).EQ.0) THEN  
          WRITE (IFM,1073) 'NON        '
        ELSEIF (ZI(JNORLI+(IZONE-1)+1).EQ.1) THEN  
          WRITE (IFM,1073) 'OUI        '
        ELSE
          WRITE (IFM,1073) 'INDEFINI   ' 
          CALL ASSERT(.FALSE.)              
        ENDIF
 252  CONTINUE 
C
      WRITE (IFM,*) '<CONTACT> ... VECT_Y'     
      DO 253 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE        
        IF (ZI(JMETH+ZMETH*(IZONE-1)+2).EQ.1) THEN  
          WRITE (IFM,1071) ZR(JTGDEF+ZTGDE*(IZONE-1)),
     &                     ZR(JTGDEF+ZTGDE*(IZONE-1)+1),
     &                     ZR(JTGDEF+ZTGDE*(IZONE-1)+2)
        ELSE
          WRITE (IFM,1072) 
        ENDIF
 253  CONTINUE 
C 
      WRITE (IFM,*) '<CONTACT> ... VECT_Z'     
      DO 256 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE        
        IF (ZI(JMETH+ZMETH*(IZONE-1)+2).EQ.1) THEN  
          WRITE (IFM,1071) ZR(JTGDEF+ZTGDE*(IZONE-1)+3),
     &                     ZR(JTGDEF+ZTGDE*(IZONE-1)+4),
     &                     ZR(JTGDEF+ZTGDE*(IZONE-1)+5)
        ELSE
          WRITE (IFM,1072) 
        ENDIF
 256  CONTINUE 
C 
 1071 FORMAT (' <CONTACT> ...... (X,Y,Z) : ',E12.5,E12.5,E12.5)   
 1072 FORMAT (' <CONTACT> ...... NON DEFINI')
 1073 FORMAT (' <CONTACT> ...... ',A8) 
C 
C --- IMPRESSIONS POUR LES PARAMETRES DE TOLERANCE
C
      WRITE (IFM,*) '<CONTACT> ... PARAMETRES DE TOLERANCE'     
      DO 300 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE          
        WRITE (IFM,1070) 'TOLE_PROJ_EXT   ',ZR(JTOLE+ZTOLE*(IZONE-1))
        WRITE (IFM,1070) 'TOLE_PROJ_INT   ',ZR(JTOLE+ZTOLE*(IZONE-1)+1)
        WRITE (IFM,1070) 'ALARME_JEU      ',ZR(JTOLE+ZTOLE*(IZONE-1)+2)
        WRITE (IFM,1070) 'TOLE_INTERP     ',ZR(JTOLE+ZTOLE*(IZONE-1)+3)
        WRITE (IFM,1070) 'RESI_ABSO       ',ZR(JTOLE+ZTOLE*(IZONE-1)+4)
        WRITE (IFM,1070) 'RESI_ITER       ',ZR(JTOLE+ZTOLE*(IZONE-1)+5)
        WRITE (IFM,1070) 'COEF_RESI       ',ZR(JTOLE+ZTOLE*(IZONE-1)+6)
 300  CONTINUE 
C
C --- INFOS SPECIFIQUES POUR FORMULATION CONTINUE
C
      WRITE (IFM,*) '<CONTACT> ... PARAMETRES DIVERS POUR FORM. CONT.'
      DO 310 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE          
        WRITE (IFM,1020) 'AXISYMETRIE     ',ZI(JECPD+ZECPD*(IZONE-1)+1)
        WRITE (IFM,1020) 'ITER_CONT_MAXI  ',ZI(JECPD+ZECPD*(IZONE-1)+2)
        WRITE (IFM,1020) 'ITER_FROT_MAXI  ',ZI(JECPD+ZECPD*(IZONE-1)+3)
        WRITE (IFM,1020) 'ITER_GEOM_MAXI  ',ZI(JECPD+ZECPD*(IZONE-1)+4)
        WRITE (IFM,1020) 'CONTACT_INIT    ',ZI(JECPD+ZECPD*(IZONE-1)+5)
        WRITE (IFM,1020) 'FORMULATION     ',ZI(JECPD+ZECPD*(IZONE-1)+6)
 310  CONTINUE 
C
      DO 320 IZONE = 1,NZOCO
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE          
        WRITE (IFM,1070) 'INTEGRATION     ',ZR(JCMCF+ZCMCF*(IZONE-1)+1)
        WRITE (IFM,1070) 'ALGO_CONT       ',ZR(JCMCF+ZCMCF*(IZONE-1)+16)
        WRITE (IFM,1070) 'COEF_REGU_CONT  ',ZR(JCMCF+ZCMCF*(IZONE-1)+2)
        WRITE (IFM,1070) 'COEF_STAB_CONT  ',ZR(JCMCF+ZCMCF*(IZONE-1)+17)
        WRITE (IFM,1070) 'COEF_PENA_CONT  ',ZR(JCMCF+ZCMCF*(IZONE-1)+18)
        WRITE (IFM,1070) 'ALGO_FROT       ',ZR(JCMCF+ZCMCF*(IZONE-1)+19)
        WRITE (IFM,1070) 'COEF_REGU_FROT  ',ZR(JCMCF+ZCMCF*(IZONE-1)+3)
        WRITE (IFM,1070) 'COEF_STAB_FROT  ',ZR(JCMCF+ZCMCF*(IZONE-1)+20)
        WRITE (IFM,1070) 'COEF_PENA_CONT  ',ZR(JCMCF+ZCMCF*(IZONE-1)+21)
        WRITE (IFM,1070) 'FROTTEMENT      ',ZR(JCMCF+ZCMCF*(IZONE-1)+5)
        WRITE (IFM,1070) 'COULOMB         ',ZR(JCMCF+ZCMCF*(IZONE-1)+4)
        WRITE (IFM,1070) 'SEUIL_INIT      ',ZR(JCMCF+ZCMCF*(IZONE-1)+6)
        WRITE (IFM,1070) 'COMPLIANCE      ',ZR(JCMCF+ZCMCF*(IZONE-1)+7)
        WRITE (IFM,1070) 'ASPERITE        ',ZR(JCMCF+ZCMCF*(IZONE-1)+8)
        WRITE (IFM,1070) 'E_N             ',ZR(JCMCF+ZCMCF*(IZONE-1)+9)
        WRITE (IFM,1070) 'E_T             ',ZR(JCMCF+ZCMCF*(IZONE-1)+10)
        WRITE (IFM,1070) 'USURE           ',ZR(JCMCF+ZCMCF*(IZONE-1)+13)
        WRITE (IFM,1070) 'K               ',ZR(JCMCF+ZCMCF*(IZONE-1)+14)
        WRITE (IFM,1070) 'H               ',ZR(JCMCF+ZCMCF*(IZONE-1)+15)
        WRITE (IFM,1070) 'FOND_FISSURE    ',ZR(JCMCF+ZCMCF*(IZONE-1)+11)
        WRITE (IFM,1070) 'RACCORD_LINE_QUA',ZR(JCMCF+ZCMCF*(IZONE-1)+12)
        WRITE (IFM,1070) 'EXCLUSION_PIV_NU',ZR(JCMCF+ZCMCF*(IZONE-1)+22)
        WRITE (IFM,1070) '<INUTILISE>     ',ZR(JCMCF+ZCMCF*(IZONE-1)+23)
        WRITE (IFM,1070) '<INUTILISE>     ',ZR(JCMCF+ZCMCF*(IZONE-1)+24)
 320  CONTINUE  
C
 1070 FORMAT (' <CONTACT> ...... PARAM. : ',A16,'VAL. : ',E12.5) 
 1020 FORMAT (' <CONTACT> ...... PARAM. : ',A16,'VAL. : ',I5) 
C
C --- NOEUDS/MAILLES EXCLUS SPECIFIQUES
C
      WRITE (IFM,*) '<CONTACT> ... NOEUDS/MAILLES EXCLUS SPECIFIQUES'
      DO 800 IZONE = 1,NZOCO
C
        WRITE (IFM,*) '<CONTACT> ...... ZONE : ',IZONE 
C              
        NRACC  = ZI(JPRACC+IZONE) - ZI(JPRACC+IZONE-1)
        IF (NRACC.EQ.0) THEN
          WRITE (IFM,*) '<CONTACT> ...... PAS DE NOEUDS DE TYPE '//
     &                  'GROUP_NO_RACC A EXCLURE'
        ELSE
          WRITE (IFM,*) '<CONTACT> ...... NOMBRE DE NOEUDS DE TYPE '//
     &                 'GROUP_NO_RACC A EXCLURE: ',NRACC
C        
          JDEC = ZI(JPRACC+IZONE-1)
          DO 801 INO = 1,NRACC
            NUMRAC = ZI(JRACC+JDEC+INO-1)
            CALL JENUNO(JEXNUM(NOEUMA,NUMRAC),ZK8(JNOMNO+INO-1))
  801     CONTINUE   
C  
          WRITE (IFM,1040) '     LISTE DES NOEUDS  : '
          WRITE (IFM,1050) (ZK8(JNOMNO+INO-1), INO = 1,NRACC)          
        ENDIF
C
        NFOND  = ZI(JPBARS+IZONE) - ZI(JPBARS+IZONE-1)
        IF (NFOND.EQ.0) THEN
          WRITE (IFM,*) '<CONTACT> ...... PAS DE NOEUDS DE TYPE '//
     &                  'GROUP_NO_FOND A EXCLURE'
        ELSE
          WRITE (IFM,*) '<CONTACT> ...... NOMBRE DE NOEUDS DE TYPE '//
     &                 'GROUP_NO_FOND A EXCLURE: ',NFOND
C        
          JDEC = ZI(JPBARS+IZONE-1)
          DO 802 INO = 1,NFOND
            NUMFON = ZI(JBARS+JDEC+INO-1)
            CALL JENUNO(JEXNUM(NOEUMA,NUMFON),ZK8(JNOMNO+INO-1))
  802     CONTINUE   
C  
          WRITE (IFM,1040) '     LISTE DES NOEUDS  : '
          WRITE (IFM,1050) (ZK8(JNOMNO+INO-1), INO = 1,NFOND)
        ENDIF  
C
        NFOND  = ZI(JPBARM+IZONE) - ZI(JPBARM+IZONE-1)
        IF (NFOND.EQ.0) THEN
          WRITE (IFM,*) '<CONTACT> ...... PAS DE MAILLES DE TYPE '//
     &                  'GROUP_MA_FOND A EXCLURE'
        ELSE
          WRITE (IFM,*) '<CONTACT> ...... NOMBRE DE MAILLES DE TYPE '//
     &                 'GROUP_MA_FOND A EXCLURE: ',NFOND
C        
          JDEC = ZI(JPBARM+IZONE-1)
          DO 803 IMA = 1,NFOND
            NUMFON = ZI(JBARM+JDEC+IMA-1)
            CALL JENUNO(JEXNUM(MAILMA,NUMFON),ZK8(JNOMMA+IMA-1))
  803     CONTINUE   
C  
          WRITE (IFM,1040) '     LISTE DES MAILLES : '
          WRITE (IFM,1050) (ZK8(JNOMMA+IMA-1), IMA = 1,NFOND)      
C                  
        ENDIF
C        
 
 800  CONTINUE
C
 1040 FORMAT (' <CONTACT> ...... ',A25)       
 1050 FORMAT ((' <CONTACT> ...... ',17X,4(A8,1X)))    
C
C --- MENAGE
C
      CALL JEDETR('&&SURFC2.TRAVNO')
      CALL JEDETR('&&SURFC2.TRAVMA')      
C      
 999  CONTINUE
      CALL JEDEMA
      END
