# coding=utf-8

"""
Build some data files (dest: share/aster)

- 'profile.sh': environment script
- 'config.txt': needed by as_run
"""

import sys
import os
import os.path as osp
from itertools import chain
from waflib import Task, TaskGen, Utils

def options(self):
    group = self.get_option_group("Code_Aster options")
    # default=False in libaster, True in Code_Aster
    group.add_option('--legacy', dest='legacy',
                    default=True, action='store_true',
                    help='create some legacy files')
    group.add_option('--nolegacy', dest='legacy',
                    action='store_false',
                    help='do not create legacy files')

def configure(self):
    self.add_os_flags('ADDMEM')
    self.env.legacy = self.options.legacy

def build(self):
    if not self.env.legacy:
        return
    src = osp.dirname(self.path.abspath())
    dict_conv = _env2dict(self, src, self.env, self.env.install_tests)
    self(
        features = 'subst',
            name = 'data_files',
          source = ('config.txt.tmpl', 'profile.sh.tmpl'),
          target = ('config.txt', 'profile.sh'),
    install_path = '${ASTERDATADIR}',
            vars = ['PREFIX', 'DEFINES', 'PYTHON', 'ADDMEM',
                    'FC', 'FCFLAGS',
                    'LIBPATH', 'LIBDIR', 'CFG_PYTHONPATH', 'astervers',
                    'ASTERDATADIR', 'ASTERLIBDIR', 'OPT_ENV', 'install_tests',
                    'MFRONT_SPECIFIC'],
     **dict_conv
    )

def _env2dict(self, src, env, install_tests):
    """build dict informations"""
    env = env.derive()
    env['LD_LIBRARY_PATH'] = os.environ.get('LD_LIBRARY_PATH', '').split(os.pathsep)
    ld_path = self.remove_duplicates(chain(*[Utils.to_list(env[name])
                for name in ('LIBPATH', 'LIBDIR', 'LD_LIBRARY_PATH',
                             'ASTERLIBDIR') if env[name]]))
    sep = os.pathsep + '\\\n'
    dico = {}
    dico['DEFINES'] = ' '.join([d.split('=')[0] for d in env['DEFINES']])
    py_path = self.remove_duplicates(Utils.to_list(env['CFG_PYTHONPATH']))
    dico['PYTHONHOME'] = sys.prefix + '' if sys.prefix == sys.exec_prefix \
                                         else ':' + sys.exec_prefix
    dico['PYTHON_DIRNAME'] = osp.dirname(env['PYTHON'][0])
    # as_run compatibility
    if env.ASRUN_MPI_VERSION:
        dico['DEFINES'] += ' _USE_MPI'
    dico['LD_LIBRARY_PATH'] = sep.join(ld_path)
    dico['CFG_PYTHONPATH'] = sep.join(py_path)
    dico['SRC'] = src
    dico['FC'] = env['FC']
    flags = [' '.join(env[i]) for i in env.keys() if i.startswith('FCFLAGS')]
    dico['FCFLAGS'] = ' '.join(flags)
    dico['OPT_ENV'] = env['OPT_ENV'] and os.linesep.join(env['OPT_ENV']) or ''
    try:
        addmem = env['ADDMEM']
        if addmem and type(addmem) in (list, tuple):
            addmem = addmem[0]
        env['ADDMEM'] = int(addmem)
    except TypeError:
        env['ADDMEM'] = 250
    dico['ADDMEM'] = env['ADDMEM']
    srctest_tmpl = """SRCTEST        | src     | -     | %s"""
    if install_tests:
        dico['srctest'] = srctest_tmpl % '$ASTER_VERSION_DIR/tests'
    else:
        dico['srctest'] = os.linesep.join([
            srctest_tmpl % '%(SRC)s/astest' % dico,
            srctest_tmpl % '%(SRC)s/../validation/astest' % dico])
    text = ""
    if env['MFRONT']:
        tfel = osp.dirname( osp.dirname(env['MFRONT']) )
        text += os.linesep.join([
            "# MFront specific",
            "export TFELHOME={}".format( tfel ),
            "export PATH=${TFELHOME}/bin:$PATH"
        ])
    dico['MFRONT_SPECIFIC'] = text
    return dico
