      SUBROUTINE DHSJF(INTSN,EPAIS,VECTG,VECTT,DVECTG,HSF,DHSF,DHSJ1F)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ELEMENTS  DATE 03/07/2012   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
      IMPLICIT NONE
      INTEGER INTSN
      REAL*8 DVECTG(2,3),DJM1(3,3)
      REAL*8 VECTG(2,3),VECTT(3,3),MATJ(3,3),JM1(3,3),EPAIS,DETJ
      REAL*8 HSF(3,9),DHSF(3,9),DHSJ1F(3,9)
C
C     CONSTRUCTION DE J-1 AUX PTS DE GAUSS NORMAL.    J = JACOBIEN
C
C-----------------------------------------------------------------------
      INTEGER I ,J ,J1 ,JB ,K ,K1 
C-----------------------------------------------------------------------
      CALL JACBM1(EPAIS,VECTG,VECTT,MATJ,JM1,DETJ)
      CALL DJACBM(EPAIS,VECTG,VECTT,DVECTG,DJM1)
C
      DO 10 JB=1,3
      DO 20  I=1,3
      DO 30  J=1,3
         J1=J+3*(JB-1)
         DHSJ1F(I,J1)=0.D0
      DO 40 K=1,3
         K1=K+3*(JB-1)
         DHSJ1F(I,J1)=DHSJ1F(I,J1)+HSF(I,K1)*DJM1(K,J)
     &                            +DHSF(I,K1)*JM1(K,J)
 40   CONTINUE
 30   CONTINUE
 20   CONTINUE
 10   CONTINUE
C
      END
