      SUBROUTINE FCEPAI(ZR)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ELEMENTS  DATE 25/02/98   AUTEUR SABJLMA P.LATRUBESSE 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 ZR(*),VF(3)
C
C---  DEFINITION DES 3 POINTS DE D'INTEGRATION SUR L'EPAISSEUR DE LA
C---  COUCHE
C
         J=1500
C
         ZR(J+1)= -1.D0
         ZR(J+2)=  0.D0
         ZR(J+3)=  1.D0
C
C     DEFINITION DES 3 POIDS DE NEWTON-COTES CORRESPONDANTS
C
         ZR(J+4)=  0.333333333333333D0
         ZR(J+5)=  1.333333333333333D0
         ZR(J+6)=  0.333333333333333D0
C
C     VALEURS DES 3 PARABOLES (POUR LA DISTRIBUTION DE LA TEMPERATURE)
C     AUX 3 PTS DE D'INTEGRATION PRECEDANTS
C
         DO 100 I=1,3
            XI3=ZR(J+I)
C
            VF(1)= 1-XI3*XI3
            VF(2)=-XI3*(1-XI3)/2.D0
            VF(3)= XI3*(1+XI3)/2.D0
C
            LL=3*(I-1)
         DO 110 L=1,3
            I1=6+LL+L
         ZR(J+I1)=VF(L)
 110     CONTINUE
 100     CONTINUE
C
      END
