      SUBROUTINE TE0547(OPTION,NOMTE)
      IMPLICIT NONE
      CHARACTER*16 OPTION,NOMTE
C     ----------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ELEMENTS  DATE 29/09/2006   AUTEUR VABHHTS J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2002  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================

      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C --------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ---------------------
      INTEGER NBCOU,NPGH,NBSECT,NBFIBR,NBVARI,JCOMPO,JDCEL,JNBSP,ITAB(2)
      INTEGER IRET


      CALL JEVECH('PDCEL_I','E',JDCEL)


C     PCOMPOR CONTIENT 1 SEULE CMP : NBVARI
C     ET LES AUTRES INFO VIENNENT DE PNBSP_I
C     SI PCOMPOR N'EST PAS FOURNI : NCMP_DYN = 0
C     ------------------------------------------------
      CALL TECACH('ONN','PCOMPOR',2,ITAB,IRET)
      IF (ITAB(1).NE.0) THEN
        IF (ITAB(2).NE.1) CALL U2MESS('F','CALCULEL_2')
        JCOMPO=ITAB(1)
        READ (ZK16(JCOMPO-1+1),'(I16)') NBVARI
      ELSE
        NBVARI=0
      END IF


C     PNBSP_I  CONTIENT LES INFOS NECESSSAIRES AU CALCUL
C     DU NOMBRE DE SOUS-POINTS.
C     SI LE CHAMP N'EST PAS DONNE, NBSPT=1
C     (VARI_ELNO_TUYO PAR EXEMPLE)
C     -----------------------------------------------------
      CALL TECACH('NNN','PNBSP_I',1,JNBSP,IRET)

C   PLUS LES 4 VARIABLES DU GRADIENT ET DU LAPLACIEN
      ZI(JDCEL-1+1) = 1
      ZI(JDCEL-1+2) = NBVARI+4


      END
