      SUBROUTINE TE0598(OPTION,NOMTE)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ELEMENTS  DATE 29/04/2013   AUTEUR SFAYOLLE S.FAYOLLE 
C ======================================================================
C COPYRIGHT (C) 1991 - 2013  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE SFAYOLLE S.FAYOLLE
      IMPLICIT NONE
      INCLUDE 'jeveux.h'

      CHARACTER*16 OPTION,NOMTE
C ----------------------------------------------------------------------
C FONCTION REALISEE:  CALCUL DE L'OPTION FORC_REFE POUR LES ELEMENTS
C                     INCOMPRESSIBLES A 2 CHAMPS UP
C                     EN 3D/D_PLAN/AXI
C
C    - ARGUMENTS:
C        DONNEES:      OPTION       -->  OPTION DE CALCUL
C                      NOMTE        -->  NOM DU TYPE ELEMENT
C ----------------------------------------------------------------------

      LOGICAL      LTEATT
      INTEGER      NDIM,NNO1,NNO2,NNOS,NPG,JGN,NTROU
      INTEGER      IW,IVF1,IVF2,IDF1,IDF2
      INTEGER      VU(3,27),VG(27),VP(27),VPI(3,27)
      INTEGER      IGEOM,IVECTU,ICOMPO
      REAL*8       SIGREF,EPSREF
      CHARACTER*8  LIELRF(10),TYPMOD(2)
      CHARACTER*24 VALK
C ----------------------------------------------------------------------


C - FONCTIONS DE FORMES ET POINTS DE GAUSS
      CALL ELREF2(NOMTE,10,LIELRF,NTROU)
      CALL ASSERT(NTROU.GE.2)
      CALL ELREF4(LIELRF(2),'RIGI',NDIM,NNO2,NNOS,NPG,IW,IVF2,IDF2,JGN)
      CALL ELREF4(LIELRF(1),'RIGI',NDIM,NNO1,NNOS,NPG,IW,IVF1,IDF1,JGN)

C - TYPE DE MODELISATION
      IF (NDIM.EQ.2 .AND. LTEATT(' ','AXIS','OUI')) THEN
        TYPMOD(1) = 'AXIS  '
      ELSE IF (NDIM.EQ.2 .AND. LTEATT(' ','D_PLAN','OUI')) THEN
        TYPMOD(1) = 'D_PLAN  '
      ELSE IF (NDIM .EQ. 3) THEN
        TYPMOD(1) = '3D'
      ELSE
        CALL U2MESK('F','ELEMENTS_34',1,NOMTE)
      END IF

C - ACCES AUX COMPOSANTES DU VECTEUR DDL
      CALL NIINIT(NOMTE,TYPMOD,NDIM,NNO1,0,NNO2,0,VU,VG,VP,VPI)

      CALL JEVECH('PGEOMER','L',IGEOM)
      CALL JEVECH('PVECTUR','E',IVECTU)
      CALL JEVECH('PCOMPOR','L',ICOMPO)
      CALL TEREFE('SIGM_REFE','MECA_INCO',SIGREF)
      CALL TEREFE('EPSI_REFE','MECA_INCO',EPSREF)

C - CALCUL DE REFE_FORC_NODA
      IF (ZK16(ICOMPO+2) (1:6).EQ.'PETIT ') THEN

        IF (.NOT.LTEATT(' ','INCO','C2PD')) THEN
          VALK = ZK16(ICOMPO+2)
          CALL U2MESK('F','MODELISA10_17', 1 ,VALK)
        END IF

        CALL NURFPD(NDIM,NNO1,NNO2,NPG,IW,ZR(IVF1),ZR(IVF2),IDF1,
     &              VU,VP,TYPMOD,ZR(IGEOM),SIGREF,EPSREF,ZR(IVECTU))
      ELSEIF (ZK16(ICOMPO+2) (1:8).EQ.'GDEF_LOG') THEN

        IF (.NOT.LTEATT(' ','INCO','C2LG')) THEN
          VALK = ZK16(ICOMPO+2)
          CALL U2MESK('F','MODELISA10_17', 1 ,VALK)
        END IF

        CALL NURFGD(NDIM,NNO1,NNO2,NPG,IW,ZR(IVF1),ZR(IVF2),IDF1,
     &              VU,VP,TYPMOD,ZR(IGEOM),SIGREF,EPSREF,ZR(IVECTU))
      ELSE
        CALL U2MESK('F','ELEMENTS3_16',1,ZK16(ICOMPO+2))
      END IF

      END
