      SUBROUTINE ZEROP2(B,C,X,N)

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ELEMENTS  DATE 20/07/98   AUTEUR GJBHHEL E.LORENTZ 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================

      IMPLICIT NONE
      REAL*8  B,C,X(2)
      INTEGER N

C ----------------------------------------------------------------------
C RESOLUTION D'UN POLYNOME DE DEGRE 2 : X**2 + B X + C = 0
C ----------------------------------------------------------------------
C IN  B,C   COEFFICIENTS DU POLYNOME
C OUT X     RACINES DANS L'ORDRE DECROISSANT
C OUT N     NOMBRE DE RACINES
C ----------------------------------------------------------------------

      REAL*8 DELTA, RAC

      DELTA = B**2 - 4*C
      IF (DELTA.LT.0) THEN
        N = 0
      ELSE
        N = 2
        RAC = SQRT(DELTA)
        X(1) = (-B+RAC)/2
        X(2) = (-B-RAC)/2
      END IF

      END
