      SUBROUTINE CFCONV(NOMA  ,DEFICO,RESOCO,SOLALG,CVNEWT,
     &                  CTCFIX,CTDCVG,GEONOE,GEOVAL)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 17/10/2011   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2011  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE ABBAS M.ABBAS
C
      IMPLICIT     NONE
      CHARACTER*8  NOMA
      CHARACTER*24 DEFICO,RESOCO
      LOGICAL      CVNEWT,CTCFIX,CTDCVG
      CHARACTER*19 SOLALG(*)
      CHARACTER*16 GEONOE
      REAL*8       GEOVAL
C
C ----------------------------------------------------------------------
C
C ROUTINE CONTACT (METHODES DISCRETES)
C
C CONVERGENCE LIEE AU CONTACT DISCRET
C
C ----------------------------------------------------------------------
C
C
C IN  DEFICO : SD POUR LA DEFINITION DU CONTACT
C IN  RESOCO : SD POUR LA RESOLUTION DU CONTACT
C IN  NOMA   : NOM DU MAILLAGE
C IN  SOLALG : VARIABLE CHAPEAU POUR INCREMENTS SOLUTIONS
C IN  CVNEWT : .TRUE. SI CONVERGENCE AU SENS DE NEWTON
C OUT CTCFIX : VAUT .TRUE. SI POINT FIXE
C OUT CTDCVG : VAUT .TRUE. SI CONTACT CONVERGE
C OUT GEONOE : ENDROIT POUR MAX GEOMETRIE 
C OUT GEOVAL : VALEUR DU MAX GEOMETRIE
C
C --------------- DEBUT DECLARATIONS NORMALISEES JEVEUX ----------------
C
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C
C -------------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ----------------
C
      LOGICAL      CFDISL,LALLV
      CHARACTER*24 CLREAC
      INTEGER      JCLREA
      LOGICAL      CTCGEO
C 
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
C --- INITIALISATIONS
C
      CTCFIX = .FALSE.
      CTDCVG = .FALSE.
      CTCGEO = .TRUE.
C
C --- ACCES SD CONTACT
C
      CLREAC = RESOCO(1:14)//'.REAL'      
C
C --- FONCTIONNALISTES ACTIVEES
C
      LALLV  = CFDISL(DEFICO,'ALL_VERIF')
C
C --- CONVERGENCE
C   
      IF (LALLV) THEN
        CTDCVG = .TRUE.
      ELSE
C
        CALL JEVEUO(CLREAC,'E',JCLREA)
C
C ----- ATTENTE POINT FIXE ?
C
        CTCFIX = ZL(JCLREA+2-1)
C
C ----- EVALUATION DE LA REACUALISATION GEOMETRIQUE POUR CONTACT DISCRET
C
        IF (CVNEWT) THEN
          IF (.NOT.CTCFIX) THEN
            CALL CFCGEO(NOMA  ,DEFICO,RESOCO,SOLALG,CTCGEO,
     &                  GEONOE,GEOVAL)
            ZL(JCLREA+1-1) = .NOT.CTCGEO
          ENDIF
          CTDCVG = (.NOT.CTCFIX)
        ELSE
          CTDCVG = .FALSE.
        ENDIF
        CTDCVG = CTDCVG.AND.CTCGEO
      ENDIF
C
      CALL JEDEMA()
      END
