      SUBROUTINE CFDISM(DEFICO,LDPOU ,LDCOQ ,POSNOE,DISTST)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 13/06/2012   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE ABBAS M.ABBAS
C 
      IMPLICIT     NONE
      INCLUDE 'jeveux.h'
      CHARACTER*24 DEFICO
      INTEGER      POSNOE
      REAL*8       DISTST
      LOGICAL      LDPOU,LDCOQ
C      
C ----------------------------------------------------------------------
C
C ROUTINE CONTACT (METHODES MAILLEES - APPARIEMENT)
C
C CALCUL DU JEU SUPPLEMENTAIRE POUR POUTRE/COQUE
C SUR UN NOEUD ESCLAVE DONNE
C
C ----------------------------------------------------------------------
C
C
C IN  DEFICO : SD POUR LA DEFINITION DE CONTACT
C IN  POSNOE : INDICE DU NOEUD ESCLAVE DANS CONTNO
C IN  LDPOU  : SI DIST_POUTRE
C IN  LDCOQ  : SI DIST_COQUE
C OUT DISTST : JEU SUPPLEMENTAIRE DU AUX POUTRES/COQUES
C
C
C
C
C
      CHARACTER*24 JEUPOU,JEUCOQ
      INTEGER      JJPOU,JJCOQ
      INTEGER      NTMAE,JDECIV,IMAE,POSMAE
      REAL*8       DISTMA
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
C --- LECTURE DES SD POUR LE CONTACT POTENTIEL
C
      JEUCOQ = DEFICO(1:16)//'.JEUCOQ'
      JEUPOU = DEFICO(1:16)//'.JEUPOU' 
C        
      CALL JEVEUO(JEUPOU,'L',JJPOU )
      CALL JEVEUO(JEUCOQ,'L',JJCOQ )              
C
C --- INITIALISATIONS
C
      DISTMA = 0.D0     
C
C --- NOMBRE DE MAILLES ATTACHEES AU NOEUD 
C --- DECALAGE POUR ACCES AU TABLEAU
C   
      CALL CFNBEN(DEFICO,POSNOE,'CONINV',NTMAE ,JDECIV)    
C
C --- BOUCLE SUR LES MAILLES MAITRES 
C 
      DO 50 IMAE = 1,NTMAE    
        CALL CFINVM(DEFICO,JDECIV,IMAE  ,POSMAE)
        IF (LDPOU) THEN
          DISTMA = DISTMA+ZR(JJPOU-1+POSMAE)
        ENDIF        
        IF (LDCOQ) THEN
          DISTMA = DISTMA+ZR(JJCOQ-1+POSMAE)
        ENDIF           
  50  CONTINUE           
C
C --- MOYENNE SIMPLE
C
      DISTST = DISTMA/NTMAE      
C
      CALL JEDEMA ()
      END
