      SUBROUTINE IMPLEC(FONACT,SDSUIV,ZDEF  ,COLACT,NCOL  ,
     &                  UNITE )
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 21/12/2010   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2010  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE ABBAS M.ABBAS
C
      IMPLICIT NONE
      CHARACTER*24 SDSUIV
      INTEGER      FONACT(*)
      INTEGER      ZDEF,NCOL,UNITE
      CHARACTER*19 COLACT
C
C ----------------------------------------------------------------------
C
C ROUTINE MECA_NON_LINE (AFFICHAGE)
C
C LECTURE MOT_CLEF
C
C ----------------------------------------------------------------------
C
C
C IN  SDSUIV : NOM DE LA SD POUR LE SUIVI
C IN  FONACT : FONCTIONNALITES ACTIVEES (VOIR NMFONC)
C IN  ZDEF   : NOMBRE MAXI DE COLONNES DISPONIBLES POUR L'AFFICHAGE
C OUT NCOL   : NOMBRE DE COLONNES ACTIVES
C OUT COLACT : VECTEUR D'ACTIVATION DES COLONNES
C OUT UNITE  : UNITE DU FICHIER POUR AFFICHAGE TABLEAU EN PLUS DE .MESS
C
C -------------- DEBUT DECLARATIONS NORMALISEES JEVEUX -----------------
C
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C
C ---------------- FIN DECLARATIONS NORMALISEES JEVEUX -----------------
C
      INTEGER      I,NBOCC,ICOL,NBCOL
      CHARACTER*16 MOTFAC
      LOGICAL      LINFRE,LUNITE
      INTEGER      NBSUIV
      CHARACTER*16 TYPM(40)
      CHARACTER*9  COLONN
C      
C ----------------------------------------------------------------------
C      
      CALL JEMARQ()
C
C --- INITIALISATIONS
C
      MOTFAC = 'AFFICHAGE'
      ICOL   = 1
      NCOL   = 0
      UNITE  = 0
C
      IF (ZDEF.NE.40) THEN
        CALL ASSERT(.FALSE.)
      ENDIF
C
C --- CREATION SD AFFICHAGE - PREPARATION
C
      CALL IMPIN0(SDSUIV,ZDEF  ,MOTFAC,COLACT,NBSUIV,
     &            LINFRE,UNITE )
      LUNITE = UNITE.NE.0
C
C --- NOMBRE D'OCCURRENCES DU MOT-CLEF FACTEUR DANS *_NON_LINE
C
      CALL GETFAC(MOTFAC,NBOCC)
      CALL ASSERT(NBOCC.LE.1) 
C
C --- CAS STANDARD
C
      CALL IMPSTD(FONACT,LINFRE,LUNITE,ZDEF  ,COLACT,
     &            ICOL  )
C
C --- SUIVIS EN TEMPS REEL
C
      CALL IMPSUI(NBSUIV,ZDEF  ,COLACT,ICOL  ) 
C
C --- NOMBRE DE COLONNES ACTIVES
C
      NCOL  = ICOL - 1
      CALL ASSERT(NCOL.LE.ZDEF)
C      
      IF (NCOL.GT.16) THEN
        CALL U2MESS('F','MECANONLINE3_1')
      ENDIF   
C
      CALL JEDEMA()

      END
