      FUNCTION LCINE2(D,GM,PM,C,DGAMMA,ALPHAM,X)
      IMPLICIT NONE
      REAL*8 D,GM,PM,C,DGAMMA,ALPHAM,ABSDGA,LCINE2,X,ALPHA,SIGNE
      REAL*8 R8PREM
C RESPONSABLE JMBHH01 J.M.PROIX
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 26/04/2011   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2011  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C ======================================================================
      ABSDGA=ABS(DGAMMA)
      LCINE2=X*(1.D0+D*ABSDGA)+D*ALPHAM*ABSDGA-DGAMMA
      ALPHA=ALPHAM+X
      IF (ABS(ALPHA).GT.R8PREM()) THEN
         SIGNE=ALPHA/ABS(ALPHA)
         LCINE2=LCINE2+((C*ABS(ALPHA)/GM)**PM)*SIGNE
      ENDIF
      END
