        SUBROUTINE LCJPLC ( FAMI,KPG,KSP,LOI  ,MOD , NMAT, MATER,
     &            TIMED, TIMEF, COMP,NBCOMM, CPMONO, PGL,TOUTMS,HSR,
     &            NR,NVI,EPSD,DEPS,ITMAX,TOLER,SIGF,VINF,SIGD,VIND,
     &                   DSDE, DRDY, OPTION, IRET )
        IMPLICIT NONE
C       ================================================================
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 28/03/2007   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C TOLE CRP_21
C       ----------------------------------------------------------------
C       MATRICE SYMETRIQUE DE COMPORTEMENT TANGENT ELASTO-PLASTIQUE OU
C       VISCO-PLASTIQUE COHERENT A T+DT OU T
C       COHERENT A T+DT OU T
C       IN  FAMI   :  FAMILLE DES POINTS DE GAUSS
C           KPG    :  NUMERO DU POINT DE GAUSS
C           KSP    :  NUMERO DU SOUS POINT DE GAUSS
C           LOI    :  MODELE DE COMPORTEMENT
C           MOD    :  TYPE DE MODELISATION
C           NMAT   :  DIMENSION MATER
C           MATER  :  COEFFICIENTS MATERIAU
C       OUT DSDE   :  MATRICE DE COMPORTEMENT TANGENT = DSIG/DEPS
C       ----------------------------------------------------------------
        INTEGER         KPG,KSP,NMAT , NR, NVI, ITMAX, IRET
        REAL*8          DSDE(6,6),EPSD(*),DEPS(*),TOLER
        REAL*8          MATER(NMAT,2)
        REAL*8 TOUTMS(5,24,6),HSR(5,24,24)
        CHARACTER*(*)   FAMI
        CHARACTER*8     MOD
        CHARACTER*16    LOI,OPTION

      INTEGER         NBCOMM(NMAT,3)
      REAL*8  SIGF(*),SIGD(*),VIND(*),VINF(*),TIMED,TIMEF,PGL(3,3)
      REAL*8  DRDY(NR,NR)
      CHARACTER*16    CPMONO(5*NMAT+1),COMP(*)
C       ----------------------------------------------------------------
       IRET=0
         IF     ( LOI(1:9) .EQ. 'VISCOCHAB' ) THEN
            CALL  CVMJPL (MOD,NMAT,MATER,
     &        TIMED, TIMEF,EPSD,DEPS,SIGF,VINF,SIGD,VIND,NVI,NR,DSDE)
         ELSEIF ( LOI(1:5) .EQ. 'LMARC'     ) THEN
            CALL  LMAJPL (MOD,NMAT,MATER,
     &            TIMED, TIMEF,SIGF,VINF,SIGD,VIND,NVI,NR,DSDE)
         ELSEIF ( LOI(1:8) .EQ. 'MONOCRIS'     ) THEN
            CALL  LCMMJP (FAMI,KPG,KSP,MOD,NMAT,MATER,
     &          TIMED, TIMEF, COMP,NBCOMM, CPMONO, PGL,TOUTMS,HSR,
     &                  NR,NVI,ITMAX,TOLER,SIGF,VINF,SIGD,VIND,
     &                   DSDE , DRDY, OPTION, IRET)
         ENDIF
C
         END
