      SUBROUTINE LISLIC(NOMO  ,PREFOB,INDXCH,LIGCAL)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 13/06/2012   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
      IMPLICIT     NONE
      INCLUDE 'jeveux.h'
      CHARACTER*8  NOMO
      CHARACTER*13 PREFOB
      INTEGER      INDXCH
      CHARACTER*19 LIGCAL
C
C ----------------------------------------------------------------------
C
C ROUTINE UTILITAIRE (LISTE_CHARGES)
C
C RETOURNE LE LIGREL SUR LEQUEL ON FAIT LE CALCUL
C
C ----------------------------------------------------------------------
C
C
C IN  MODELE : NOM DU MODELE
C IN  PREFOB : PREFIXE DE L'OBJET DE LA CHARGE
C IN  INDXCH : INDICE DU TYPE DE CHARGE
C OUT LIGCAL : NOM DU LIGREL SUR LEQUEL ON FAIT LE CALCUL
C
C
C
C
      CHARACTER*6  TYPLIG
      INTEGER      IBID
      CHARACTER*19 LIGRMO
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
      CALL LISDEF('LIGC',' ',INDXCH,TYPLIG,IBID  )
      LIGRMO = NOMO(1:8)//'.MODELE'
      IF (TYPLIG.EQ.'LIGRMO') THEN
        LIGCAL = LIGRMO
      ELSEIF (TYPLIG.EQ.'LIGRCH') THEN
        LIGCAL = PREFOB//'.LIGRE'
      ELSE
        CALL ASSERT(.FALSE.)
      ENDIF

C
      CALL JEDEMA()
      END
