      SUBROUTINE LISOPT(PREFOB,NOMO  ,TYPECH,INDXCH,OPTION,
     &                  PARAIN,PARAOU,CARTE ,LIGCAL)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 17/01/2012   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
      IMPLICIT     NONE
      INTEGER      INDXCH
      CHARACTER*8  NOMO
      CHARACTER*16 OPTION
      CHARACTER*19 CARTE,LIGCAL
      CHARACTER*8  PARAIN,PARAOU
      CHARACTER*8  TYPECH
      CHARACTER*13 PREFOB
C
C ----------------------------------------------------------------------
C
C ROUTINE UTILITAIRE (LISTE_CHARGES)
C
C CREATION OBJETS CONTENANT LA LISTE DES CHARGES POUR LE GENRE DONNE
C
C ----------------------------------------------------------------------
C
C
C IN  NOMO   : NOM DU MODELE
C IN  PREFOB : PREFIXE DE L'OBJET DE LA CHARGE
C IN  TYPECH : TYPE DE LA CHARGE
C IN  INDXCH : INDICE DU TYPE DE CHARGE
C OUT OPTION : NOM DE L'OPTION DE CALCUL
C OUT CARTE  : NOM DE LA CARTE
C OUT PARAIN : NOM DU PARAMETRE D'ENTREE
C OUT PARAOU : NOM DU PARAMETRE DE SORTIE
C OUT LIGCAL : NOM DU LIGREL SUR LEQUEL ON FAIT LE CALCUL
C
C -------------- DEBUT DECLARATIONS NORMALISEES  JEVEUX ----------------
C
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C
C -------------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ----------------
C
      INTEGER      IBID
      CHARACTER*24 NOMOBJ
      INTEGER      ITYPOB
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
C
      OPTION = ' '
      PARAIN = ' '
      PARAOU = ' '
      CARTE  = ' '
      LIGCAL = ' '
C
C --- OPTION DE CALCUL
C
      CALL LISDEF('OPTI',TYPECH,INDXCH,OPTION,IBID  )
C
C --- NOM DE LA CARTE
C
      CALL LISDEF('OBJE',PREFOB,INDXCH,NOMOBJ,ITYPOB)
C
C --- ON ATTEND UNE CARTE !
C
      IF (ITYPOB.EQ.1) THEN
        CARTE = NOMOBJ(1:19)
      ELSE
        CALL ASSERT(.FALSE.)
      ENDIF
C
C --- NOM DU PARAMETRE D'ENTREE
C
      CALL LISDEF('PARA',TYPECH,INDXCH,PARAIN,IBID  )
      IF (TYPECH.EQ.'COMP') THEN
        PARAOU = 'PVECTUC'
      ELSE
        PARAOU = 'PVECTUR'
      ENDIF
C
C --- LIGREL DE CALCUL
C
      CALL LISLIC(NOMO  ,PREFOB,INDXCH,LIGCAL)
C
      CALL JEDEMA()
      END
