      SUBROUTINE MMCMEM(MODELE,
     &                  DEPMOI,VITMOI,ACCMOI,DEPDEL,
     &                  LIGRCF,CARTCF,MCONEL,SCONEL)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 29/09/2006   AUTEUR VABHHTS J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
      IMPLICIT NONE
      CHARACTER*24 MODELE
      CHARACTER*8  MCONEL
      CHARACTER*8  SCONEL
      CHARACTER*19 CARTCF,LIGRCF
      CHARACTER*24 DEPMOI,DEPDEL,ACCMOI,VITMOI
C
C ----------------------------------------------------------------------
C ROUTINE APPELLEE PAR : CONLIG
C ----------------------------------------------------------------------
C
C CALCUL DES MATRICES ELEMENTAIRES ET DES SECONDS MEMBRES
C DES ELEMENTS DE CONTACT/FROTTEMENT METHODE CONTINUE
C
C IN  MODELE : NOM DU MODELE
C IN  DEPMOI : CHAM_NO DES DEPLACEMENTS A L'INSTANT PRECEDENT
C IN  VITMOI : CHAM_NO DES VITESSES A L'INSTANT PRECEDENT
C IN  ACCMOI : CHAM_NO DES ACCELERATIONS A L'INSTANT PRECEDENT
C IN  DEPDEL : INCREMENT DE DEPLACEMENT CUMULE
C IN  LIGRCF : LIGREL POUR ELEMENTS TARDIFS DE CONTACT
C IN  CARTCF : CARTE CONTENANT LES INFOS DE CONTACT
C IN  MCONEL : OBJET MATR_ELEM POUR MATRICES ELEMENTAIRES
C IN  SCONEL : OBJET VECT_ELEM POUR SECONDS MEMBRES ELEMENTAIRES
C
C -------------- DEBUT DECLARATIONS NORMALISEES  JEVEUX ----------------
C
      INTEGER            ZI
      COMMON  / IVARJE / ZI(1)
      REAL*8             ZR
      COMMON  / RVARJE / ZR(1)
      COMPLEX*16         ZC
      COMMON  / CVARJE / ZC(1)
      LOGICAL            ZL
      COMMON  / LVARJE / ZL(1)
      CHARACTER*8        ZK8
      CHARACTER*16                ZK16
      CHARACTER*24                          ZK24
      CHARACTER*32                                    ZK32
      CHARACTER*80                                              ZK80
      COMMON  / KVARJE / ZK8(1) , ZK16(1) , ZK24(1) , ZK32(1) , ZK80(1)
C
C -------------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ----------------
C
      CHARACTER*8  LPAIN(6),LPAOUT,K8BID,VECCON,VECFRO
      CHARACTER*19 CHGEOM,LCHIN(6),LCHOUT
      INTEGER      JLIRES,JLICON,JLIFRO
      LOGICAL      EXIGEO
      INTEGER      IFM,NIV
C
C ----------------------------------------------------------------------
C
      CALL JEMARQ()
      CALL INFNIV(IFM,NIV)
C
C --- AFFICHAGE
C
      IF (NIV.GE.2) THEN
        WRITE (IFM,*) '<CONTACT> CALCUL DES MATRICES ET SECONDS '//
     &                 ' MEMBRES ELEMENTAIRES'
      ENDIF
C
C --- INITIALISATIONS
C
      VECCON = '&&MMCCON'
      VECFRO = '&&MMCFRO'
C
C --- ON DETRUIT MCONEL ET SCONEL S'ILS EXISTENT
C
      CALL DETRSD('MATR_ELEM',MCONEL)
      CALL DETRSD('VECT_ELEM',SCONEL)
      CALL DETRSD('VECT_ELEM',VECCON)
      CALL DETRSD('VECT_ELEM',VECFRO)
C
C --- RECUPERATION DE LA GEOMETRIE
C
      CALL MEGEOM(MODELE,' ',EXIGEO,CHGEOM)
      IF (.NOT.EXIGEO) THEN
        CALL U2MESS('F','ALGORITH5_84')
      ENDIF
C
C --- CREATION DES LISTES DES CHAMPS IN ET OUT
C --- GEOMETRIE ET DEPLACEMENTS
C
      LPAIN(1) = 'PGEOMER'
      LCHIN(1) = CHGEOM
      LPAIN(2) = 'PDEPL_M'
      LCHIN(2) = DEPMOI
      LPAIN(3) = 'PDEPL_P'
      LCHIN(3) = DEPDEL
      LPAIN(4) = 'PCONFR'
      LCHIN(4) = CARTCF
      LPAIN(5) = 'PDEPLAR'
      LCHIN(5) = VITMOI
      LPAIN(6) = 'PCHDYNR'
      LCHIN(6) = ACCMOI
      CALL JEVEUO(DEPDEL(1:19)//'.VALE','L',JLIRES)
C
C --- CALCUL DE MCONEL: MATRICES ELEMENTAIRES
C
      CALL MEMARE('V',MCONEL(1:8),MODELE,' ',' ','RIGI_MECA')
      CALL WKVECT(MCONEL(1:8)//'.LISTE_RESU','V V K24',2,JLIRES)
C
C --- PARTIE CONTACT
C
      LPAOUT = 'PMATUUR'
      LCHOUT = MCONEL(1:8) // '.ME001'
      CALL CALCUL('S','RIGI_CONT',LIGRCF,6,LCHIN,LPAIN,1,LCHOUT,LPAOUT,
     &           'V')
      ZK24(JLIRES-1+1) = LCHOUT
C
C --- PARTIE FROTTEMENT
C
      LPAOUT = 'PMATUUR'
      LCHOUT = MCONEL(1:8) // '.ME002'
      CALL CALCUL('S','RIGI_FROT',LIGRCF,6,LCHIN,LPAIN,1,LCHOUT,LPAOUT,
     &           'V')
      ZK24(JLIRES-1+2) = LCHOUT
      CALL JEECRA(MCONEL(1:8)//'.LISTE_RESU','LONUTI',2,K8BID)
C
C --- CALCUL DE SCONEL: SECONDS MEMBRES ELEMENTAIRES
C
      CALL MEMARE('V',SCONEL,MODELE,' ',' ','CHAR_MECA')
      CALL WKVECT(SCONEL//'.LISTE_RESU','V V K24',2,JLIRES)
      CALL JEECRA(SCONEL//'.LISTE_RESU','LONUTI',2,K8BID)
      CALL MEMARE('V',VECCON,MODELE,' ',' ','CHAR_MECA')
      CALL WKVECT(VECCON//'.LISTE_RESU','V V K24',1,JLICON)
      CALL JEECRA(VECCON//'.LISTE_RESU','LONUTI',1,K8BID)
      CALL MEMARE('V',VECFRO,MODELE,' ',' ','CHAR_MECA')
      CALL WKVECT(VECFRO//'.LISTE_RESU','V V K24',1,JLIFRO)
      CALL JEECRA(VECFRO//'.LISTE_RESU','LONUTI',1,K8BID)
C
C --- PARTIE CONTACT
C
      LPAOUT = 'PVECTUR'
      LCHOUT = SCONEL // '.VE001'
      CALL CALCUL('S','CHAR_MECA_CONT',LIGRCF,6,LCHIN,LPAIN,1,LCHOUT,
     &           LPAOUT,'V')
      ZK24(JLIRES-1+1) = LCHOUT
      ZK24(JLICON)     = LCHOUT
C
C --- PARTIE FROTTEMENT
C
      LPAOUT = 'PVECTUR'
      LCHOUT = SCONEL // '.VE002'
      CALL CALCUL('S','CHAR_MECA_FROT',LIGRCF,6,LCHIN,LPAIN,1,LCHOUT,
     &           LPAOUT,'V')
      ZK24(JLIRES-1+2) = LCHOUT
      ZK24(JLIFRO)     = LCHOUT
C
      CALL JEDEMA()
      END
