      SUBROUTINE NDCENT(IGEOM,LSN,X,XLSN)
      IMPLICIT NONE 

      INTEGER       IGEOM
      REAL*8        X(3),LSN(8),XLSN
      
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 16/06/2010   AUTEUR CARON A.CARON 
C ======================================================================
C COPYRIGHT (C) 1991 - 2010  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C       CALCUL DES COORDONNEES ET DE LA LSN DU NOEUD MILIEU
C       DE LA DIAGONALE DROITE D'UN QUAD8
C
C     ENTREE
C       IGEOM    : ADRESSE DES COORDONNÉES DES NOEUDS DE L'ELT PARENT
C       LSN      : LSN DES NOEUDS DE L'ELT PARENT
C     SORTIE
C       X        : COORDONNEES DU NOEUD CENTRAL (MILIEU DE L'ARETE 2-4)
C       XLSN     : LSN DU NOEUD CENTRAL (MILIEU DE L'ARETE 2-4)
C......................................................................
C     ----- DEBUT COMMUNS NORMALISES  JEVEUX  ------------------------
      REAL*8           ZR
      COMMON  /RVARJE/ ZR(1)
C     -----  FIN  COMMUNS NORMALISES  JEVEUX  ------------------------

      INTEGER       I,IRET,NNO,NDIM,NBNOMX,IBID
      REAL*8        FF(8),XE(3)
      CHARACTER*8   ELP
      PARAMETER     (NBNOMX = 8)
C
C......................................................................

       ELP='QU8'
       CALL ELREF4(ELP,'RIGI',NDIM,NNO,IBID,IBID,IBID,IBID,IBID,IBID)

C      CALCUL DES COORDONNEES DU MILIEU DE [AB]
       DO 10 I=1,NDIM
         X(I)=(ZR(IGEOM-1+NDIM*(2-1)+I)+ZR(IGEOM-1+NDIM*(4-1)+I))/2
 10    CONTINUE 
C
C     CALCUL DE LA LSN DU MILIEU DE [AB]
      CALL REEREG('S',ELP,NNO,ZR(IGEOM),X,NDIM,XE,IRET)
      CALL ELRFVF(ELP,XE,NBNOMX,FF,NNO)

        XLSN = 0
        DO 50 I=1,NNO
          XLSN = XLSN + FF(I)*LSN(I)
 50     CONTINUE

      END
