      SUBROUTINE NMCHAP(SDSENS,SDDYNA,VALMOI,VALPLU,POUGD ,
     &                  SECMBR,DEPALG,MEELEM,VEELEM,MEASSE)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 19/12/2007   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2007  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE ABBAS M.ABBAS
C
      IMPLICIT NONE
      CHARACTER*24 SDSENS 
      CHARACTER*19 SDDYNA     
      CHARACTER*24 VALMOI(8),VALPLU(8),POUGD(8),SECMBR(8),DEPALG(8)   
      CHARACTER*8  VEELEM(30),MEELEM(8)         
      CHARACTER*19 MEASSE(8)
C 
C ----------------------------------------------------------------------
C
C ROUTINE MECA_NON_LINE (INITIALISATION)
C
C CREATION DES VARIABLES CHAPEAUX
C      
C ----------------------------------------------------------------------
C
C
C IN  SDSENS : SD SENSIBILITE
C IN  SDDYNA : SD DYNAMIQUE
C OUT VALMOI : ETAT EN T-
C OUT VALPLU : ETAT EN T+
C OUT SECMBR : CHARGEMENTS
C OUT POUGD  : INFOS POUTRES EN GRANDES ROTATIONS
C OUT DEPALG : VARIABLE CHAPEAU POUR DEPLACEMENTS
C OUT VEELEM : VECTEURS ELEMENTAIRES
C OUT MEELEM : MATRICES ELEMENTAIRES
C OUT MEASSE : MATRICES ASSEMBLEES
C
C -------------- DEBUT DECLARATIONS NORMALISEES  JEVEUX ----------------
C
      INTEGER ZI
      COMMON /IVARJE/ ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)
C
C -------------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ----------------
C
      CHARACTER*24 K24BLA   
      CHARACTER*8  K8BLA 
      CHARACTER*19 K19BLA  
      INTEGER      NRPASE,I
      INTEGER      IFM,NIV
      LOGICAL      NDYNLO  
C
      CHARACTER*8  VEFINT,VEBUDI,VEDIDO 
      CHARACTER*8  VEDIPI,VEFEDO,VEFEPI,VELAMP,VEONDE
      CHARACTER*8  VEFSDO,VEINER,VEHYST,VEMODA,VEIMPE
      CHARACTER*8  VEMASE,VESSTR,VEDIDI,VEDIRI,VEFNOD
C 
C      
      CHARACTER*24 DEPMOI,SIGMOI,VARMOI,COMMOI,VITMOI
      CHARACTER*24 ACCMOI
      CHARACTER*24 DEPPLU,SIGPLU,VARPLU,COMPLU,VITPLU
      CHARACTER*24 ACCPLU
      CHARACTER*24 DEPKM1,VITKM1,ACCKM1,ROMKM1,ROMK 
C       
      CHARACTER*24 CNFEDO,CNFEPI,CNFSDO,CNFSPI,CNDIDI
      CHARACTER*24 CNDIDO,CNDIPI,CNCINE    
C      
      CHARACTER*24 DEPOLD,DDEPLA,DEPDEL,DEPPRE(2)
C      
      CHARACTER*8  MEMASS,MEAMOR,MERIGI,MEDIRI,MESUIV,MESSTR,MEGEOM
      CHARACTER*19 MASSE ,AMORT ,RIGID ,DIRIC ,SUIVI ,SSTRU
C
      DATA DEPMOI,DEPPLU    /'&&OP0070.DEPMOI', '&&OP0070.DEPPLU'/
      DATA SIGMOI,SIGPLU    /'&&OP0070.SIGMOI', '&&OP0070.SIGPLU'/
      DATA VARMOI,VARPLU    /'&&OP0070.VARMOI', '&&OP0070.VARPLU'/
      DATA VITMOI,VITPLU    /'&&OP0070.VITMOI', '&&OP0070.VITPLU'/
      DATA ACCMOI,ACCPLU    /'&&OP0070.ACCMOI', '&&OP0070.ACCPLU'/
      DATA COMMOI,COMPLU    /'&&OP0070.COMMOI', '&&OP0070.COMPLU'/
C
      DATA DEPKM1,VITKM1    /'&&OP0070.DEPKM1', '&&OP0070.VITKM1'/
      DATA ACCKM1           /'&&OP0070.ACCKM1'/
      DATA ROMKM1,ROMK      /'&&OP0070.ROMKM1', '&&OP0070.ROMK  '/
C
      DATA CNFEDO,CNFEPI    /'&&OP0070.CNFEDO', '&&OP0070.CNFEPI'/
      DATA CNFSDO,CNFSPI    /'&&OP0070.CNFSDO', '&&OP0070.CNFSPI'/
      DATA CNDIDO,CNDIPI    /'&&OP0070.CNDIDO', '&&OP0070.CNDIPI'/
      DATA CNDIDI,CNCINE    /'&&OP0070.CNDIDI', '&&OP0070.CNCINE'/
C
      DATA DEPDEL,DDEPLA    /'&&OP0070.DEPDEL', '&&OP0070.DDEPLA'/ 
      DATA DEPOLD           /'&&OP0070.DEPOLD'/
      DATA DEPPRE           /'&&OP0070.DEPPRE0','&&OP0070.DEPPRE1'/
C      
      DATA MEMASS,MEDIRI    /'&&MEMASS','&&MEDIRI'/
      DATA MERIGI,MEAMOR    /'&&MERIGI','&&MEAMOR'/
      DATA MESUIV,MESSTR    /'&&MATGME','&SSR.ELE'/  
      DATA MEGEOM           /'&&MEGEOM'/           
      DATA AMORT ,MASSE     /'&&AMORT','&&MASSE'/
      DATA RIGID ,DIRIC     /'&&RIGID','&&DIRIC'/  
      DATA SUIVI ,SSTRU     /'&&SUIVI','&SSR.ASS'/                     
C
      DATA VEFEDO,VEFSDO    /'&&VEFEDO', '&&VEFSDO'/ 
      DATA VEDIDO,VEFEPI    /'&&VEDIDO', '&&VEFEPI'/
      DATA VEDIPI,VEFINT    /'&&VEDIPI', '&&VEFINT'/
      DATA VEBUDI           /'&&VEBUDI'/
      DATA VELAMP           /'&&VELAME'/
      DATA VEONDE,VEINER    /'&&VEONDE', '&&VEINER'/
      DATA VEHYST,VEMODA    /'&&VEHYST', '&&VEMODA'/
      DATA VEIMPE,VEMASE    /'&&VEIMPE', '&&VEMASE'/
      DATA VESSTR,VEDIDI    /'&&VESSTR', '&&VEDIDI'/  
      DATA VEDIRI,VEFNOD    /'&&VEDIRI', '&&VEFNOD'/
C      
C ----------------------------------------------------------------------
C      
      CALL JEMARQ()
      CALL INFDBG('MECA_NON_LINE',IFM,NIV)
C
C --- AFFICHAGE
C
      IF (NIV.GE.2) THEN
        WRITE (IFM,*) '<MECANONLINE> ... CREATION VARIABLES CHAPEAUX'
      ENDIF
C
C --- INITIALISATIONS
C
      K24BLA = ' '    
      K8BLA  = ' ' 
      K19BLA = ' '
C
C --- NOMS DES CHAMPS DE BASE (SANS SENSIBILITE)
C    
      NRPASE = 0
      CALL NMNSLE(SDSENS,NRPASE,'DEPPLU',DEPPLU)
      CALL NMNSLE(SDSENS,NRPASE,'DEPMOI',DEPMOI)
      CALL NMNSLE(SDSENS,NRPASE,'SIGPLU',SIGPLU)
      CALL NMNSLE(SDSENS,NRPASE,'SIGMOI',SIGMOI)
      CALL NMNSLE(SDSENS,NRPASE,'VARPLU',VARPLU)
      CALL NMNSLE(SDSENS,NRPASE,'VARMOI',VARMOI)
      IF (NDYNLO(SDDYNA,'DYNAMIQUE')) THEN
        CALL NMNSLE(SDSENS,NRPASE,'VITPLU',VITPLU)
        CALL NMNSLE(SDSENS,NRPASE,'ACCPLU',ACCPLU)
        CALL NMNSLE(SDSENS,NRPASE,'VITMOI',VITMOI)
        CALL NMNSLE(SDSENS,NRPASE,'ACCMOI',ACCMOI)        
      END IF      
C
C --- CREATIONS DES VECTEURS 
C
      CALL AGGLOM(DEPMOI,SIGMOI,VARMOI,COMMOI,
     &            VITMOI,ACCMOI,K24BLA,K24BLA, 6, VALMOI)
      CALL AGGLOM(DEPPLU,SIGPLU,VARPLU,COMPLU,
     &            VITPLU,ACCPLU,K24BLA,K24BLA, 6, VALPLU)
      CALL AGGLOM(CNFEDO,CNFEPI,CNDIDO,CNDIPI,
     &            CNFSDO,CNFSPI,CNDIDI,CNCINE, 8, SECMBR)
      CALL AGGLOM(DEPKM1,VITKM1,ACCKM1,ROMKM1,
     &            ROMK  ,K24BLA,K24BLA,K24BLA, 5, POUGD )
      CALL AGGLOM(DDEPLA,DEPDEL,DEPOLD,DEPPRE(1),
     &            DEPPRE(2),K24BLA,K24BLA,K24BLA, 5, DEPALG)     
C
C --- MATRICES ELEMENTAIRES 
C                  
      MEELEM(1) = MERIGI
      MEELEM(2) = MEDIRI
      MEELEM(3) = MEMASS
      MEELEM(4) = MEAMOR
      MEELEM(5) = MESUIV
      MEELEM(6) = MESSTR
      MEELEM(7) = MEGEOM
      MEELEM(8) = MEDIRI
C
C --- MATRICES ASSEMBLEES
C                  
      MEASSE(1) = RIGID
      MEASSE(2) = DIRIC
      MEASSE(3) = MASSE
      MEASSE(4) = AMORT
      MEASSE(5) = SUIVI
      MEASSE(6) = SSTRU
      MEASSE(7) = K19BLA
      MEASSE(8) = K19BLA
C
C --- VECTEURS ELEMENTAIRES 
C       
      DO 10 I = 1,30 
        VEELEM(I) = K8BLA          
   10 CONTINUE
      VEELEM(1)  = VEFINT 
      VEELEM(2)  = VEDIRI 
      VEELEM(3)  = VEBUDI 
      VEELEM(4)  = VEFNOD 
      VEELEM(5)  = VEDIDO 
      VEELEM(6)  = VEDIPI 
      VEELEM(7)  = VEFEDO 
      VEELEM(8)  = VEFEPI 
      VEELEM(9)  = VELAMP 
      VEELEM(10) = VEONDE 
      VEELEM(11) = VEFSDO 
      VEELEM(12) = VEINER 
      VEELEM(13) = VEHYST 
      VEELEM(14) = VEMODA 
      VEELEM(15) = VEIMPE 
      VEELEM(16) = VEMASE 
      VEELEM(17) = VESSTR 
      VEELEM(18) = VEDIDI 
      VEELEM(19) = VEFNOD 
C
      CALL JEDEMA()      
C
      END
