      SUBROUTINE NMDOSE(CARELE,NBPASE,MATERI,INPSCO)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 17/01/2012   AUTEUR ABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
      IMPLICIT      NONE
      INTEGER       NBPASE
      CHARACTER*(*) INPSCO
      CHARACTER*8   MATERI
      CHARACTER*24  CARELE
C
C ----------------------------------------------------------------------
C
C ENREGISTREMENT DU PARAMETRE SENSIBLE
C
C ----------------------------------------------------------------------
C
C
C IN  NBPASE : NOMBRE DE PARAMETRES SENSIBLES
C IN  CARELE : CARACTERISTIQUES ELEMENTAIRES
C IN  MATERI : CHAMP DE MATERIAU (NON CODE)
C I/O INPSCO : STRUCTURE CONTENANT LA LISTE DES NOMS
C
C ----------------------------------------------------------------------
C
      INTEGER      NRPASE
      INTEGER      IAUX,JAUX,IRET
      CHARACTER*8  MATERS,K8BID,NOPASE
      CHARACTER*24 MATES
C
C ----------------------------------------------------------------------
C
      DO 10 NRPASE = 1,NBPASE
C
C ----- NOM DU PARAMETRE SENSIBLE
C
        IAUX   = NRPASE
        JAUX   = 1
        CALL PSNSLE(INPSCO,IAUX  ,JAUX  ,NOPASE)
C
C ----- A-T-ON UN CHAMP DE MATERIAU DERIVE ASSOCIE A CE PARAMETRE ?
C -----   SI OUI :
C -----     . ON MEMORISE QUE LE PARAMETRE SENSIBLE IMPACTE
C -----       LES MATERIAUX
C -----     . ON CREE LE MATERIAU CODE ASSOCIE AU MATERIAU DERIVE
C
        CALL PSGENC(MATERI,NOPASE,MATERS,IRET  )
        IF (IRET.EQ.0) THEN
          CALL PSTYPA(NBPASE,INPSCO,MATERI,NOPASE,'MATERIAU')
          CALL RCMFMC(MATERS,MATES )
        ENDIF
C
C ----- A-T-ON DES CARACTERISTIQUES DERIVEES ASSOCIEES A CE PARAMETRE ?
C -----   SI OUI :
C -----    . ON MEMORISE QUE LE PARAMETRE SENSIBLE IMPACTE
C -----      LES CARACTERISTIQUES
C
        CALL PSGENC(CARELE,NOPASE,K8BID ,IRET  )
        IF (IRET.EQ.0) THEN
          CALL PSTYPA(NBPASE,INPSCO,CARELE,NOPASE,'CARAELEM')
        ENDIF
   10 CONTINUE

      END
