      SUBROUTINE PREKPR ( MODMEC, MTRMAS, NBDDL, NUMER, MAILLA, CHAMAT,
     +                    CELEM )
      IMPLICIT   NONE
      INCLUDE 'jeveux.h'
      INTEGER             NBDDL
      CHARACTER*8         MODMEC, MTRMAS, NUMER, MAILLA, CHAMAT, CELEM
C-----------------------------------------------------------------------
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 13/06/2012   AUTEUR COURTOIS M.COURTOIS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR   
C (AT YOUR OPTION) ANY LATER VERSION.                                 
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT 
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF          
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU    
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                            
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE   
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,       
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.      
C ======================================================================
C
C  BUT: RECHERCHE DES MATRICES ELEMENTAIRES POUR LA REPONSE EFFO_ELNO
C       DU CALCUL DYNAMIQUE ALEATOIRE
C
C IN  : MODMEC : CONCEPT MODE_MECA
C OUT : MTRMAS : MATRICE MASSE
C OUT : NBDDL  : NOMBRE DE DDLS DU PROBLEME
C OUT : NUMER  : CONCEPT NUMEROTATION
C OUT : MAILLA : CONCEPT MAILLAGE
C OUT : CHAMAT : CHAMP MATER
C OUT : CELEM  : CARA_ELEM
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
C
      INTEGER        IBID, IE, IAD1
      CHARACTER*8    K8B
C
C---------CONSTITUTION DE LA LISTE COMPLETE DES ET DDLS EN CAS D EFFORT
C---------RECUPERATION MODELE ET MAILLA
C
      CALL JEMARQ()
C
      CALL JEVEUO(MODMEC//'           .REFD','L',IAD1)
      MTRMAS = ZK24(IAD1+1)(1:8)
      CALL DISMOI('F','NB_EQUA'     ,MTRMAS,'MATR_ASSE',NBDDL,K8B  ,IE)
      CALL DISMOI('F','NOM_NUME_DDL',MTRMAS,'MATR_ASSE',IBID,NUMER ,IE)
      CALL DISMOI('F','NOM_MAILLA'  ,MTRMAS,'MATR_ASSE',IBID,MAILLA,IE)
      CALL DISMOI('F','CHAM_MATER'  ,MTRMAS,'MATR_ASSE',IBID,CHAMAT,IE)
      CALL DISMOI('F','CARA_ELEM'   ,MTRMAS,'MATR_ASSE',IBID,CELEM ,IE)
C
      CALL JEDEMA()
      END
