      SUBROUTINE SUIEXT(MAILLA,NBMODS,INSTAP,ITERAT,NBSUIV,
     &                  VITPLU,ACCPLU,VALPLU,DEPDEL,
     &                  SECMBR,
     &                  DEPENT,VITENT,ACCENT,CNSINR)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 24/08/2005   AUTEUR MABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2005  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
      IMPLICIT     NONE
      INTEGER      NBMODS
      CHARACTER*8  MAILLA
      REAL*8       INSTAP
      INTEGER      ITERAT
      INTEGER      NBSUIV
      CHARACTER*24 VALPLU
      CHARACTER*24 VITPLU
      CHARACTER*24 ACCPLU
      CHARACTER*24 DEPDEL
      CHARACTER*24 SECMBR(8)
      CHARACTER*24 DEPENT
      CHARACTER*24 VITENT
      CHARACTER*24 ACCENT
      CHARACTER*19 CNSINR
C
C ----------------------------------------------------------------------
C ROUTINE APPELEE PAR : OP0070
C ----------------------------------------------------------------------
C
C REALISATION D'UN SUIVI EN TEMPS REEL
C
C IN  MAILLA : NOM DU MAILLAGE
C IN  NBMODS : NOMBRE DE MODES STATIQUES
C IN  INSTAP : INSTANT COURANT
C IN  ITERAT : ITERATION COURANTE
C IN  NBSUIV : NOMBRE DE SUIVIS A FAIRE
C IN  VALPLU : VARIABLES A L'INSTANT ACTUEL (DANS CHAPEAU)
C IN  VITPLU : VITESSES A L'INSTANT ACTUEL
C IN  ACCPLU : ACCELERATIONS A L'INSTANT ACTUEL
C IN  SECMBR : SECOND MEMBRE A L'INSTANT ACTUEL (DANS CHAPEAU)
C IN  DEPENT : DEPLACEMENTS DE REFERENCE POUR LES DEPLACEMENTS ABSOLUS
C IN  VITENT : VITESSES DE REFERENCE POUR LES VITESSES ABSOLUS
C IN  ACCENT : ACCELERATIONS DE REFERENCE POUR LES ACCELERATIONS
C              ABSOLUS
C IN  CNSINR : CHAM_NO_S CONTENANT LES INFOS SUR LE CONTACT
C
C -------------- DEBUT DECLARATIONS NORMALISEES  JEVEUX ----------------
C
      INTEGER            ZI
      COMMON  / IVARJE / ZI(1)
      REAL*8             ZR
      COMMON  / RVARJE / ZR(1)
      COMPLEX*16         ZC
      COMMON  / CVARJE / ZC(1)
      LOGICAL            ZL
      COMMON  / LVARJE / ZL(1)
      CHARACTER*8        ZK8
      CHARACTER*16                ZK16
      CHARACTER*24                          ZK24
      CHARACTER*32                                    ZK32
      CHARACTER*80                                              ZK80
      COMMON  / KVARJE / ZK8(1) , ZK16(1) , ZK24(1) , ZK32(1) , ZK80(1)
C
C -------------- FIN  DECLARATIONS  NORMALISEES  JEVEUX ----------------
C
      INTEGER      IOCC,INOEUD,ICMP,VARINT,ICTC,ISND
      INTEGER      JDEPP,JVITP,JACCP,JDEPEN,JVITEN,JACCEN,JCONT,JDEPDE
      REAL*8       VALR
      CHARACTER*13 RESULT,CONCEP,NOMCMD
      CHARACTER*16 CHAM
      CHARACTER*24 K24BID
      INTEGER      KCHAM,KCOMP,KNUCM,KNOEU,KMAIL,KPOIN
      INTEGER      SUBTOP,TYPCHA
      CHARACTER*24 DEPPLU,SIGPLU,VARPLU
      CHARACTER*24 CNFEDO,CNFEPI,CNFSDO,CNFSPI
      CHARACTER*19 CNSINZ
      CHARACTER*8  CMP,TOPO
      INTEGER      IFM,NIV
C
C ----------------------------------------------------------------------
C
      CALL GETRES(RESULT,CONCEP,NOMCMD)
C
      CALL JEMARQ()
      CALL INFNIV(IFM,NIV)
C
      IF (NBSUIV.EQ.0) THEN
        GOTO 999
      ENDIF

      CALL JEVEUO ( '&&SUICMP.NOM_CHAM' , 'L' , KCHAM )
      CALL JEVEUO ( '&&SUICMP.NOM_CMP ' , 'L' , KCOMP )
      CALL JEVEUO ( '&&SUICMP.NUME_CMP' , 'L' , KNUCM )
      CALL JEVEUO ( '&&SUICMP.NOEUD'    , 'L' , KNOEU )
      CALL JEVEUO ( '&&SUICMP.MAILLE'   , 'L' , KMAIL )
      CALL JEVEUO ( '&&SUICMP.POINT'    , 'L' , KPOIN )
C
C --- SI ON DEMANDE DES DDL ABSOLUS EN STATIQUE -> ARRET
C
      IF (NOMCMD(1:13).EQ.'STAT_NON_LINE')THEN
        DO 10 IOCC = 1 , NBSUIV 
          CHAM   = ZK16(KCHAM-1+IOCC)
          IF (  CHAM(1:11) .EQ. 'DEPL_ABSOLU'.OR.
     &         CHAM(1:11) .EQ. 'VITE_ABSOLU'.OR.
     &         CHAM(1:11) .EQ. 'ACCE_ABSOLU') THEN
                 CALL UTDEBM('F','SUIEXT','ERREUR FATALE')
                 CALL UTIMPK('L','LE CHAMP',1,CHAM(1:11))
                 CALL UTIMPK('S','EST INCOMPATIBLE AVEC'//
     &            ' LE MODE ',1,NOMCMD(1:13))
                 CALL UTFINM()
          ENDIF
 10     CONTINUE
      ENDIF
C
C --- DECOMPACTION DES VARIABLES CHAPEAUX
C
      CALL DESAGG(VALPLU,DEPPLU,SIGPLU,VARPLU,K24BID,K24BID,K24BID,
     &            K24BID,K24BID)

      CALL DESAGG(SECMBR,CNFEDO,CNFEPI,K24BID,K24BID,CNFSDO,CNFSPI,
     &            K24BID,K24BID)
C
C --- RECUPERATIONS DES POINTEURS JEVEUX SUR LES CHAMPS
C
      CALL JEVEUO(DEPPLU(1:19)//'.VALE','L',JDEPP) 
      CALL JEVEUO(DEPDEL(1:19)//'.VALE','L',JDEPDE) 
      IF (NOMCMD(1:13).NE.'STAT_NON_LINE')THEN
         CALL JEVEUO(VITPLU(1:19)//'.VALE','L',JVITP) 
         CALL JEVEUO(ACCPLU(1:19)//'.VALE','L',JACCP)
         CALL JEVEUO(DEPENT(1:19)//'.VALE','L',JDEPEN)
         CALL JEVEUO(VITENT(1:19)//'.VALE','L',JVITEN)
         CALL JEVEUO(ACCENT(1:19)//'.VALE','L',JACCEN)
      ENDIF
C
C --- POUR LES FORCES NODALES
C
      ISND = 1
C
C --- POUR LE CONTACT: CONVERSION CHAM_NO EN CHAM_NO_S
C
      CALL JEEXIN(CNSINR//'.CNSV',ICTC)
      IF (ICTC.NE.0) THEN
        CNSINZ = '&&DYOBAR.CNSINZ'
        CALL CNSCNO(CNSINR,' ','NON','V',CNSINZ)
        CALL JEVEUO(CNSINZ(1:19)//'.VALE','L',JCONT)
      ENDIF
C      
      DO 20 IOCC = 1 , NBSUIV
C
C --- CHAMP
C
         CHAM   = ZK16(KCHAM-1+IOCC)
C
C --- IDENTIFICATION DU CHAMP A EXTRAIRE
C
         TYPCHA = 0
         IF     ( CHAM(1:11) .EQ. 'DEPL_ABSOLU' ) THEN
           TYPCHA = 1        
         ELSEIF ( CHAM(1:11) .EQ. 'VITE_ABSOLU' ) THEN
           TYPCHA = 2         
         ELSEIF ( CHAM(1:11) .EQ. 'ACCE_ABSOLU' ) THEN
           TYPCHA = 3         
         ELSEIF ( CHAM(1:4) .EQ. 'DEPL' ) THEN
           TYPCHA = 4         
         ELSEIF ( CHAM(1:9) .EQ. 'VALE_CONT' ) THEN
           TYPCHA = 5          
         ELSEIF ( CHAM(1:4) .EQ. 'VITE' ) THEN
           TYPCHA = 6         
         ELSEIF ( CHAM(1:4) .EQ. 'ACCE' ) THEN
           TYPCHA = 7         
         ELSEIF ( CHAM(1:9) .EQ. 'SIEF_ELGA' ) THEN
           TYPCHA = 8         
         ELSEIF ( CHAM(1:9) .EQ. 'VARI_ELGA' ) THEN
           TYPCHA = 9     
         ELSEIF ( CHAM(1:9) .EQ. 'FORC_NODA' ) THEN
           TYPCHA = 10     
         ELSE
           CALL UTMESS('F','SUIEXT','TYPE DE CHAMP INCONNU')
         ENDIF
C
C --- COMPOSANTE
C
         CMP    = ZK8(KCOMP-1+IOCC)
C
C --- ENTITE TOPOLOGIQUE PRINCIPALE (NOEUD OU MAILLE)
C --- SI MAILLE -> SOUS-ENTITE TOPOLOGIQUE  (POINT DE GAUSS)
C
         SUBTOP = 0
         IF ((TYPCHA.EQ.8).OR.(TYPCHA.EQ.9)) THEN
           TOPO   = ZK8(KMAIL-1+IOCC)
           SUBTOP = ZI(KPOIN-1+IOCC)
         ELSE
           TOPO   = ZK8(KNOEU-1+IOCC)
         ENDIF
C
C --- NUMERO DE VARIABLE INTERNE 
C
         VARINT = 0
         IF (TYPCHA.EQ.9) THEN
           VARINT  = ZI(KNUCM-1+IOCC)
         ENDIF
C
C --- DEPL, VITE ET ACCE ABSOLUS -> MODES STATIQUES ?
C
         IF ((TYPCHA.GE.1).AND.(TYPCHA.LE.3)) THEN
           IF (NBMODS.EQ.0) THEN
               GOTO 15
           ENDIF
         ENDIF
C
         CALL DYOEXT(MAILLA,TYPCHA,TOPO,SUBTOP,CMP,VARINT,
     &               DEPPLU,VITPLU,ACCPLU,SIGPLU,VARPLU,
     &               DEPENT,VITENT,ACCENT,
     &               ICTC,CNSINZ,
     &               ISND,CNFEDO,CNFEPI,CNFSDO,CNFSPI,
     &               INOEUD,ICMP,VALR)
C
         IF ((ICMP.EQ.0).OR.(INOEUD.EQ.0)) THEN
           GOTO 15
         ENDIF
C
C ---
C
         IF     (TYPCHA.EQ.1) THEN
           VALR = ZR(JDEPP+ICMP-1) + ZR(JDEPEN+ICMP-1)                  
         ELSEIF (TYPCHA.EQ.2) THEN
           VALR = ZR(JVITP+ICMP-1) + ZR(JVITEN+ICMP-1)        
         ELSEIF (TYPCHA.EQ.3) THEN
           VALR = ZR(JACCP+ICMP-1) + ZR(JACCEN+ICMP-1)      
         ELSEIF (TYPCHA.EQ.4) THEN
           VALR = ZR(JDEPP+ICMP-1)
         ELSEIF (TYPCHA.EQ.5) THEN
           VALR = ZR(JCONT+ICMP-1)          
         ELSEIF (TYPCHA.EQ.6) THEN
           VALR = ZR(JVITP+ICMP-1)       
         ELSEIF (TYPCHA.EQ.7) THEN
           VALR = ZR(JACCP+ICMP-1)          
         ELSEIF (TYPCHA.EQ.8) THEN
C          VALR = VALR
         ELSEIF (TYPCHA.EQ.9) THEN
C          VALR = VALR
         ELSEIF (TYPCHA.EQ.10) THEN
C          VALR = VALR          
         ELSE 
C           CMPINC =  .TRUE.
         ENDIF

  15     CONTINUE

    
C
 20   CONTINUE
C
 999  CONTINUE
C
      CALL JEDEMA()


      END
