      SUBROUTINE VEBUME(MODELZ,DEPLAZ,LISCHA,VECELZ)

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 23/01/2006   AUTEUR MABBAS M.ABBAS 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C RESPONSABLE MABBAS M.ABBAS

      IMPLICIT NONE
      CHARACTER*(*) VECELZ,MODELZ,DEPLAZ
      CHARACTER*8 VECELE,MODELE
      CHARACTER*19 LISCHA,DEPLA

C ----------------------------------------------------------------------
C     CALCUL DES VECTEURS ELEMENTAIRES B.U (ELEMENTS DE LAGRANGE)
C                                   ET BT.LAMBDA
C ----------------------------------------------------------------------
C IN       MODELE K8  : NOM DU MODELE
C IN       DEPLA  K19 : CHAMP DE DEPLACEMENTS
C IN       LISCHA K19 : SD L_CHARGES
C IN/JXOUT VECELZ  : VECT_ELEM RESULTAT

C --- DEBUT DECLARATIONS NORMALISEES JEVEUX ----------------------------

      CHARACTER*32 JEXNUM,JEXNOM,JEXR8,JEXATR
      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)

C --- FIN DECLARATIONS NORMALISEES JEVEUX ------------------------------

      CHARACTER*8 NOMCHA,LPAIN(2),PAOUT,K8BID,NEWNOM
      CHARACTER*16 OPTION
      CHARACTER*19 RESUEL
      CHARACTER*24 LIGRMO,LIGRCH,LCHIN(2)
      INTEGER IRET,NCHAR,ILIRES,JLVE,JCHAR,JINF,ICHA,IBID
C ----------------------------------------------------------------------


      CALL JEMARQ()
      NEWNOM='.0000000'
      VECELE = VECELZ
      MODELE = MODELZ
      DEPLA = DEPLAZ

      CALL JEEXIN(LISCHA//'.LCHA',IRET)
      IF (IRET.EQ.0) GO TO 20

      CALL JELIRA(LISCHA//'.LCHA','LONMAX',NCHAR,K8BID)
      CALL JEVEUO(LISCHA//'.LCHA','L',JCHAR)
      CALL JEVEUO(LISCHA//'.INFC','L',JINF)




C     -- ALLOCATION DU VECT_ELEM RESULTAT :
C     -------------------------------------
      CALL DETRSD('VECT_ELEM',VECELE)
      CALL MEMARE('V',VECELE,MODELE(1:8),' ',' ','CHAR_MECA')
      CALL WKVECT(VECELE//'.LISTE_RESU','V V K24',NCHAR,JLVE)
      CALL JEECRA(VECELE//'.LISTE_RESU','LONUTI',0,K8BID)


      ILIRES = 0
      DO 10 ICHA = 1,NCHAR
        IF (ZI(JINF+ICHA).LE.0) GO TO 10

        NOMCHA = ZK24(JCHAR+ICHA-1) (1:8)
        LIGRCH = NOMCHA//'.CHME.LIGRE'
        CALL JEEXIN(NOMCHA//'.CHME.LIGRE.LIEL',IRET)
        IF (IRET.LE.0) GO TO 10
        CALL EXISD('CHAMP_GD',NOMCHA//'.CHME.CMULT',IRET)
        IF (IRET.LE.0) GO TO 10

        LPAIN(1) = 'PDDLMUR'
        LCHIN(1) = NOMCHA//'.CHME.CMULT'
        LPAIN(2) = 'PDDLIMR'
        LCHIN(2) = DEPLA

        PAOUT = 'PVECTUR'
        RESUEL = '&&VEBUME.???????'
        CALL GCNCO2(NEWNOM)
        RESUEL(10:16) = NEWNOM(2:8)
        CALL CORICH('E',RESUEL,ICHA,IBID)

        OPTION = 'MECA_BU_R'
        CALL CALCUL('S',OPTION,LIGRCH,2,LCHIN,LPAIN,1,RESUEL,PAOUT,'V')
        ILIRES = ILIRES + 1
        ZK24(JLVE-1+ILIRES) = RESUEL
   10 CONTINUE
      CALL JEECRA(VECELE//'.LISTE_RESU','LONUTI',ILIRES,K8BID)

   20 CONTINUE

      CALL JEDEMA()
      END
