      SUBROUTINE VEDTEL(MODELE,CHARGE,TEMPER,THETA,DEULTG,DLAGTE)

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 11/09/2002   AUTEUR VABHHTS J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2001  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.

C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.

C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================

      IMPLICIT NONE

      CHARACTER*24 MODELE,CHARGE
      CHARACTER*24 TEMPER,DLAGTE,THETA
      CHARACTER*24 DEULTG

C ----------------------------------------------------------------------
C      DERIVEE DE LA TEMPERATURE : PASSAGE DE L'EULERIEN AU LAGRANGIEN

C IN  MODELE : NOM DU MODELE
C IN  CHARGE : LISTE DES CHARGES
C IN  TEMPER : CHAMP DE TEMPERATURE A L'INSTANT COURANT
C IN  THETA  : CHAMP DU VECTEUR THETA ET DE SON GRADIENT POUR LE CALCUL
C              DE LA DERIVEE EULERIENNE DE LA TEMPERATURE
C IN  DEULTG : CHAMP DE LA DERIVEE EULERIENNE DE T. CHAMP AUX POINTS
C              DE GAUSS. IL EST SUR LA BASE GLOBALE.
C OUT DLAGTE : CHAMP DE LA DERIVEE LAGRANGIENNE DE T. IL EST SUR LA
C              BASE VOLATILE.

C --- DEBUT DECLARATIONS NORMALISEES JEVEUX ----------------------------

      INTEGER ZI
      COMMON /IVARJE/ZI(1)
      REAL*8 ZR
      COMMON /RVARJE/ZR(1)
      COMPLEX*16 ZC
      COMMON /CVARJE/ZC(1)
      LOGICAL ZL
      COMMON /LVARJE/ZL(1)
      CHARACTER*8 ZK8
      CHARACTER*16 ZK16
      CHARACTER*24 ZK24
      CHARACTER*32 ZK32
      CHARACTER*80 ZK80
      COMMON /KVARJE/ZK8(1),ZK16(1),ZK24(1),ZK32(1),ZK80(1)

C --- FIN DECLARATIONS NORMALISEES JEVEUX ------------------------------
      CHARACTER*8 LPAIN(4),LPAOUT(1),K8BID
      CHARACTER*16 OPTION
      CHARACTER*24 LIGREL,LCHIN(4),LCHOUT(1)
      CHARACTER*24 CHGEOM,VECTTH

      INTEGER IRET,JCHAR,NCHAR
      INTEGER NCHIN,NCHOUT,NUMORD

      LOGICAL EXIGEO

C DEB ------------------------------------------------------------------

      CALL JEMARQ()

      CALL JEEXIN(CHARGE,IRET)
      IF (IRET.NE.0) THEN
        CALL JELIRA(CHARGE,'LONMAX',NCHAR,K8BID)
        IF (NCHAR.NE.0) THEN
          CALL JEVEUO(CHARGE,'L',JCHAR)
        END IF
      END IF

      LIGREL = MODELE(1:8)//'.MODELE'
      CALL MEGEOM(MODELE(1:8),ZK24(JCHAR) (1:8),EXIGEO,CHGEOM)

      NUMORD = 0
      CALL RSEXCH(THETA,'THETA',NUMORD,VECTTH,IRET)

      LPAIN(1) = 'PGEOMER'
      LCHIN(1) = CHGEOM
      LPAIN(2) = 'PTEMPER'
      LCHIN(2) = TEMPER
      LPAIN(3) = 'PVECTTH'
      LCHIN(3) = VECTTH
      LPAIN(4) = 'PDEULTG'
      LCHIN(4) = DEULTG
      NCHIN = 4

      LPAOUT(1) = 'PDLAGTE'
      LCHOUT(1) = DLAGTE
      NCHOUT = 1

      OPTION = 'DLAG_NOEU_TEMP'

      CALL CALCUL('S',OPTION,LIGREL,NCHIN,LCHIN,LPAIN,NCHOUT,LCHOUT,
     &            LPAOUT,'V')

C FIN ------------------------------------------------------------------
      CALL JEDEMA()

      END
