      SUBROUTINE  VERSST (NOMRES)
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 03/07/2012   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C (AT YOUR OPTION) ANY LATER VERSION.
C
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
C    1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
C ======================================================================
C***********************************************************************
C    P. RICHARD     DATE 13/10/92
C-----------------------------------------------------------------------
C  BUT:      < VERIFICATION DES SOUS-STRUCTURES >
      IMPLICIT NONE
C
C  VERIFIER LA COHERENCE DES MACRO_ELEMENTS MIS EN JEU ET
C  NOTAMMENT LA GRANDEUR SOUS-JACENTE ET
C  CREATION DU .DESC STOCKANT CES INFORMATIONS
C
C-----------------------------------------------------------------------
C
C NOMRES   /I/: NOM UTILISATEUR DU RESULTAT
C
C
      INCLUDE 'jeveux.h'
      INTEGER VALI(2)
C
C
C
      CHARACTER*24 VALK(4)
      CHARACTER*8 NOMRES,NMSSTR,NMSST,NMMCLR,NMMCL,BLANC
      LOGICAL PBLOG
      CHARACTER*1 K1BID
C
C-----------------------------------------------------------------------
C-----------------------------------------------------------------------
      INTEGER I ,IBID ,LDDESC ,LLDESC ,NBCMPR ,NBECR ,NBSST 
      INTEGER NUMGD ,NUMGDR 
C-----------------------------------------------------------------------
      DATA BLANC /'        '/
C-----------------------------------------------------------------------
C
      CALL JEMARQ()
      PBLOG=.FALSE.
C
C------------RECUPERATION DU NOMBRE DE MACR_ELEM MIS EN JEU-------------
C
      CALL JELIRA(NOMRES//'      .MODG.SSME','LONMAX',NBSST,K1BID)
C
C------RECUPERATION VALEURS DE REFERENCE GRANDEUR SOUS-JACENTE----------
C      (ON PREND CELLES DU PREMIER MACR_ELEM)
C
      NMSSTR=BLANC
      CALL MGUTDM(NOMRES,NMSSTR,1,'NOM_MACR_ELEM',IBID,NMMCLR)
      CALL JEVEUO(NMMCLR//'.MAEL_DESC','L',LLDESC)
      NBECR=ZI(LLDESC)
      NBCMPR=ZI(LLDESC+1)
      NUMGDR=ZI(LLDESC+2)
C
C----------------BOUCLE SUR TOUS LES MACR_ELEM MIS EN JEU---------------
C
      DO 10 I=1,NBSST
        NMSST=BLANC
        CALL MGUTDM(NOMRES,NMSST,I,'NOM_MACR_ELEM',IBID,NMMCL)
        CALL JEVEUO(NMMCL//'.MAEL_DESC','L',LLDESC)
        NUMGD=ZI(LLDESC+2)
        IF(NUMGDR.NE.NUMGD) THEN
          PBLOG=.TRUE.
          CALL JENUNO(JEXNUM(NOMRES//'      .MODG.SSNO',I),NMSST)
        VALK (1) = NMSSTR
        VALK (2) = NMMCLR
        VALK (3) = NMSST
        VALK (4) = NMMCL
        VALI (1) = NUMGDR
        VALI (2) = NUMGD
          CALL U2MESG('E', 'ALGORITH14_73',4,VALK,2,VALI,0,0.D0)
        ENDIF
10    CONTINUE
C
      IF(PBLOG) THEN
        CALL U2MESG('F', 'ALGORITH14_74',0,' ',0,0,0,0.D0)
      ENDIF
C
      CALL WKVECT(NOMRES//'      .MODG.DESC','G V I',3,LDDESC)
      ZI(LDDESC)=NBECR
      ZI(LDDESC+1)=NBCMPR
      ZI(LDDESC+2)=NUMGDR
C
      CALL JEDEMA()
      END
