      SUBROUTINE VICIN1(NDIM,G,NPG,LGPG,VIM,FDAT,NBCIN,NUMCIN) 
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 08/12/2009   AUTEUR PROIX J-M.PROIX 
C ======================================================================
C COPYRIGHT (C) 1991 - 2009  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
      IMPLICIT NONE
      INTEGER NDIM,G,NPG,LGPG,I,J,NBCIN,NUMCIN(2)
      REAL*8 VIM(LGPG,NPG),FDAT(3,3),VIMM(3,3)
      REAL*8 VARI(3,3),VARIM(7),ESP(9)

C ---------------------------------
C   G       : NUMERO DU POINT DE GAUSS COURANT
C   NDIM    : DIMENSION DE L'ESPACE
C   NPG     : NOMBRE DE POINTS DE GAUSS
C   LGPG    : TAILLE DES VARIABLES INTERNES DEPEND DU COMPORTEMENT
C   VIM    : VARIABLE INTERNE EN T-
C   FDAT    : TRANSPOSEE DU TENSEUR DE DEFORMATION ENTRE CONFIGURATION
C             T- ET  CONFIGURATION INTERMEDIAIRE

C   SORTIE:
C   VIMM   : MATRICE CORRESPONDANT AU VECTEUR VIM
C   VARI   : MATRICE COMPOSEE DE FDAT^T VIMM FDAT
C   VARIM  : VECTEUR CORRESPONDANT A VARI
C ----------------------------
C
C     CALCUL DES ENTREES DE NMCOMP POUR SIMO_HUGHES1
C
C -------------------------
      
      CALL R8INIR(9,0.D0,VIMM,1)
      CALL R8INIR(9,0.D0,VARI,1) 
C     POUR SIMO_HUGHES1  UNE SEULE VI CINEMATIQUE      
      CALL ASSERT(NBCIN.EQ.1) 
                                   
      CALL TNSVEC(6,NDIM,VIMM,VIM(1,G),1.D0)
                         
C     MULTIPLICATION PAR f^T_{n+alpha}
      CALL UTBTAB('ZERO',3,3,VIMM,FDAT,ESP,VARI)
      
C     PREPARATION DES VARIABLES INTERNES POUR NMCOMP
C     VARIM : VECTEUR DE LONGUEUR 6 (SANS INDICATEUR PLASTIQUE)
C     MODIFICATION DES VARIABLES INTERNES POUR NMCOMP
      DO 2 I=1,3
         VIM(NUMCIN(1)-1+I,G)=VARI(I,I)
 2    CONTINUE
      VIM(NUMCIN(1)-1+4,G)=VARI(1,2)
      VIM(NUMCIN(1)-1+5,G)=VARI(1,3)
      VIM(NUMCIN(1)-1+6,G)=VARI(2,3)

      END
