      SUBROUTINE XMCONT(ALGOCR,COEFCR,COEFCP,COHES ,COHEO ,DDLM  ,
     &                  DDLS  ,FFC   ,FFP   ,IDEPD ,IDEPM ,
     &                  IFA   ,IFISS ,IMATE ,INDCO ,IPGF  ,
     &                  JAC   ,JFISNO,JHEAFA,MMAT  ,LACT  ,
     &                  NCOMPH,ND    ,NDDL  ,NDIM  ,NFH   ,
     &                  NFISS ,NNO   ,NNOL  ,NNOS  ,
     &                  NVIT,PLA   ,RELA  ,RR    ,
     &                  SINGU,TAU1,TAU2)
       IMPLICIT NONE
      INCLUDE 'jeveux.h'
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 19/12/2012   AUTEUR PELLET J.PELLET 
C ======================================================================
C COPYRIGHT (C) 1991 - 2012  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C TOLE CRP_21
C IN ALGOCR : ALGO CONTACT (1:LAG, 2:PENA, 3:COHESIF)
C IN COEFCR : COEF AUGMENTATION CONTACT
C IN COEFCP : COEF PENALISATION CONTACT
C IN COHES  : VARIABLE INTERNE COHESIVE
C IN DDLM   : NOMBRE DE DDLS A CHAQUE NOEUD MILIEU
C IN DDLS   : NOMBRE DE DDLS A CHAQUE NOEUD SOMMET
C IN FFC    : FONCTIONS DE FORME DE CONTACT
C IN FFP    : FONCTIONS DE FORME ELEMENT PARENT
C IN IDEPD  : ADRESSE INCREMENT DEPLACEMENT COURANT
C IN IDEPM  : ADRESSE DEPLACEMENT INSTANT -
C IN IFA    : NUMERO FACETTE DE CONTACT
C IN IFISS  : NUMERO FISSURE
C IN IMATE  : ADRESSE MATERIAU
C IN INDCO  : ETAT DE CONTACT POINT DE GAUSS
C IN IPGF   : NUMERO POINT DE GAUSS DE CONTACT
C IN IVFF   : ADRESSE FONCTION DE FORME EL PARENT
C IN JAC    : PRODUIT JACOBIEN*POIDS
C IN JFISNO
C IN JHEAFA
C OUT MMAT  : MATRICE ELEMENTAIRE DE CONTACT
C IN NCOMPH
C IN ND     : NORMALE A LA SURFACE DE CONTACT AU PG
C IN NDDL   : NOMBRE TOTAL DDL DE L ELEMENT
C IN NDIM   : DIMENSION DU MODELE
C IN NFH    : NOMBRE DE DDL HEAVISIDE
C IN NFISS  : NOMBRE DE FISSURES
C IN NOEUD  : FORMULATION AUX NOEUDS
C IN PLA    : PLACE DES DDLS DE LAGRANGE
C IN RELA   : LOI DE COMPORTEMENT COHESIVE
C IN RR     : RACINE RAYON A LA POINTE DE FISSURE
C IN SINGU  : ELEMENT ENRICHI CTIP OU ON
C IN TAU1   : 1ERE TANGENTE SURFACE DE CONTACT
C IN TAU2   : 2EME TANGENTE (3D)
       INTEGER ALGOCR,DDLM,DDLS
       INTEGER IDEPD,IDEPM,IFA,IFISS
       INTEGER IMATE,INDCO,IPGF,JFISNO,JHEAFA
       INTEGER NCOMPH,NDDL,NDIM,NFH,NFISS,LACT(8)
       INTEGER NNO,NNOL,NNOS,NVEC,NVIT,PLA(27)
       INTEGER SINGU
       REAL*8  ALPHA(3),AM(3),COHES(3),COEFCP,COEFCR
       REAL*8  DNOR(3),DSIDEP(6,6),DTANG(3),FFC(8),FFP(27)
       REAL*8  JAC,MMAT(216,216),ND(3),P(3,3),PP(3,3),RR
       REAL*8  SIGMA(6),SAUT(3),TAU1(3),TAU2(3),UN,RELA
       REAL*8  LAMB(3),DELTA(6),R,COHEO(3)
       CHARACTER*8 JOB
C       
C CAS FORMULATION LAGRANGIEN AUGMENTE
C             
       IF(ALGOCR.EQ.1) THEN
          IF(INDCO.EQ.0) THEN
            IF(NVIT.NE.0) THEN
            CALL XMMAA4(NNOL,PLA,FFC,
     &                  JAC,COEFCR,MMAT)
             ENDIF
          ELSE IF(INDCO.EQ.1) THEN
            CALL XMMAA3(NDIM,NNO,NNOS,NNOL,PLA,
     &                  FFC,FFP,JAC,NFH,ND,COEFCR,
     &                  SINGU,RR,DDLS,DDLM,
     &                  JFISNO,NFISS,IFISS,JHEAFA,NCOMPH,IFA,
     &                  MMAT )
          ENDIF
C
C CAS FORMULATION PENALISEE
C
       ELSE IF(ALGOCR.EQ.2) THEN
         IF(INDCO.EQ.0) THEN
            IF(NVIT.NE.0) THEN
               CALL XMMAA4(NNOL,PLA,FFC,
     &                     JAC,COEFCP,MMAT)
            ENDIF
          ELSE IF(INDCO.EQ.1) THEN
             CALL XMMPA3(NDIM,NNO,NNOS,NNOL,PLA,
     &                   FFC,FFP,JAC,NFH,ND,COEFCP,
     &                   SINGU,RR,DDLS,DDLM,
     &                   JFISNO,NFISS,IFISS,JHEAFA,NCOMPH,IFA,
     &                   MMAT )
          ENDIF 
C
C CAS LOI COHESIVE
C
        ELSE IF(ALGOCR.EQ.3) THEN
C
C CAS DES LOIS COHESIVES REGULARISEES
C
          IF(RELA.EQ.1.D0.OR.RELA.EQ.2.D0) THEN
           NVEC=2
           UN = 1.D0
           IF(NVIT.NE.0) THEN
           CALL XMMAA4(NNOL,PLA,FFC,
     &                 JAC,UN,MMAT)
           ENDIF           
           CALL XMMSA3(NDIM,NNO,NNOS,FFP,NDDL,NVEC,ZR(IDEPD),
     &                 ZR(IDEPM),ZR(IDEPM),NFH,SINGU,RR,DDLS,DDLM,
     &                 JFISNO,NFISS,IFISS,JHEAFA,NCOMPH,IFA,
     &                 SAUT)
           JOB='MATRICE'
           CALL XMMSA2(NDIM ,IPGF  ,IMATE   ,SAUT ,ND  ,
     &                 TAU1 ,TAU2  ,COHES       ,JOB  ,RELA,
     &                 ALPHA,DSIDEP,SIGMA       ,PP   ,DNOR,
     &                 DTANG,P     ,AM)
C --- CALCUL DES MATRICES DE COHESION 
C
           CALL XMMCO1(NDIM,NNO,DSIDEP,PP,P,
     &                 ND,NFH,DDLS,JAC,FFP,
     &                 SINGU,RR,TAU1,TAU2,MMAT)
          ELSE IF(RELA.EQ.3.D0.OR.RELA.EQ.4.D0) THEN
C
C CAS DES LOIS MIXTES CZM_TAC_MIX ET CZM_OUV_MIX
C
C --- ON COMMENCE EGALEMENT PAR CALCULER LE SAUT
C
           NVEC = 2
           CALL XMMSA3(NDIM,NNO,NNOS,FFP,NDDL,NVEC,ZR(IDEPD),
     &                 ZR(IDEPM),ZR(IDEPM),NFH,SINGU,RR,DDLS,DDLM,
     &                 JFISNO,NFISS,IFISS,JHEAFA,NCOMPH,IFA,
     &                 SAUT)
C
C --- ON CALCULE ENSUITE LA VALEUR DE LA FORCE COHESIVE
C
           NVEC = 2
           CALL XXLAG2(FFC   ,IDEPD ,IDEPM ,LACT  ,NDIM  ,
     &                 NNOL  ,PLA   ,LAMB  ,NVEC)
C
C --- ON VA ENSUITE ALLER CHERCHER LA MATRICE TGTE LOCALE
C --- ET LA MATRICE DE CHANGEMENT DE BASE
C
           JOB = 'MATRICE'
           CALL XMMSA5(NDIM ,IPGF  ,IMATE ,SAUT ,LAMB ,
     &                 ND   ,TAU1 ,TAU2  ,COHES ,JOB  ,
     &                 RELA ,ALPHA,DSIDEP,DELTA ,P    ,
     &                 AM   ,R)
C
C --- CALCUL DE LA MATRICE TANGENTE
C
          CALL XMMCO2(NDIM  ,NNO   ,NNOS  ,NNOL  ,DDLS  ,
     &                DDLM  ,DSIDEP,P     ,R     ,NFH   ,
     &                JAC   ,FFP   ,FFC   ,PLA   ,SINGU ,
     &                NFISS ,JHEAFA,JFISNO,IFA   ,NCOMPH,
     &                IFISS ,RR    ,MMAT)
          ENDIF
C
C --- ACTUALISATION INDICATEUR PREDICTION / CORRECTION
C
         COHEO(1)=COHES(1)
         COHEO(2)=COHES(2)
         COHEO(3)=2.D0
C
        ENDIF
       END
