      SUBROUTINE XMVEC0(NDIM,NNE,NNES,NNC,NFAES,LAMBD,
     &                 HPG,FFPC,JACOBI,CFACE,IAINES,
     &                 COEFCA,TYPMA,NDLS,VTMP)
C
C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 08/12/2009   AUTEUR PROIX J-M.PROIX 
C ======================================================================
C COPYRIGHT (C) 1991 - 2006  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C
      IMPLICIT NONE
      INTEGER  NDIM,NNE,NNES,NNC,NFAES,CFACE(3,5),IAINES,NDLS
      REAL*8   LAMBD,HPG,FFPC(9),JACOBI,COEFCA
      REAL*8   VTMP(168)
      CHARACTER*8  TYPMA
C
C ----------------------------------------------------------------------
C ROUTINE APPELLEE PAR : TE0365
C ----------------------------------------------------------------------
C ROUTINE SPECIFIQUE A L'APPROCHE <<GRANDS GLISSEMENTS AVEC XFEM>>,
C TRAVAIL EFFECTUE EN COLLABORATION AVEC I.F.P.
C ----------------------------------------------------------------------
C VECTEUR SECOND MEMBRE SI PAS DE CONTACT (XFEM)
C
C IN  NDIM   : DIMENSION DU PROBLEME
C IN  NNE    : NOMBRE DE NOEUDS DE LA MAILLE ESCLAVE
C IN  LAMBD  : LAGRANGE DE CONTACT AU POINT D'INTÈGRATION
C IN  HPG    : POIDS DU POINT INTEGRATION DU POINT DE CONTACT
C IN  FFPC   : FONCTIONS DE FORME DU POINT DE CONTACT
C IN  JACOBI : JACOBIEN DE LA MAILLE AU POINT DE CONTACT
C IN  COEFCA : COEF_REGU_CONT
C IN  COEFFS : COEF_STAB_CONT
C IN  COEFFP : COEF_PENA_CONT
C IN  NDLS   : NOMBRE DE DDLS D'UN NOEUD SOMMET ESCLAVE
C I/O VTMP   : VECTEUR SECOND MEMBRE ELEMENTAIRE DE CONTACT/FROTTEMENT
C ----------------------------------------------------------------------
      INTEGER I,IN,PL,XOULA
C ----------------------------------------------------------------------
C
C --------------------- CALCUL DE [C]-----------------------------------
C
      DO 10 I = 1,NNC
        IN=XOULA(CFACE,NFAES,I,IAINES,TYPMA)
        CALL XPLMA2(NDIM,NNE,NNES,NDLS,IN,PL)
        VTMP(PL) = -HPG*JACOBI*LAMBD*FFPC(I)/COEFCA
   10 CONTINUE
C
      END
