      SUBROUTINE XORIMA(NBMAF,JDLIMA,JCONX1,JCONX2,JCOOR,SENS)

      IMPLICIT REAL*8 (A-H,O-Z)

      CHARACTER*19 SENS
      INTEGER     NBMAF,JDLIMA,JCONX1,JCONX2,JCOOR

C            CONFIGURATION MANAGEMENT OF EDF VERSION
C MODIF ALGORITH  DATE 18/10/2011   AUTEUR COLOMBO D.COLOMBO 
C ======================================================================
C COPYRIGHT (C) 1991 - 2011  EDF R&D                  WWW.CODE-ASTER.ORG
C THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY  
C IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY  
C THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR     
C (AT YOUR OPTION) ANY LATER VERSION.                                   
C                                                                       
C THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT   
C WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF            
C MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU      
C GENERAL PUBLIC LICENSE FOR MORE DETAILS.                              
C                                                                       
C YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE     
C ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,         
C   1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.         
C ======================================================================
C RESPONSABLE COLOMBO D.COLOMBO
   

C     ----- DEBUT COMMUNS NORMALISES  JEVEUX  --------------------------
      INTEGER          ZI
      COMMON  /IVARJE/ ZI(1)
      REAL*8           ZR
      COMMON  /RVARJE/ ZR(1)
      COMPLEX*16       ZC
      COMMON  /CVARJE/ ZC(1)
      LOGICAL          ZL
      COMMON  /LVARJE/ ZL(1)
      CHARACTER*8      ZK8
      CHARACTER*16             ZK16
      CHARACTER*24                      ZK24
      CHARACTER*32                               ZK32
      CHARACTER*80                                        ZK80
      COMMON  /KVARJE/ ZK8(1), ZK16(1), ZK24(1), ZK32(1), ZK80(1)
      CHARACTER*32    JEXNUM
C     -----  FIN  COMMUNS NORMALISES  JEVEUX  --------------------------

      REAL*8      A(3),B(3),C(3),AB(3),AC(3),VN(3),VNREF(3),PS,DDOT
      REAL*8      NORME
      INTEGER     JSENS,IMAFIS,NMAAB1,NBNOM1,INOMA,NUNO(3),I,KMAFIS
      INTEGER     NMAAB2,NBNOM2,NUMNO1,NUMNO2,NMAADJ

      CALL JEMARQ()

      CALL WKVECT(SENS,'V V I',NBMAF,JSENS)

C     BOUCLE SUR LES MAILLES DE LA FISSURE
      ZI(JSENS-1+1)=1
      DO 1 IMAFIS=2,NBMAF

        NMAAB1=ZI(JDLIMA+IMAFIS-1)
        NBNOM1=ZI(JCONX2+NMAAB1) - ZI(JCONX2+NMAAB1-1)
C       RECUPERATION DES TROIS PREMIERS NOEUDS POUR CALCULER VN
        INOMA=1
        NUNO(INOMA)=ZI(JCONX1-1+ZI(JCONX2+NMAAB1-1)+INOMA-1)
        A(1)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+1)
        A(2)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+2)
        A(3)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+3)

        INOMA=2
        NUNO(INOMA)=ZI(JCONX1-1+ZI(JCONX2+NMAAB1-1)+INOMA-1)
        B(1)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+1)
        B(2)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+2)
        B(3)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+3)

        INOMA=3
        NUNO(INOMA)=ZI(JCONX1-1+ZI(JCONX2+NMAAB1-1)+INOMA-1)
        C(1)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+1)
        C(2)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+2)
        C(3)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+3)

        DO 11 I=1,3
          AB(I)=B(I)-A(I)
          AC(I)=C(I)-A(I)
 11     CONTINUE

C       CALCUL DE LA NORMALE A LA MAILLE TRIA3
        CALL PROVEC(AB,AC,VN)
        CALL NORMEV(VN,NORME)
C       RECHERCHE DUN ELEMENT ADJACENT PAR COMPARAISON DE LA 
C       CONNECTIVITE
        DO 12 KMAFIS=IMAFIS-1,1,-1
          NMAAB2=ZI(JDLIMA+KMAFIS-1)
          NBNOM2=ZI(JCONX2-1+NMAAB2+1) - ZI(JCONX2-1+NMAAB2)

           DO 121 INOMA1=1,NBNOM1
            NUMNO1=ZI(JCONX1-1+ZI(JCONX2+NMAAB1-1)+INOMA1-1)

            DO 1211 INOMA2=1,NBNOM2
              NUMNO2=ZI(JCONX1-1+ZI(JCONX2+NMAAB2-1)+INOMA2-1)

              IF (NUMNO1.EQ.NUMNO2)THEN
                NMAADJ=NMAAB2
                GO TO 13
              END IF

 1211       CONTINUE            

 121      CONTINUE

 12     CONTINUE

 13     CONTINUE

        INOMA=1
        NUNO(INOMA)=ZI(JCONX1-1+ZI(JCONX2+NMAADJ-1)+INOMA-1)
        A(1)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+1)
        A(2)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+2)
        A(3)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+3)

        INOMA=2
        NUNO(INOMA)=ZI(JCONX1-1+ZI(JCONX2+NMAADJ-1)+INOMA-1)
        B(1)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+1)
        B(2)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+2)
        B(3)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+3)

        INOMA=3
        NUNO(INOMA)=ZI(JCONX1-1+ZI(JCONX2+NMAADJ-1)+INOMA-1)
        C(1)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+1)
        C(2)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+2)
        C(3)=ZR(JCOOR-1+3*(NUNO(INOMA)-1)+3)

        DO 14 I=1,3
          AB(I)=B(I)-A(I)
          AC(I)=C(I)-A(I)
 14     CONTINUE
        

C       CALCUL DE LA NORMALE A LA MAILLE TRIA3 
        CALL PROVEC(AB,AC,VNREF)
        CALL NORMEV(VNREF,NORME)
        VNREF=ZI(JSENS-1+KMAFIS)*VNREF
        PS=DDOT(3,VN,1,VNREF,1)
C       STOCKAGE DU SENS DE L'ORIENTATION DE LA NORMALE
C       SI PRODUIT SCALAIRE NEGATIF, INVERSION NORAMALE
        IF(PS.LT.0)THEN
          ZI(JSENS-1+IMAFIS)=-1
        ELSE
          ZI(JSENS-1+IMAFIS)=1
        END IF
 1    CONTINUE 

      CALL JEDEMA()
      END
